import fs from 'node:fs/promises'
import path, {win32} from 'node:path'

import {beforeEach, describe, expect, it, vi} from 'vitest'

import {toForwardSlashes, writeSanityRuntime} from '../runtime'

vi.mock('node:fs/promises')
vi.mock('chokidar', () => ({default: {watch: vi.fn(() => ({on: vi.fn()}))}}))
vi.mock('../renderDocument', () => ({
  renderDocument: vi.fn(() => Promise.resolve('<html></html>')),
  decorateIndexWithAutoGeneratedWarning: vi.fn((html: string) => html),
  decorateIndexWithBridgeScript: vi.fn((html: string) => html),
  getPossibleDocumentComponentLocations: vi.fn(() => []),
}))
vi.mock('../sanityConfig', () => ({
  getSanityStudioConfigPath: vi.fn(() => Promise.resolve(null)),
}))

const CWD = '/home/user/project'

describe('Windows path normalization for ESM imports', () => {
  let writtenFiles: Record<string, string> = {}

  beforeEach(() => {
    vi.resetAllMocks()
    writtenFiles = {}
    vi.mocked(fs.mkdir).mockResolvedValue(undefined)
    vi.mocked(fs.writeFile).mockImplementation(async (filePath: unknown, content: unknown) => {
      writtenFiles[String(filePath)] = String(content)
    })
  })

  it('converts backslashes to forward slashes for JavaScript imports', () => {
    // Test with actual Windows path.relative() output
    const windowsPath = win32.relative(
      'C:\\project\\.sanity\\runtime',
      'C:\\project\\sanity.config.ts',
    )
    expect(windowsPath).toBe('..\\..\\sanity.config.ts') // Windows uses backslashes
    expect(toForwardSlashes(windowsPath)).toBe('../../sanity.config.ts') // Converts to forward slashes

    // Test with mixed separators and absolute paths
    expect(toForwardSlashes('C:\\Users\\test/project\\src/App.tsx')).toBe(
      'C:/Users/test/project/src/App.tsx',
    )
  })

  it('generates valid studio config imports with forward slashes', async () => {
    const {getSanityStudioConfigPath} = await import('../sanityConfig')
    vi.mocked(getSanityStudioConfigPath).mockResolvedValue(`${CWD}/sanity.config.ts`)

    await writeSanityRuntime({cwd: CWD, reactStrictMode: true, watch: false, isApp: false})

    const appJs = writtenFiles[path.join(CWD, '.sanity', 'runtime', 'app.js')]
    expect(appJs).toMatch(/from ["']\.\.\/\.\.\/sanity\.config\.ts["']/)
    expect(appJs).not.toContain('\\')
  })

  it('generates valid app entry imports with forward slashes', async () => {
    await writeSanityRuntime({
      cwd: CWD,
      reactStrictMode: true,
      watch: false,
      isApp: true,
      entry: './src/App',
    })

    const appJs = writtenFiles[path.join(CWD, '.sanity', 'runtime', 'app.js')]
    expect(appJs).toContain('import App from')
    expect(appJs).not.toContain('\\')
  })
})
