name: "Setup Environment"
description: "Sets up Node.js, pnpm, and installs dependencies"

inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: lts/*

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # ratchet:pnpm/action-setup@v5

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v6
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}

    - name: Install project dependencies
      run: pnpm install --ignore-scripts
      shell: bash
