name: "Setup Environment"
description: "Sets up Node.js, pnpm, and installs dependencies"

inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: lts

runs:
  using: composite
  steps:
    - uses: pnpm/setup@v1
      with:
        cache: true
        runtime: node@${{ inputs.node-version }}
