packages:
  - dev/*
  - perf/*
  - examples/*
  - scripts
  - e2e
  - packages/@repo/*
  - packages/@sanity/*
  - packages/create-sanity
  - packages/groq
  - packages/sanity
  - packages/sanity/fixtures/examples/*

catalog:
  '@playwright/experimental-ct-react': 1.56.1
  '@playwright/test': 1.56.1
  '@sanity/eslint-config-i18n': ^2.0.0
  '@sanity/pkg-utils': ^8.1.13
  '@sanity/ui': ^3.1.5
  '@sanity/ui-workshop': ^3.1.2
  '@types/node': ^24.3.0
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@types/react-is': ^19.0.0
  '@vitejs/plugin-react': ^4.6.0
  esbuild: 0.25.12
  esbuild-register: ^3.6.0
  eslint: ^9.37.0
  globals: ^16.2.0
  playwright: 1.56.1
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  react-is: ^19.1.1
  # Note: there is currently a test failure in src/core/form/inputs/files/FileInput/__tests__/fileInput.test.tsx
  # that blocks us from upgrading to jsdom@27 – once that test is passing, the jsdom override can be removed from
  # the workspace package.json.
  # × FileInput with empty state > renders the browse button with a tooltip when it has at least one element in assetSources 255ms
  #     → Cannot create property 'border-width' on string '1px solid var(--card-border-color)'
  jsdom: ^26.1.0
  vite: ^7.1.7
  vitest: ^3.2.4
  styled-components: ^6.1.18
  typescript: 5.9.3

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1

preferWorkspacePackages: true
linkWorkspacePackages: deep

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@oxlint/*'
  - '@oxlint-tsgolint/*'
  - '@portabletext/*'
  - '@sanity/*'
  - 'groq-js'
  - 'oxlint'
  - 'oxlint-tsgolint'
  - 'eslint-plugin-oxlint'
  - 'react-rx'
  - 'use-effect-event'
