packages:
  - dev/*
  - perf/*
  - examples/*
  - packages/@repo/*
  - packages/@sanity/*
  - packages/create-sanity
  - packages/groq
  - packages/sanity
  - packages/sanity/fixtures/examples/*

catalog:
  '@playwright/experimental-ct-react': 1.54.2
  '@playwright/test': 1.54.2
  '@sanity/eslint-config-i18n': ^2.0.0
  '@sanity/eslint-config-studio': ^5.0.2
  '@sanity/ui-workshop': ^2.1.4
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@types/react-is': ^19.0.0
  '@vitejs/plugin-react': ^4.6.0
  esbuild-register: ^3.6.0
  esbuild: 0.25.9
  globals: ^16.2.0
  i18next: ^23.16.8
  playwright: 1.54.2
  prettier: ^3.5.3
  react: ^19.1.1
  react-dom: ^19.1.1
  react-is: ^19.1.1
  styled-components: ^6.1.18
  typescript: 5.8.3

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
