packages:
  - dev/*
  - perf/*
  - examples/*
  - packages/@repo/*
  - packages/@sanity/*
  - packages/create-sanity
  - packages/groq
  - packages/sanity
  - packages/sanity/fixtures/examples/*

catalog:
  '@playwright/experimental-ct-react': 1.52.0
  '@playwright/test': 1.52.0
  '@sanity/eslint-config-i18n': ^2.0.0
  '@sanity/eslint-config-studio': ^5.0.2
  '@vitejs/plugin-react': ^4.5.2
  esbuild-register: ^3.6.0
  esbuild: 0.25.5
  globals: ^16.2.0
  playwright: 1.52.0
  prettier: ^3.5.3
  react: ^19.1.0
  react-dom: ^19.1.0
  styled-components: ^6.1.18
  typescript: 5.8.3

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
