packages:
  - 'dev/*'
  - 'perf/*'
  - 'examples/*'
  - 'packages/@repo/*'
  - 'packages/@sanity/*'
  - 'packages/create-sanity'
  - 'packages/groq'
  - 'packages/sanity'
  - 'packages/sanity/fixtures/examples/*'
