packages:
  - dev/*
  - perf/*
  - examples/*
  - scripts
  - e2e
  - packages/@repo/*
  - packages/@sanity/*
  - packages/groq
  - packages/sanity
  - packages/sanity/fixtures/examples/*

catalog:
  '@playwright/experimental-ct-react': 1.57.0
  '@playwright/test': 1.57.0
  '@sanity/client': ^7.14.1
  '@sanity/codegen': ^5.9.1
  '@sanity/eslint-config-i18n': ^2.0.0
  '@sanity/migrate': ^5.2.3
  '@sanity/pkg-utils': ^10.4.2
  '@sanity/telemetry': ^0.8.1
  '@sanity/ui': ^3.1.11
  '@sanity/ui-workshop': ^3.4.0
  '@types/node': ^24.3.0
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/react-is': ^19.2.0
  '@typescript/native-preview': 7.0.0-dev.20260112.1
  '@vitejs/plugin-react': ^5.1.2
  babel-plugin-styled-components: ^2.1.4
  esbuild: 0.27.2
  esbuild-register: ^3.6.0
  eslint: ^9.39.2
  globals: ^16.2.0
  jsdom: ^26.1.0
  playwright: 1.57.0
  prettier: ^3.8.1
  react: ^19.2.3
  react-dom: ^19.2.3
  react-is: ^19.2.3
  styled-components: npm:@sanity/styled-components@^6.1.24
  typescript: 5.9.3
  vite: ^7.3.1
  vitest: ^4.0.18

linkWorkspacePackages: deep

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@oxlint/*'
  - '@oxlint-tsgolint/*'
  - '@portabletext/*'
  - '@sanity/*'
  - '@types/*'
  - '@typescript/*'
  - csstype
  - get-it
  - groq-js
  - oxlint
  - oxlint-tsgolint
  - eslint-plugin-oxlint
  - react
  - react-dom
  - react-is
  - react-rx

overrides:
  '@sanity/types': ^5.0.0
  '@sanity/ui@3': $@sanity/ui
  jsdom: 26.1.0
  vitest: $vitest

patchedDependencies:
  '@sanity/codegen@5.9.1': patches/@sanity__codegen@5.9.1.patch

preferWorkspacePackages: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@octokit/endpoint@9.0.6'
  - '@octokit/plugin-paginate-rest@9.2.2'
  - '@reduxjs/toolkit@2.9.0 || 2.10.1 || 2.11.0'
  - '@sanity/mutate@0.11.0-canary.4'
  - '@sanity/sdk@2.1.2'
  - '@swc/core@1.13.5'
  - chokidar@4.0.3
  - groq@3.88.1-typegen-experimental.0
  - react-redux@9.2.0
  - reselect@5.1.1
  - rxjs@7.8.2
  - semver@5.7.2 || 6.3.1
  - undici@5.29.0
  - undici-types@6.21.0
  - vite@6.4.1
