packages:
  - dev/*
  - perf/*
  - examples/*
  - packages/@repo/*
  - packages/@sanity/*
  - packages/create-sanity
  - packages/groq
  - packages/sanity
  - packages/sanity/fixtures/examples/*

catalog:
  '@playwright/experimental-ct-react': 1.55.0
  '@playwright/test': 1.55.0
  '@sanity/eslint-config-i18n': ^2.0.0
  '@sanity/eslint-config-studio': ^5.0.2
  '@sanity/pkg-utils': ^8.1.13
  '@sanity/ui': 4.0.0-static.35
  '@sanity/ui-workshop': ^3.1.2
  '@types/node': ^24.3.0
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@types/react-is': ^19.0.0
  '@vitejs/plugin-react': ^4.6.0
  esbuild-register: ^3.6.0
  esbuild: 0.25.10
  globals: ^16.2.0
  playwright: 1.55.0
  prettier: ^3.5.3
  react: ^19.1.1
  react-dom: ^19.1.1
  react-is: ^19.1.1
  styled-components: ^6.1.18
  typescript: 5.9.2

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
  ui-v3:
    '@sanity/ui-v3': npm:@sanity/ui@^3.1.4
