packages:
  - dev/*
  - perf/*
  - examples/*
  - scripts
  - e2e
  - packages/@repo/*
  - packages/@sanity/*
  - packages/create-sanity
  - packages/groq
  - packages/sanity
  - packages/sanity/fixtures/examples/*

catalog:
  '@playwright/experimental-ct-react': 1.56.1
  '@playwright/test': 1.56.1
  '@sanity/client': ^7.13.1
  '@sanity/eslint-config-i18n': ^2.0.0
  '@sanity/pkg-utils': ^10.1.1
  '@sanity/ui': ^3.1.11
  '@sanity/ui-workshop': ^3.4.0
  '@types/node': ^24.3.0
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/react-is': ^19.2.0
  '@typescript/native-preview': 7.0.0-dev.20251128.1
  '@vitejs/plugin-react': ^5.1.1
  esbuild: 0.27.0
  esbuild-register: ^3.6.0
  eslint: ^9.39.1
  globals: ^16.2.0
  playwright: 1.56.1
  prettier: ^3.7.3
  react: ^19.2.1
  react-dom: ^19.2.1
  react-is: ^19.2.1
  # Note: there is currently a test failure in src/core/form/inputs/files/FileInput/__tests__/fileInput.test.tsx
  # that blocks us from upgrading to jsdom@27 – once that test is passing, the jsdom override can be removed from
  # the workspace package.json.
  # The test failure looks like this:
  # × FileInput with empty state > renders the browse button with a tooltip when it has at least one element in assetSources
  #     → Cannot create property 'border-width' on string '1px solid var(--card-border-color)'
  jsdom: ^26.1.0
  vite: ^7.2.6
  vitest: ^3.2.4
  styled-components: npm:@sanity/styled-components@^6.1.24
  typescript: 5.9.3

overrides:
  # The e2e-ui.yml workflow needs a @sanity/ui related override in the root package.json in order for it's pnpm add -w ./artifacts/sanity-ui-*.tgz to work its magic.
  '@sanity/ui@3': '$@sanity/ui'
  # We are currently blocked from upgrading to jsdom 27 because of a strange build error related to the new version of
  # cssstyle required by jsdom 27. If this error is no longer present, it's safe to remove the following override.
  jsdom: 26.1.0
  vitest: $vitest

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1

preferWorkspacePackages: true
linkWorkspacePackages: deep

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@oxlint/*'
  - '@oxlint-tsgolint/*'
  - '@portabletext/*'
  - '@sanity/*'
  - '@types/*'
  - '@typescript/*'
  - csstype
  - 'get-it'
  - 'groq-js'
  - 'oxlint'
  - 'oxlint-tsgolint'
  - 'eslint-plugin-oxlint'
  - 'react'
  - 'react-dom'
  - 'react-is'
  - 'react-rx'
  - 'use-effect-event'

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@octokit/endpoint@9.0.6'
  - '@octokit/plugin-paginate-rest@9.2.2'
  - '@reduxjs/toolkit@2.9.0 || 2.10.1 || 2.11.0'
  - '@sanity/mutate@0.11.0-canary.4'
  - '@sanity/sdk@2.1.2'
  - '@swc/core@1.13.5'
  - chokidar@4.0.3
  - groq@3.88.1-typegen-experimental.0
  - react-redux@9.2.0
  - reselect@5.1.1
  - rxjs@7.8.2
  - semver@5.7.2 || 6.3.1
  - undici@5.29.0
  - undici-types@6.21.0
  - vite@6.4.1
