// flow-typed signature: bac8006c66bade1f3c1323ac6c5f12b6
// flow-typed version: <<STUB>>/eslint-config-sanity_v^2.1.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-sanity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-sanity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-sanity/import' {
  declare module.exports: any;
}

declare module 'eslint-config-sanity/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-sanity/import.js' {
  declare module.exports: $Exports<'eslint-config-sanity/import'>;
}
declare module 'eslint-config-sanity/index' {
  declare module.exports: $Exports<'eslint-config-sanity'>;
}
declare module 'eslint-config-sanity/index.js' {
  declare module.exports: $Exports<'eslint-config-sanity'>;
}
declare module 'eslint-config-sanity/react.js' {
  declare module.exports: $Exports<'eslint-config-sanity/react'>;
}
