import {type SanityClient} from '@sanity/client'
import {mergeMap, range} from 'rxjs'

import {type DocGenTemplate} from './types'

export type ProgramArgs = {
  client: SanityClient
  number?: number
  published?: boolean
  size?: number
  draft?: boolean
  bundles?: string[]
  template: DocGenTemplate
  concurrency?: number
}

export function run(_args: ProgramArgs) {
  const {client, bundles, draft, concurrency, published, template, number, size} = _args
  const runId = Date.now()

  return range(0, number || 1).pipe(
    mergeMap((i) => {
      const id = `${runId}-autogenerated-${i}`

      const templateOptions = {
        size: size ?? 256,
        id,
      }

      const title = `Generated #${runId.toString(32).slice(2)}/${i}`

      const baseDocument = {...template({...templateOptions, title}), _id: id}

      const publishedDocument = {...baseDocument, title: `${title} - Published`}
      const draftDocument = {...baseDocument, _id: `drafts.${id}`, title: `${title} - Draft`}

      const bundleDocuments = bundles
        ? bundles.map((bundle) => ({
            ...baseDocument,
            _id: `versions.${bundle}.${id}`,
            title: `${title} - Bundle: ${bundle}`,
          }))
        : []

      return [published && publishedDocument, draft && draftDocument, bundleDocuments].flatMap(
        (d) => (d ? d : []),
      )
    }),
    mergeMap((doc) => {
      console.log('Creating', doc._id)
      return client.observable.create(doc, {autoGenerateArrayKeys: true})
    }, concurrency ?? 2),
  )
}
