name: 'Check Examples Only'
description: 'Checks if only files in the examples/ directory have changed'

outputs:
  examples_only:
    description: 'true if only examples/ files changed, false otherwise'
    value: ${{ steps.check.outputs.examples_only }}

runs:
  using: composite
  steps:
    - name: Check if only examples files changed
      id: check
      shell: bash
      run: |
        # Handle different event types
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          # For PRs, check files changed in the PR
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
        elif [ "${{ github.event_name }}" = "push" ]; then
          # For pushes, check files in the last commit
          CHANGED_FILES=$(git diff --name-only HEAD~1)
        else
          # For other event types (workflow_dispatch, etc.), do not skip
          echo "Event type ${{ github.event_name }} - not checking, will not skip"
          echo "examples_only=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Debug output
        echo "Changed files:"
        echo "$CHANGED_FILES"

        # Handle empty diffs (no changes)
        if [ -z "$CHANGED_FILES" ]; then
          echo "No files changed, will not skip"
          echo "examples_only=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Check if all changed files are in examples/ directory
        EXAMPLES_ONLY="true"
        while IFS= read -r file; do
          if [ -n "$file" ] && [[ ! "$file" =~ ^examples/ ]]; then
            EXAMPLES_ONLY="false"
            break
          fi
        done <<< "$CHANGED_FILES"

        echo "examples_only=$EXAMPLES_ONLY" >> $GITHUB_OUTPUT

        if [ "$EXAMPLES_ONLY" = "true" ]; then
          echo "Only examples/ files changed - workflows can skip"
        else
          echo "Non-examples files changed - workflows should run"
        fi
