declare module 'part:@sanity/storybook'
declare module 'part:@sanity/storybook/addons/actions'
declare module 'part:@sanity/storybook/addons/knobs'
declare module 'part:@sanity/storybook/addons/sanity'
declare module 'part:@sanity/storybook/components'
