/* eslint-disable camelcase */

export type {
  GeneralPreviewLayoutKey,
  PortableTextPreviewLayoutKey,
  PreviewLayoutKey,
  PreviewProps,
  PreviewMediaDimensions,
} from '../src/components/previews'

export type {
  AssetSourceResolver,
  AsyncComposableOption,
  ComposableOption,
  ConfigContext,
  DocumentActionsContext,
  DocumentActionsResolver,
  DocumentBadgesContext,
  DocumentBadgesResolver,
  DocumentPluginOptions,
  FormBuilderComponentResolverContext,
  NewDocumentCreationContext,
  NewDocumentOptionsContext,
  NewDocumentOptionsResolver,
  PartialContext,
  Plugin,
  PluginOptions,
  ResolveProductionUrlContext,
  SanityFormConfig,
  SchemaPluginOptions,
  Source,
  TemplateResolver,
  Tool,
  WorkspaceSummary,
} from '../src/config'

export {Timeline, TimelineController} from '../src/datastores'

export type {
  AuthState,
  AuthStore,
  CombinedDocument,
  DocumentRemoteMutationEvent,
  DocumentRemoteMutationVersionEvent,
  EditStateFor,
  LoginComponentProps,
  ParsedTimeRef,
  RemoteSnapshotEvent,
  RemoteSnapshotVersionEvent,
  SnapshotEvent,
  TimelineControllerOptions,
  TimelineOptions,
  Transaction,
  UserStore,
  WithVersion,
} from '../src/datastores'

export {deskTool, useDocumentPane} from '../src/desk'

export type {
  DefaultDocumentNodeResolver,
  DefaultDocumentNodeContext,
  DeskToolMenuItem,
  DeskToolOptions,
  PaneMenuItem,
  PaneMenuItemGroup,
  PaneView,
  RouterPaneGroup,
  RouterPaneSibling,
  RouterPanes,
  StructureBuilder,
  StructureResolver,
} from '../src/desk'

export type {
  ActionComponent,
  DocumentActionComponent,
  DocumentActionConfirmModalProps,
  DocumentActionDescription,
  DocumentActionModalProps,
  DocumentActionDialogModalProps,
  DocumentActionPopoverModalProps,
  DocumentActionProps,
  DocumentActionResolver,
} from '../src/desk/actions'

export type {
  DocumentBadgeComponent,
  DocumentBadgeProps,
  DocumentBadgeDescription,
} from '../src/desk/badges'

export {
  DeleteAction,
  PublishAction,
  DuplicateAction,
  UnpublishAction,
  DiscardChangesAction,
  HistoryRestoreAction,
} from '../src/desk/actions'

export {ConfirmDeleteDialog, usePaneRouter} from '../src/desk/components'

export type {ConfirmDeleteDialogProps} from '../src/desk/components'

export type {
  BackLinkProps,
  ChildLinkProps,
  EditReferenceOptions,
  PaneRouterContextValue,
  ParameterizedLinkProps,
  ReferenceChildLinkProps,
} from '../src/desk/components'

export type {DocumentPaneContextValue} from '../src/desk/panes/document/DocumentPaneContext'
export type {TimelineMode} from '../src/desk/panes/document/types'

export {
  ComponentBuilder,
  ComponentViewBuilder,
  DocumentBuilder,
  DocumentListBuilder,
  DocumentListItemBuilder,
  DocumentTypeListBuilder,
  FormViewBuilder,
  GenericListBuilder,
  GenericViewBuilder,
  InitialValueTemplateItemBuilder,
  ListBuilder,
  ListItemBuilder,
  MenuItemBuilder,
  MenuItemGroupBuilder,
} from '../src/desk/structureBuilder'

export type {
  BaseGenericList,
  BaseIntentParams,
  BaseView,
  BuildableComponent,
  BuildableGenericList,
  BuildableList,
  Child,
  ChildObservable,
  ChildResolver,
  ChildResolverOptions,
  Collection,
  CollectionBuilder,
  Component,
  ComponentInput,
  ComponentView,
  Divider,
  DocumentList,
  DocumentListInput,
  DocumentListItem,
  DocumentListItemInput,
  DocumentListOptions,
  DocumentNode,
  DocumentOptions,
  DocumentTypeListInput,
  EditorNode,
  FormView,
  GenericList,
  GenericListInput,
  Intent,
  IntentChecker,
  IntentJsonParams,
  IntentParams,
  ItemChild,
  List,
  ListDisplayOptions,
  ListInput,
  ListItem,
  ListItemChild,
  ListItemDisplayOptions,
  ListItemInput,
  ListItemSerializeOptions,
  MenuItem,
  MenuItemActionType,
  MenuItemGroup,
  MenuItemParamsType,
  PartialDocumentList,
  PartialDocumentListItem,
  PartialDocumentNode,
  PartialListItem,
  PartialMenuItem,
  Serializable,
  SerializeOptions,
  SerializePath,
  StructureContext,
  StructureNode,
  UnserializedListItem,
  UnserializedListItemChild,
  UserComponent,
  UserViewComponent,
  View,
  ViewBuilder,
} from '../src/desk/structureBuilder'

export type {Annotation, AnnotationDetails, Chunk, ChunkType} from '../src/field'

export type {
  ArrayFieldProps,
  ArrayInputProps,
  ArrayItemError,
  ArrayOfObjectsFormNode,
  ArrayOfObjectsInputProps,
  ArrayOfObjectsItemMember,
  ArrayOfObjectsMember,
  ArrayOfPrimitivesElementType,
  ArrayOfPrimitivesFormNode,
  ArrayOfPrimitivesInputProps,
  ArrayOfPrimitivesItemMember,
  ArrayOfPrimitivesMember,
  BaseFieldProps,
  BaseFormNode,
  BaseItemProps,
  BooleanFieldProps,
  BooleanFormNode,
  BooleanInputProps,
  DocumentFormNode,
  DuplicateKeysError,
  FieldError,
  FieldMember,
  FieldProps,
  FieldSetMember,
  FieldsetState,
  FormArrayInputFunctionsProps,
  FormBuilderArrayFunctionComponent,
  FormBuilderCustomMarkersComponent,
  FormBuilderMarkersComponent,
  FormDiffMatchPatch,
  FormFieldGroup,
  FormInsertPatch,
  FormInsertPatchPosition,
  FormPatch,
  FormPatchJSONValue,
  FormPatchOrigin,
  FormSetIfMissingPatch,
  FormSetPatch,
  FormUnsetPatch,
  IncompatibleTypeError,
  InputProps,
  InsertItemEvent,
  InvalidItemTypeError,
  ItemProps,
  MissingKeysError,
  MixedArray,
  MoveItemEvent,
  NodeValidation,
  NumberFieldProps,
  NumberFormNode,
  NumberInputProps,
  ObjectFieldProps,
  ObjectFormNode,
  ObjectInputProps,
  ObjectItemProps,
  ObjectMember,
  PatchArg,
  PatchEvent,
  PortableTextMarker,
  PrimitiveFormNode,
  PrimitiveItemProps,
  RenderArrayOfObjectsItemCallback,
  RenderArrayOfPrimitivesItemCallback,
  RenderCustomMarkers,
  RenderFieldCallback,
  RenderInputCallback,
  RenderItemCallback,
  RenderPreviewCallback,
  StringFieldProps,
  StringFormNode,
  StringInputProps,
  TypeAnnotationMismatchError,
  UndeclaredMembersError,
  ArrayInputMember,
} from '../src/form'

export type {
  FileLike,
  UploadEvent,
  UploadOptions,
  Uploader,
  UploaderResolver,
} from '../src/form/studio/uploads/types'

export type {FormFieldPresence} from '../src/presence'

export type {
  Route,
  RouteChildren,
  RouteSegment,
  RouteTransform,
  Router,
  RouterNode,
  RouterState,
} from '../src/router'

export type {
  ArrayFieldDefinition,
  FieldDefinition,
  InitialValueTemplateItem,
  ReferenceTarget,
  Template,
  TemplateParameter,
  TemplateResponse,
  TypeTarget,
} from '../src/templates'

export type {StudioTheme} from '../src/theme'
