export const CHANGELOG_MOCK_DATA = {
  currentVersion: '2.25.0',
  latestVersion: '2.27.0',
  changelog: [
    {
      changeItems: [
        {
          _key: 'c73a914baa12',
          _type: 'changeItem',
          changeType: 'feature',
          description: [
            {
              _key: '5a09c9e8f98f',
              _type: 'block',
              children: [
                {
                  _key: 'bbb7a11bf4c00',
                  _type: 'span',
                  marks: ['fd11d27c7ad1'],
                  text: 'Presence',
                },
                {
                  _key: 'bbb7a11bf4c01',
                  _type: 'span',
                  marks: [],
                  text:
                    ', the ability to see where your collaborators are, is now visible in document lists, search results, and reference previews.',
                },
              ],
              markDefs: [
                {
                  _key: 'fd11d27c7ad1',
                  _type: 'link',
                  href: 'https://www.sanity.io/blog/introducing-presence',
                },
              ],
              style: 'normal',
            },
            {
              _key: '5b46acd7278c',
              _type: 'image',
              alt: 'Presence avatars in document lists alt',
              asset: {
                _createdAt: '2022-02-16T11:32:16Z',
                _id: 'image-cf6078f389bf1374dded2caa7053fb6f06972a2b-1280x719-jpg',
                _rev: '869qAXrKOqVwZTP6BH8af7',
                _type: 'sanity.imageAsset',
                _updatedAt: '2022-02-16T11:32:16Z',
                assetId: 'cf6078f389bf1374dded2caa7053fb6f06972a2b',
                extension: 'jpg',
                metadata: {
                  _type: 'sanity.imageMetadata',
                  blurHash: 'MGRLq:l:y_yEv4L*s8tQXSpG{MRXSzkiOq',
                  dimensions: {
                    _type: 'sanity.imageDimensions',
                    aspectRatio: 1.7802503477051461,
                    height: 719,
                    width: 1280,
                  },
                  hasAlpha: false,
                  isOpaque: true,
                  lqip:
                    'data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAALABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAUGBAf/xAAfEAABBAIDAQEAAAAAAAAAAAABAAIDBAUREiExMoL/xAAWAQEBAQAAAAAAAAAAAAAAAAAEAgP/xAAdEQACAgIDAQAAAAAAAAAAAAABEQACAyEEEhNh/9oADAMBAAIRAxEAPwDrxoZid3OkyqYT4ZCdlOKtTLMbxkx1GR+vQ86Warania1schaAfFUVpXkb5dnS2NjUshxnMOUHdtfJMW4p2S6sVooZNfLHbCExz3d/8BCvs9qNwPzqzP/Z',
                  palette: {
                    _type: 'sanity.imagePalette',
                    darkMuted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#3f4544',
                      foreground: '#fff',
                      population: 0.24,
                      title: '#fff',
                    },
                    darkVibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#5c346c',
                      foreground: '#fff',
                      population: 0,
                      title: '#fff',
                    },
                    dominant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#2575f4',
                      foreground: '#fff',
                      population: 3.37,
                      title: '#fff',
                    },
                    lightMuted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#cab0a5',
                      foreground: '#000',
                      population: 0.08,
                      title: '#fff',
                    },
                    lightVibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#69bcfc',
                      foreground: '#000',
                      population: 0.01,
                      title: '#fff',
                    },
                    muted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#9c7d54',
                      foreground: '#fff',
                      population: 0.04,
                      title: '#fff',
                    },
                    vibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#2575f4',
                      foreground: '#fff',
                      population: 3.37,
                      title: '#fff',
                    },
                  },
                },
                mimeType: 'image/jpeg',
                originalFilename: 'presence-img.jpeg',
                path:
                  'images/3do82whm/herman_test/cf6078f389bf1374dded2caa7053fb6f06972a2b-1280x719.jpg',
                sha1hash: 'cf6078f389bf1374dded2caa7053fb6f06972a2b',
                size: 65699,
                uploadId: 'RTnHqLbbH4tMeTbIUjQhslEer4LV5eOp',
                url:
                  'https://cdn.sanity.io/images/3do82whm/herman_test/cf6078f389bf1374dded2caa7053fb6f06972a2b-1280x719.jpg',
              },
              caption: 'Presence avatars in document lists',
            },
          ],
          title: 'More presence',
        },
        {
          _key: '694c46f1dec9',
          _type: 'changeItem',
          changeType: 'feature',
          description: [
            {
              _key: 'b89e05f6835e',
              _type: 'block',
              children: [
                {
                  _key: '6bb603c247cb0',
                  _type: 'span',
                  marks: [],
                  text: 'You can now configure the default API version for Vision (',
                },
                {
                  _key: '6bb603c247cb1',
                  _type: 'span',
                  marks: ['79d582faf5aa'],
                  text: '#3127',
                },
                {
                  _key: '6bb603c247cb2',
                  _type: 'span',
                  marks: [],
                  text: ')',
                },
              ],
              markDefs: [
                {
                  _key: '79d582faf5aa',
                  _type: 'link',
                  href: 'https://github.com/sanity-io/sanity/pull/3127',
                },
              ],
              style: 'normal',
            },
          ],
          title: 'Default Vision API version',
        },
        {
          _key: 'b4d26ba0187f',
          _type: 'changeItem',
          changeType: 'bugfix',
          description: [
            {
              _key: '773582950456',
              _type: 'block',
              children: [
                {
                  _key: '72037efa11dc0',
                  _type: 'span',
                  marks: [],
                  text:
                    'Removes a false positive validation error with some nested image and file fields (',
                },
                {
                  _key: '72037efa11dc1',
                  _type: 'span',
                  marks: ['af92f4a51daa'],
                  text: '#3119',
                },
                {
                  _key: '72037efa11dc2',
                  _type: 'span',
                  marks: [],
                  text: ')',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [
                {
                  _key: 'af92f4a51daa',
                  _type: 'link',
                  href: 'https://github.com/sanity-io/sanity/pull/3119',
                },
              ],
              style: 'normal',
            },
            {
              _key: '783802b49050',
              _type: 'block',
              children: [
                {
                  _key: '95301f6cdf1e0',
                  _type: 'span',
                  marks: [],
                  text:
                    'Fixes a bug where adding marks to a Portable Text block would remove some existing marks (',
                },
                {
                  _key: '95301f6cdf1e1',
                  _type: 'span',
                  marks: ['72cc5d07a0fc'],
                  text: '#3124',
                },
                {
                  _key: '95301f6cdf1e2',
                  _type: 'span',
                  marks: [],
                  text: ')',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [
                {
                  _key: '72cc5d07a0fc',
                  _type: 'link',
                  href: 'https://github.com/sanity-io/sanity/pull/3124',
                },
              ],
              style: 'normal',
            },
            {
              _key: '956176ace2a7',
              _type: 'block',
              children: [
                {
                  _key: 'cfdcc8961d540',
                  _type: 'span',
                  marks: [],
                  text:
                    'Fixes a bug where list items in Portable Text without a level would cause an error (',
                },
                {
                  _key: 'cfdcc8961d541',
                  _type: 'span',
                  marks: ['a60cea1960f3'],
                  text: '#3129',
                },
                {
                  _key: 'cfdcc8961d542',
                  _type: 'span',
                  marks: [],
                  text: ')',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [
                {
                  _key: 'a60cea1960f3',
                  _type: 'link',
                  href: 'https://github.com/sanity-io/sanity/pull/3129',
                },
              ],
              style: 'normal',
            },
            {
              _key: '3d79a4fb7c23',
              _type: 'block',
              children: [
                {
                  _key: '6bc84ce87e9a0',
                  _type: 'span',
                  marks: [],
                  text: 'Fixes a bug where read-only arrays showed an empty actions menu (',
                },
                {
                  _key: '6bc84ce87e9a1',
                  _type: 'span',
                  marks: ['26bfba94f0ce'],
                  text: '#3130',
                },
                {
                  _key: '6bc84ce87e9a2',
                  _type: 'span',
                  marks: [],
                  text: ')',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [
                {
                  _key: '26bfba94f0ce',
                  _type: 'link',
                  href: 'https://github.com/sanity-io/sanity/pull/3130',
                },
              ],
              style: 'normal',
            },
            {
              _key: '3fdefbad2146',
              _type: 'block',
              children: [
                {
                  _key: '0a2b746f324b0',
                  _type: 'span',
                  marks: [],
                  text: 'Improves empty read-only state for arrays (',
                },
                {
                  _key: '0a2b746f324b1',
                  _type: 'span',
                  marks: ['8014b6b94958'],
                  text: '#3131',
                },
                {
                  _key: '0a2b746f324b2',
                  _type: 'span',
                  marks: [],
                  text: ')',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [
                {
                  _key: '8014b6b94958',
                  _type: 'link',
                  href: 'https://github.com/sanity-io/sanity/pull/3131',
                },
              ],
              style: 'normal',
            },
            {
              _key: 'bc40242d0308',
              _type: 'block',
              children: [
                {
                  _key: '30df2f77288d0',
                  _type: 'span',
                  marks: [],
                  text: 'Adds validation warnings on incorrectly implemented asset sources (',
                },
                {
                  _key: '30df2f77288d1',
                  _type: 'span',
                  marks: ['5084c1b4d506'],
                  text: '#3135',
                },
                {
                  _key: '30df2f77288d2',
                  _type: 'span',
                  marks: [],
                  text: ')',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [
                {
                  _key: '5084c1b4d506',
                  _type: 'link',
                  href: 'https://github.com/sanity-io/sanity/pull/3135',
                },
              ],
              style: 'normal',
            },
          ],
        },
      ],
      version: '2.27.0',
    },
    {
      changeItems: [
        {
          _key: '19f2f0d76fc3',
          _type: 'changeItem',
          changeType: 'feature',
          description: [
            {
              _key: 'c4115d819eb7',
              _type: 'block',
              children: [
                {
                  _key: '5ab684e11f740',
                  _type: 'span',
                  marks: [],
                  text: 'Empty state takes up much less vertical space',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [],
              style: 'normal',
            },
            {
              _key: '86426c058c8f',
              _type: 'block',
              children: [
                {
                  _key: '34d176b69d0a0',
                  _type: 'span',
                  marks: [],
                  text:
                    'Image is vertically responsive to the height of the window, taking up less vertical space',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [],
              style: 'normal',
            },
            {
              _key: '84f8dc6d76e5',
              _type: 'block',
              children: [
                {
                  _key: '463db2181ec90',
                  _type: 'span',
                  marks: [],
                  text: 'Images are no longer enlarged to fit the size of the field',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [],
              style: 'normal',
            },
            {
              _key: 'e2c3c7d0ba8d',
              _type: 'block',
              children: [
                {
                  _key: '2cacc169df640',
                  _type: 'span',
                  marks: [],
                  text: 'Options to copy image url and download the image',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [],
              style: 'normal',
            },
            {
              _key: 'd2ac64c5b86b',
              _type: 'image',
              alt: 'Image Input alt',
              asset: {
                _createdAt: '2022-02-16T12:07:41Z',
                _id: 'image-d441e880ad146bbcbcfbb00d708c85afec71efc7-1280x659-png',
                _rev: '869qAXrKOqVwZTP6BHBAql',
                _type: 'sanity.imageAsset',
                _updatedAt: '2022-02-16T12:07:41Z',
                assetId: 'd441e880ad146bbcbcfbb00d708c85afec71efc7',
                extension: 'png',
                metadata: {
                  _type: 'sanity.imageMetadata',
                  blurHash: 'MmOgTnIU~q%Mt7-;j[M{R*j[-;t7IoR*ay',
                  dimensions: {
                    _type: 'sanity.imageDimensions',
                    aspectRatio: 1.9423368740515934,
                    height: 659,
                    width: 1280,
                  },
                  hasAlpha: true,
                  isOpaque: true,
                  lqip:
                    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAKCAYAAAC0VX7mAAAACXBIWXMAABYlAAAWJQFJUiTwAAACd0lEQVQokUWS+0tTYRjH93f1m1BgkD+koGVSSYGXCNOoMCIiqIyQYZq31GnqdKhbG3M6L02SKDGyNCHLSp3OXc45u5ztXDbnJ87J8oUv7/vCOR8+z/M+FlGKE40JxESJUCTKr+0gm1s7bAX3CIbC7IUjZnaN7IfZCe0TDO2b3yuqxsHBAfl8nsPDQ4xlSWcUkkmZmCCxsv6N17PzjPn8eOYC+BYWmVpYxBt4a96dM3M4JqeZ8M/ycW0dMZ5AVVV0XSWfPzChFk3TMaAxMc77T1/on3DT63Ay7Pbh8PoZ9fqxe6YYdE1iG3fTPTqB3eNjefUromQAFXTdMM2ZtkdAFUFMsPR5jWH3JIMuL2O+OZzTb3D6A2bGp+YZ9c4w4plm/t2S2ZKUnEbXdbNkI9lc7hhoGC58WMbaN0hTRy8ttmE67ePYxj30OFy0DozwrLuf5p5XuGcD7OyGkOU0xv//gdnsMTASE/HMBrh+/xEVdbepvvuAO0+aedjSQWOTlau37nH+WgOVDY20D9jZ/L2NnM6QURQ0XTdNDZZF1XQyGZX9iMCIy0tZVR0FJRUUXaziXE095bU3OVtZw8mSCk6cLuFU8QUeW1+w8eOnaSjLaROqqCqqqv01zCgq4aiAw+WlorqewtJLFFfWUlZ1w9zPlF/hdNllCopKKSwu56m1jY3vm8jJJOmUjK7pZv8MS0s2m0PTsyRTMssrq/QNOXjeZaOz30734CjttiHaegZofdlPc2sn1rYuvD4/we0dUpKEnEigmaOTxajW8q+hxpMriooUT5hDK0hxjKEXjPNRYoJAJBojGo0hCiKSIBEX4yQSKZIpo/wMfwBFlZ+ReSuIhAAAAABJRU5ErkJggg==',
                  palette: {
                    _type: 'sanity.imagePalette',
                    darkMuted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#3e4e57',
                      foreground: '#fff',
                      population: 9.96,
                      title: '#fff',
                    },
                    darkVibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#13242e',
                      foreground: '#fff',
                      population: 0.19,
                      title: '#fff',
                    },
                    dominant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#73858a',
                      foreground: '#fff',
                      population: 10.05,
                      title: '#fff',
                    },
                    lightMuted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#aab3b9',
                      foreground: '#000',
                      population: 9.93,
                      title: '#fff',
                    },
                    lightVibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#f3fcfb',
                      foreground: '#000',
                      population: 1.23,
                      title: '#000',
                    },
                    muted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#73858a',
                      foreground: '#fff',
                      population: 10.05,
                      title: '#fff',
                    },
                    vibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#4a8db4',
                      foreground: '#fff',
                      population: 0,
                      title: '#fff',
                    },
                  },
                },
                mimeType: 'image/png',
                originalFilename: 'image-1.png',
                path:
                  'images/3do82whm/herman_test/d441e880ad146bbcbcfbb00d708c85afec71efc7-1280x659.png',
                sha1hash: 'd441e880ad146bbcbcfbb00d708c85afec71efc7',
                size: 711461,
                uploadId: 'B8NirgF91rANDcgzdA2NyU4Hg0P35iQC',
                url:
                  'https://cdn.sanity.io/images/3do82whm/herman_test/d441e880ad146bbcbcfbb00d708c85afec71efc7-1280x659.png',
              },
              caption: 'Image Input',
            },
          ],
          title: 'Updated image input',
        },
        {
          _key: 'a9b942fd297ab532a766f9c8553cd370',
          _type: 'changeItem',
          changeType: 'feature',
          description: [
            {
              _key: 'a828feb45c9f',
              _type: 'block',
              children: [
                {
                  _key: 'a018984566750',
                  _type: 'span',
                  marks: [],
                  text: 'Empty state takes up much less vertical space',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [],
              style: 'normal',
            },
            {
              _key: 'e81351302d04',
              _type: 'block',
              children: [
                {
                  _key: '72092df11b4f0',
                  _type: 'span',
                  marks: [],
                  text: 'Field with file selected also takes up less vertical space',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [],
              style: 'normal',
            },
            {
              _key: '80ffd0050183',
              _type: 'block',
              children: [
                {
                  _key: '4c447492241c0',
                  _type: 'span',
                  marks: [],
                  text: 'Display original file name and size',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [],
              style: 'normal',
            },
            {
              _key: 'c7784b30f92d',
              _type: 'block',
              children: [
                {
                  _key: '3d4acad9b7230',
                  _type: 'span',
                  marks: [],
                  text: 'Options to download the file or copy the url',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [],
              style: 'normal',
            },
            {
              _key: 'fe3571a050aa',
              _type: 'image',
              alt: 'File Input alt',
              asset: {
                _createdAt: '2022-02-16T12:07:20Z',
                _id: 'image-35f2fc0573d10b238c6a8259bf4f2afc03e72488-1279x628-png',
                _rev: 'LV30YrzKNkA2K504Yb3LmC',
                _type: 'sanity.imageAsset',
                _updatedAt: '2022-02-16T12:07:20Z',
                assetId: '35f2fc0573d10b238c6a8259bf4f2afc03e72488',
                extension: 'png',
                metadata: {
                  _type: 'sanity.imageMetadata',
                  blurHash: 'M8S$ov%MD%t7-;~qIUWAa}RjV@R*j[ofkC',
                  dimensions: {
                    _type: 'sanity.imageDimensions',
                    aspectRatio: 2.036624203821656,
                    height: 628,
                    width: 1279,
                  },
                  hasAlpha: true,
                  isOpaque: true,
                  lqip:
                    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAKCAYAAAC0VX7mAAAACXBIWXMAABYlAAAWJQFJUiTwAAABMElEQVQokY1S2Y6DQAyb///TbSlzX8zhlQO0lehW+xANContOFGlVDjn8HisWJYFWmvknDHGwJzzfzH2WmBCbdsG5zzu9wU/txu0Mai1PgHHpxhDovcB9tda0HuTetV7R0oZ1joJfjP3Daz1jlo3lFpRSkEpGa1t0ieAORfEGKWArN/GIyBVxZgQQgQtI8auuEO1RoX7T7KOcTRelL0AWcd66zzSm99PhWThIviSnSS7T/Py9gOQCgkYDpXMMRQX4H2AtRbG2IuPf46ckizT+YAQk/TQOvWS7wTQWCsWtNbEz/fz2cGajBl8gLMW3jmZjnmGOs0kAKULEzdX9zGYl5HnlAYZlRehDexjhefdpnSczwb1ZD9MPZnOODco59KajEWLjDbQywq9aiHwPsKHiF+irQ+YPMydlQAAAABJRU5ErkJggg==',
                  palette: {
                    _type: 'sanity.imagePalette',
                    darkMuted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#545556',
                      foreground: '#fff',
                      population: 0.03,
                      title: '#fff',
                    },
                    darkVibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#6e5516',
                      foreground: '#fff',
                      population: 0,
                      title: '#fff',
                    },
                    dominant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#868586',
                      foreground: '#fff',
                      population: 0.54,
                      title: '#fff',
                    },
                    lightMuted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#ccb1b4',
                      foreground: '#000',
                      population: 0.17,
                      title: '#fff',
                    },
                    lightVibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#f8f0dc',
                      foreground: '#000',
                      population: 0.01,
                      title: '#000',
                    },
                    muted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#868586',
                      foreground: '#fff',
                      population: 0.54,
                      title: '#fff',
                    },
                    vibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#d4a32a',
                      foreground: '#000',
                      population: 0,
                      title: '#fff',
                    },
                  },
                },
                mimeType: 'image/png',
                originalFilename: 'file-1.png',
                path:
                  'images/3do82whm/herman_test/35f2fc0573d10b238c6a8259bf4f2afc03e72488-1279x628.png',
                sha1hash: '35f2fc0573d10b238c6a8259bf4f2afc03e72488',
                size: 125529,
                uploadId: 'StOlGVZi7tTmAJgULVE2X4JBQUGPJjtX',
                url:
                  'https://cdn.sanity.io/images/3do82whm/herman_test/35f2fc0573d10b238c6a8259bf4f2afc03e72488-1279x628.png',
              },
              caption: 'File Input',
            },
          ],
          title: 'Updated file input',
        },
        {
          _key: 'f4eb887bd808',
          _type: 'changeItem',
          changeType: 'feature',
          description: [
            {
              _key: 'b2ab1d93b309',
              _type: 'image',
              alt: 'PTE review changes alt',
              asset: {
                _createdAt: '2022-02-09T14:49:54Z',
                _id: 'image-0169085d09424d82c24d2c6ba3b4c71fe8e093e4-1280x665-png',
                _rev: 'QU9a42E9Ryq24nhllqP0pH',
                _type: 'sanity.imageAsset',
                _updatedAt: '2022-02-09T14:49:54Z',
                assetId: '0169085d09424d82c24d2c6ba3b4c71fe8e093e4',
                extension: 'png',
                metadata: {
                  _type: 'sanity.imageMetadata',
                  blurHash: 'M9SY{oV=o$?bxuDhs,NHj[xu?w?cD%M_t7',
                  dimensions: {
                    _type: 'sanity.imageDimensions',
                    aspectRatio: 1.9248120300751879,
                    height: 665,
                    width: 1280,
                  },
                  hasAlpha: false,
                  isOpaque: true,
                  lqip:
                    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAKCAIAAAA7N+mxAAAACXBIWXMAAAsTAAALEwEAmpwYAAABD0lEQVQokaWQa2uDMBSG8/9/2Kh+2Id2jLUxxkusrU6jieZiLo7aWsaQwdjDQ8iBvJycA5xzSqnxhpBSGmP8wjw/9N47ZwfeEZIiFMUIYYyzLK/rGmitq6pMMEwwJHnc0UqKXsm7TEk2aW6mkbOGkDSOY4xxmqRleWE9A1qNJTnBj93p/QUddyR5vZD96uFavLXVUfCzGGnXtbRtKaV914tRGGOA1uP1DHEUYrjDMMAwSKIwiYK7KQqvZD/0hTHSWmMXnHPLXDOYJtV8XkiOSBY9ztU8g0WOmrpQkntv77tYN3IDWGuHYWCsZ4xxzhb48845k1JYa+ctgPf++ZlNnn02wj/q709/iW2H/8S/wl/Ysz2Yfy02zwAAAABJRU5ErkJggg==',
                  palette: {
                    _type: 'sanity.imagePalette',
                    darkMuted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#373737',
                      foreground: '#fff',
                      population: 0.34,
                      title: '#fff',
                    },
                    darkVibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#7c6508',
                      foreground: '#fff',
                      population: 0,
                      title: '#fff',
                    },
                    dominant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#c3bfab',
                      foreground: '#000',
                      population: 2.47,
                      title: '#fff',
                    },
                    lightMuted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#c3bfab',
                      foreground: '#000',
                      population: 2.47,
                      title: '#fff',
                    },
                    lightVibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#fcf4d3',
                      foreground: '#000',
                      population: 0.39,
                      title: '#000',
                    },
                    muted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#9d9887',
                      foreground: '#000',
                      population: 2.08,
                      title: '#fff',
                    },
                    vibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#eec310',
                      foreground: '#000',
                      population: 0,
                      title: '#fff',
                    },
                  },
                },
                mimeType: 'image/png',
                originalFilename: 'image.png',
                path:
                  'images/3do82whm/herman_test/0169085d09424d82c24d2c6ba3b4c71fe8e093e4-1280x665.png',
                sha1hash: '0169085d09424d82c24d2c6ba3b4c71fe8e093e4',
                size: 226180,
                uploadId: 'Ho859f1BYzF8zOhQwIZOe6SAiA7xr81G',
                url:
                  'https://cdn.sanity.io/images/3do82whm/herman_test/0169085d09424d82c24d2c6ba3b4c71fe8e093e4-1280x665.png',
              },
              caption: 'PTE review changes',
            },
          ],
          title: 'Improved change indicator highlighting in Portable Text Editor',
        },
        {
          _key: '2aa32363563b',
          _type: 'changeItem',
          changeType: 'feature',
          description: [
            {
              _key: 'b65fdf4b067f',
              _type: 'block',
              children: [
                {
                  _key: '003c85efca6a0',
                  _type: 'span',
                  marks: [],
                  text: 'Shows full name, email and login provider of the logged in user',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [],
              style: 'normal',
            },
            {
              _key: '382a2d80c380',
              _type: 'block',
              children: [
                {
                  _key: 'fb894b88f8140',
                  _type: 'span',
                  marks: [],
                  text: 'Link to project management interface',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [],
              style: 'normal',
            },
            {
              _key: 'b3ad8c0ef9c2',
              _type: 'image',
              alt: 'Login popover improvements alt',
              asset: {
                _createdAt: '2022-02-16T12:20:01Z',
                _id: 'image-707c10d8643fdffaee08833b470146e3ecfc5d8d-710x458-png',
                _rev: 'LV30YrzKNkA2K504Yb4CUm',
                _type: 'sanity.imageAsset',
                _updatedAt: '2022-02-16T12:20:01Z',
                assetId: '707c10d8643fdffaee08833b470146e3ecfc5d8d',
                extension: 'png',
                metadata: {
                  _type: 'sanity.imageMetadata',
                  blurHash: 'V6P?:h_M?uM{M}000KWCxtfS004nRQx[bv00D%RQxubb',
                  dimensions: {
                    _type: 'sanity.imageDimensions',
                    aspectRatio: 1.5502183406113537,
                    height: 458,
                    width: 710,
                  },
                  hasAlpha: true,
                  isOpaque: true,
                  lqip:
                    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAANCAYAAACpUE5eAAAACXBIWXMAABYlAAAWJQFJUiTwAAACN0lEQVQ4jZWSy2sTURjF8x/Yh32obaH4QNBdSa1SRbGIC1Erli7MoyspdaUbEUQR3SjUiFgq+ie4EF24cOHCpZtOSrT2SWqSdiZNJvOeSZv0J/dWQ6FY4sDh3O+D73zn3LmhxqZmmve2SDQ0NrGnobEGUYt+a1s7Xd2HCYf7OX/yDAO9PZwNH6Ov5zj9vae4fuEaF89dpfvoCULt+/bT0dnFgY5OOdjS2laDqEX/4KEjhPv6GR6OMXojzs2hK0QGBxi8NEB0aJgnt+9xZ+wuvacvE4pGY8TjI8TiI0SiUSKRbYjGZH907Bb3Hzwi8WKCyZcTTCbGeZV4SuL5M96+fsPnD594/+4jDx+PE1IUBUVJ/oGyg6emFJTkNNPJFNNTKb6nZpiZ+cns3ByLi4uk08toqoaq5plfWCLELt/m5iaVahXP8cnNLTP/LcnqUgZNW2N1VUXT8qiqSj6fx7ZtgnKZkBjaDZVKFcdySSs/SH35SmZ2AVXVyGZzZLI5fmWy5HIr6HoJ1/PrEazguT76Sh51KY2+VsB2XCzbwbJsTMuWZ9f18PxgZ+S/QrXIQtAP5LBhmJimJQWEqOO42LaD43oybhCU6xT0fEqGSVEvyWiC5blkSBaL/CAgKK/XJ+j7gXQk3Eg4jnQnFvm+ECqzvrHxf4IipnAiXAkWtYhYrVZrr6FuQeHEMC2KusFaQadQFHFN6Vos84OyZPmX/yW4/dls3aFFQTcoFI0t1sX9CYi7Fc4tDMvmN5qtb/VvEy2oAAAAAElFTkSuQmCC',
                  palette: {
                    _type: 'sanity.imagePalette',
                    darkMuted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#2a3255',
                      foreground: '#fff',
                      population: 0.79,
                      title: '#fff',
                    },
                    darkVibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#191e3a',
                      foreground: '#fff',
                      population: 0.19,
                      title: '#fff',
                    },
                    dominant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#2a3255',
                      foreground: '#fff',
                      population: 0.79,
                      title: '#fff',
                    },
                    lightMuted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#c3b4a1',
                      foreground: '#000',
                      population: 0.48,
                      title: '#fff',
                    },
                    lightVibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#f9fae4',
                      foreground: '#000',
                      population: 0.11,
                      title: '#000',
                    },
                    muted: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#a0845b',
                      foreground: '#fff',
                      population: 0.48,
                      title: '#fff',
                    },
                    vibrant: {
                      _type: 'sanity.imagePaletteSwatch',
                      background: '#38966e',
                      foreground: '#fff',
                      population: 0.01,
                      title: '#fff',
                    },
                  },
                },
                mimeType: 'image/png',
                originalFilename: 'status.png',
                path:
                  'images/3do82whm/herman_test/707c10d8643fdffaee08833b470146e3ecfc5d8d-710x458.png',
                sha1hash: '707c10d8643fdffaee08833b470146e3ecfc5d8d',
                size: 75515,
                uploadId: '9qu3NZ7sSpT0qFqJdaTyKDGDHRxB74Mb',
                url:
                  'https://cdn.sanity.io/images/3do82whm/herman_test/707c10d8643fdffaee08833b470146e3ecfc5d8d-710x458.png',
              },
              caption: 'Login popover improvements',
            },
          ],
          title: 'Updated login status popover',
        },
        {
          _key: '676d73292acc',
          _type: 'changeItem',
          changeType: 'bugfix',
          description: [
            {
              _key: 'e6ac5ed5568f',
              _type: 'block',
              children: [
                {
                  _key: 'f2e7c57132760',
                  _type: 'span',
                  marks: [],
                  text:
                    'Fixes an issue where the empty editor placeholder text would sometimes cause focus problems in Webkit.',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [],
              style: 'normal',
            },
            {
              _key: '05fc8dfe8429',
              _type: 'block',
              children: [
                {
                  _key: '68d67fed79530',
                  _type: 'span',
                  marks: [],
                  text:
                    'Fixes an issue where multiple types in array input would prevent it from being scrollable',
                },
              ],
              level: 1,
              listItem: 'bullet',
              markDefs: [],
              style: 'normal',
            },
          ],
        },
      ],
      version: '2.26.0',
    },
  ],
}
