import {describe, expect, it} from 'vitest'

import {type ReleaseDocument} from '../../../store/types'
import {buildReleaseEditEvents} from './buildReleaseEditEvents'

describe('buildReleaseEditEvents()', () => {
  it('should identify a metadata.releaseType change', () => {
    const release = {
      userId: '',
      _createdAt: '2024-12-05T16:34:59Z',
      _rev: '27IdYXOVe1PEc0ZOADFAhQ',
      name: 'rWBfpXZVj',
      state: 'active',
      _updatedAt: '2024-12-05T17:09:28Z',
      metadata: {
        releaseType: 'undecided',
        description: '',
        title: 'winter drop',
      },
      publishAt: null,
      _id: '_.releases.rWBfpXZVj',
      _type: 'system.release',
      finalDocumentStates: null,
    } as unknown as ReleaseDocument
    const changes = buildReleaseEditEvents(
      [
        {
          id: '27IdYXOVe1PEc0ZOADFAhQ',
          timestamp: '2024-12-05T17:09:28.325641Z',
          author: 'p8xDvUMxC',
          documentIDs: ['_.releases.rWBfpXZVj'],
          effects: {
            '_.releases.rWBfpXZVj': {
              apply: [
                11,
                3,
                23,
                0,
                12,
                22,
                '7:09:28',
                23,
                19,
                20,
                15,
                10,
                5,
                19,
                1,
                17,
                'undecided',
                'releaseType',
                15,
              ],
              revert: [
                11,
                3,
                23,
                0,
                12,
                22,
                '6:35:11',
                23,
                19,
                20,
                15,
                10,
                5,
                17,
                '2024-12-20T16:35:00.000Z',
                'intendedPublishAt',
                17,
                'scheduled',
                'releaseType',
                15,
              ],
            },
          },
        },
      ],
      release,
    )
    expect(changes).toEqual([
      {
        type: 'editRelease',
        author: 'p8xDvUMxC',
        origin: 'translog',
        change: {releaseType: 'undecided', intendedPublishDate: undefined},
        id: '27IdYXOVe1PEc0ZOADFAhQ',
        timestamp: '2024-12-05T17:09:28.325641Z',
        releaseName: 'rWBfpXZVj',
      },
    ])
  })
  it('should identify a intededPublishDate change', () => {
    const release = {
      publishAt: null,
      _rev: 'zGoOhrVQZLzwh7QVfgQryJ',
      _id: '_.releases.rWBfpXZVj',
      _createdAt: '2024-12-05T16:34:59Z',
      userId: '',
      metadata: {
        releaseType: 'scheduled',
        description: '',
        title: 'winter drop',
        intendedPublishAt: '2024-12-13T17:12:00.000Z',
      },
      name: 'rWBfpXZVj',
      state: 'active',
      _updatedAt: '2024-12-05T17:12:56Z',
      _type: 'system.release',
      finalDocumentStates: null,
    } as unknown as ReleaseDocument
    const changes = buildReleaseEditEvents(
      [
        {
          id: 'zGoOhrVQZLzwh7QVfgQryJ',
          timestamp: '2024-12-05T17:12:56.253502Z',
          author: 'p8xDvUMxC',
          documentIDs: ['_.releases.rWBfpXZVj'],
          effects: {
            '_.releases.rWBfpXZVj': {
              apply: [
                11,
                3,
                23,
                0,
                17,
                22,
                '56',
                23,
                19,
                20,
                15,
                10,
                5,
                11,
                1,
                23,
                0,
                9,
                22,
                '3',
                23,
                10,
                24,
                15,
                15,
              ],
              revert: [
                11,
                3,
                23,
                0,
                17,
                22,
                '48',
                23,
                19,
                20,
                15,
                10,
                5,
                11,
                1,
                23,
                0,
                9,
                22,
                '2',
                23,
                10,
                24,
                15,
                15,
              ],
            },
          },
        },
      ],
      release,
    )
    expect(changes).toEqual([
      {
        type: 'editRelease',
        author: 'p8xDvUMxC',
        origin: 'translog',
        change: {intendedPublishDate: '2024-12-13T17:12:00.000Z'},
        id: 'zGoOhrVQZLzwh7QVfgQryJ',
        timestamp: '2024-12-05T17:12:56.253502Z',
        releaseName: 'rWBfpXZVj',
      },
    ])
  })
  it('should identify a metadata.releaseType and intendedPublishDate change', () => {
    const releaseDocument = {
      publishAt: null,
      finalDocumentStates: null,
      _id: '_.releases.rWBfpXZVj',
      state: 'active',
      _updatedAt: '2024-12-05T16:35:11Z',
      metadata: {
        releaseType: 'scheduled',
        description: '',
        title: 'winter drop',
        intendedPublishAt: '2024-12-20T16:35:00.000Z',
      },
      _rev: 'zGoOhrVQZLzwh7QVfgIGWK',
      _type: 'system.release',
      name: 'rWBfpXZVj',
      userId: '',
      _createdAt: '2024-12-05T16:34:59Z',
    } as unknown as ReleaseDocument

    const releaseEditEvents = buildReleaseEditEvents(
      [
        {
          id: 'zGoOhrVQZLzwh7QVfgIGWK',
          timestamp: '2024-12-05T16:35:11.995089Z',
          author: 'p8xDvUMxC',
          documentIDs: ['_.releases.rWBfpXZVj'],
          effects: {
            '_.releases.rWBfpXZVj': {
              apply: [
                11,
                3,
                23,
                0,
                15,
                22,
                '5:11',
                23,
                19,
                20,
                15,
                10,
                5,
                17,
                '2024-12-20T16:35:00.000Z',
                'intendedPublishAt',
                17,
                'scheduled',
                'releaseType',
                15,
              ],
              revert: [10, 0, 14, '_updatedAt', 10, 5, 19, 1, 17, 'asap', 'releaseType', 15],
            },
          },
        },
      ],
      releaseDocument,
    )
    expect(releaseEditEvents).toEqual([
      {
        type: 'editRelease',
        author: 'p8xDvUMxC',
        origin: 'translog',
        change: {
          releaseType: 'scheduled',
          intendedPublishDate: '2024-12-20T16:35:00.000Z',
        },
        id: 'zGoOhrVQZLzwh7QVfgIGWK',
        timestamp: '2024-12-05T16:35:11.995089Z',
        releaseName: 'rWBfpXZVj',
      },
    ])
  })
  it('should handle multiple changes correctly', () => {
    const release = {
      publishAt: null,
      _rev: 'zGoOhrVQZLzwh7QVfgQryJ',
      _id: '_.releases.rWBfpXZVj',
      _createdAt: '2024-12-05T16:34:59Z',
      userId: '',
      metadata: {
        releaseType: 'scheduled',
        description: '',
        title: 'winter drop',
        intendedPublishAt: '2024-12-13T17:12:00.000Z',
      },
      name: 'rWBfpXZVj',
      state: 'active',
      _updatedAt: '2024-12-05T17:12:56Z',
      _type: 'system.release',
      finalDocumentStates: null,
    } as unknown as ReleaseDocument
    const changes = buildReleaseEditEvents(
      [
        {
          id: 'zGoOhrVQZLzwh7QVfgQryJ',
          timestamp: '2024-12-05T17:12:56.253502Z',
          author: 'p8xDvUMxC',
          documentIDs: ['_.releases.rWBfpXZVj'],
          effects: {
            '_.releases.rWBfpXZVj': {
              apply: [
                11,
                3,
                23,
                0,
                17,
                22,
                '56',
                23,
                19,
                20,
                15,
                10,
                5,
                11,
                1,
                23,
                0,
                9,
                22,
                '3',
                23,
                10,
                24,
                15,
                15,
              ],
              revert: [
                11,
                3,
                23,
                0,
                17,
                22,
                '48',
                23,
                19,
                20,
                15,
                10,
                5,
                11,
                1,
                23,
                0,
                9,
                22,
                '2',
                23,
                10,
                24,
                15,
                15,
              ],
            },
          },
        },
        {
          id: '27IdYXOVe1PEc0ZOADFjtK',
          timestamp: '2024-12-05T17:12:48.742846Z',
          author: 'p8xDvUMxC',

          documentIDs: ['_.releases.rWBfpXZVj'],
          effects: {
            '_.releases.rWBfpXZVj': {
              apply: [
                11,
                3,
                23,
                0,
                14,
                22,
                '12:4',
                23,
                18,
                20,
                15,
                10,
                5,
                17,
                '2024-12-12T17:12:00.000Z',
                'intendedPublishAt',
                17,
                'scheduled',
                'releaseType',
                15,
              ],
              revert: [
                11,
                3,
                23,
                0,
                14,
                22,
                '09:2',
                23,
                18,
                20,
                15,
                10,
                5,
                19,
                1,
                17,
                'undecided',
                'releaseType',
                15,
              ],
            },
          },
        },
        {
          id: '27IdYXOVe1PEc0ZOADFAhQ',
          timestamp: '2024-12-05T17:09:28.325641Z',
          author: 'p8xDvUMxC',

          documentIDs: ['_.releases.rWBfpXZVj'],
          effects: {
            '_.releases.rWBfpXZVj': {
              apply: [
                11,
                3,
                23,
                0,
                12,
                22,
                '7:09:28',
                23,
                19,
                20,
                15,
                10,
                5,
                19,
                1,
                17,
                'undecided',
                'releaseType',
                15,
              ],
              revert: [
                11,
                3,
                23,
                0,
                12,
                22,
                '6:35:11',
                23,
                19,
                20,
                15,
                10,
                5,
                17,
                '2024-12-20T16:35:00.000Z',
                'intendedPublishAt',
                17,
                'scheduled',
                'releaseType',
                15,
              ],
            },
          },
        },
        {
          id: 'zGoOhrVQZLzwh7QVfgIGWK',
          timestamp: '2024-12-05T16:35:11.995089Z',
          author: 'p8xDvUMxC',

          documentIDs: ['_.releases.rWBfpXZVj'],
          effects: {
            '_.releases.rWBfpXZVj': {
              apply: [
                11,
                3,
                23,
                0,
                15,
                22,
                '5:11',
                23,
                19,
                20,
                15,
                10,
                5,
                17,
                '2024-12-20T16:35:00.000Z',
                'intendedPublishAt',
                17,
                'scheduled',
                'releaseType',
                15,
              ],
              revert: [10, 0, 14, '_updatedAt', 10, 5, 19, 1, 17, 'asap', 'releaseType', 15],
            },
          },
        },
        {
          id: '27IdYXOVe1PEc0ZOAD1jvY',
          timestamp: '2024-12-05T16:34:59.512774Z',
          author: 'p8xDvUMxC',
          documentIDs: ['_.releases.rWBfpXZVj'],
          effects: {
            '_.releases.rWBfpXZVj': {
              apply: [
                0,
                {
                  _createdAt: '2024-12-05T16:34:59Z',
                  _id: '_.releases.rWBfpXZVj',
                  _type: 'system.release',
                  _updatedAt: '2024-12-05T16:34:59Z',
                  finalDocumentStates: null,
                  metadata: {
                    description: '',
                    releaseType: 'asap',
                    title: 'winter drop',
                  },
                  name: 'rWBfpXZVj',
                  publishAt: null,
                  state: 'active',
                  userId: '',
                },
              ],
              revert: [0, null],
            },
          },
        },
      ],
      release,
    )

    expect(changes).toEqual([
      {
        type: 'editRelease',
        author: 'p8xDvUMxC',
        origin: 'translog',
        change: {intendedPublishDate: '2024-12-13T17:12:00.000Z'},
        id: 'zGoOhrVQZLzwh7QVfgQryJ',
        timestamp: '2024-12-05T17:12:56.253502Z',
        releaseName: 'rWBfpXZVj',
      },
      {
        type: 'editRelease',
        author: 'p8xDvUMxC',
        origin: 'translog',
        change: {releaseType: 'scheduled', intendedPublishDate: '2024-12-12T17:12:00.000Z'},
        id: '27IdYXOVe1PEc0ZOADFjtK',
        timestamp: '2024-12-05T17:12:48.742846Z',
        releaseName: 'rWBfpXZVj',
      },
      {
        type: 'editRelease',
        author: 'p8xDvUMxC',
        origin: 'translog',
        change: {releaseType: 'undecided', intendedPublishDate: undefined},
        id: '27IdYXOVe1PEc0ZOADFAhQ',
        timestamp: '2024-12-05T17:09:28.325641Z',
        releaseName: 'rWBfpXZVj',
      },
      {
        type: 'editRelease',
        author: 'p8xDvUMxC',
        origin: 'translog',
        change: {releaseType: 'scheduled', intendedPublishDate: '2024-12-20T16:35:00.000Z'},
        id: 'zGoOhrVQZLzwh7QVfgIGWK',
        timestamp: '2024-12-05T16:35:11.995089Z',
        releaseName: 'rWBfpXZVj',
      },
      {
        type: 'createRelease',
        author: 'p8xDvUMxC',
        origin: 'translog',
        change: {releaseType: 'asap'},
        id: '27IdYXOVe1PEc0ZOAD1jvY',
        timestamp: '2024-12-05T16:34:59.512774Z',
        releaseName: 'rWBfpXZVj',
      },
    ])
  })
  it('should identify state changes', () => {
    const transactions = [
      {
        id: 'ad56vrBQ94RnZtJ3uXY2W4',
        timestamp: '2025-02-17T15:50:22.301295Z',
        author: 'p8xDvUMxC',
        mutations: [
          {
            createOrReplace: {
              _id: '_.releases.rY3Ko1I4q',
            },
          },
        ],
        documentIDs: ['_.releases.rY3Ko1I4q'],
        effects: {
          '_.releases.rY3Ko1I4q': {
            apply: [
              19,
              9,
              11,
              3,
              23,
              0,
              18,
              22,
              '2',
              23,
              19,
              20,
              15,
              17,
              [
                {
                  id: 'versions.rY3Ko1I4q.f8dece19-c458-4cff-bf76-732b00617183',
                },
              ],
              'finalDocumentStates',
              17,
              '2025-02-17T15:50:22.318027688Z',
              'publishedAt',
              11,
              7,
              23,
              0,
              7,
              22,
              'ed',
              15,
            ],
            revert: [
              19,
              4,
              19,
              8,
              11,
              3,
              23,
              0,
              18,
              22,
              '1',
              23,
              19,
              20,
              15,
              11,
              9,
              23,
              0,
              7,
              22,
              'ing',
              15,
              17,
              'release-rY3Ko1I4q-HjgIO3PPq5URB0RPr1deq1',
              'workflowId',
            ],
          },
        },
      },
      {
        id: 'ad56vrBQ94RnZtJ3uXY2T4',
        timestamp: '2025-02-17T15:50:21.242977Z',
        author: 'p8xDvUMxC',
        mutations: [
          {
            createOrReplace: {
              _id: '_.releases.rY3Ko1I4q',
            },
          },
        ],
        documentIDs: ['_.releases.rY3Ko1I4q'],
        effects: {
          '_.releases.rY3Ko1I4q': {
            apply: [11, 3, 23, 0, 17, 22, '21', 23, 19, 20, 15, 17, 'publishing', 'state'],
            revert: [11, 3, 23, 0, 17, 22, '19', 23, 19, 20, 15, 17, 'scheduled', 'state'],
          },
        },
      },
      {
        id: 'ad56vrBQ94RnZtJ3uXY2Q4',
        timestamp: '2025-02-17T15:50:19.843869Z',
        author: 'p8xDvUMxC',
        mutations: [
          {
            createOrReplace: {
              _id: '_.releases.rY3Ko1I4q',
            },
          },
        ],
        documentIDs: ['_.releases.rY3Ko1I4q'],
        effects: {
          '_.releases.rY3Ko1I4q': {
            apply: [11, 7, 23, 0, 7, 22, 'ed', 15],
            revert: [11, 7, 23, 0, 7, 22, 'ing', 15],
          },
        },
      },
      {
        id: 'HjgIO3PPq5URB0RPr1demX',
        timestamp: '2025-02-17T15:50:19.684661Z',
        author: 'p8xDvUMxC',
        mutations: [
          {
            createOrReplace: {
              _id: '_.releases.rY3Ko1I4q',
            },
          },
        ],
        documentIDs: ['_.releases.rY3Ko1I4q'],
        effects: {
          '_.releases.rY3Ko1I4q': {
            apply: [
              11,
              3,
              23,
              0,
              14,
              22,
              '50:19',
              23,
              19,
              20,
              15,
              17,
              '2025-02-17T15:50:19.692089333Z',
              'publishAt',
              17,
              'scheduling',
              'state',
              17,
              'release-rY3Ko1I4q-HjgIO3PPq5URB0RPr1deq1',
              'workflowId',
            ],
            revert: [
              19,
              6,
              19,
              9,
              11,
              3,
              23,
              0,
              14,
              22,
              '49:47',
              23,
              19,
              20,
              15,
              17,
              'active',
              'state',
            ],
          },
        },
      },
      {
        id: 'HjgIO3PPq5URB0RPr1cN6P',
        timestamp: '2025-02-17T15:49:47.189728Z',
        author: 'p8xDvUMxC',
        mutations: [
          {
            patch: {
              id: '_.releases.rY3Ko1I4q',
              unsetIsEmpty: false,
            },
          },
        ],
        documentIDs: ['_.releases.rY3Ko1I4q'],
        effects: {
          '_.releases.rY3Ko1I4q': {
            apply: [
              11,
              3,
              23,
              0,
              15,
              22,
              '9:4',
              23,
              18,
              20,
              15,
              10,
              4,
              11,
              2,
              23,
              0,
              6,
              22,
              'publish',
              23,
              12,
              14,
              15,
              15,
            ],
            revert: [
              11,
              3,
              23,
              0,
              15,
              22,
              '8:3',
              23,
              18,
              20,
              15,
              10,
              4,
              11,
              2,
              23,
              0,
              6,
              22,
              'archiv',
              23,
              13,
              15,
              15,
              15,
            ],
          },
        },
      },
      {
        id: 'ad56vrBQ94RnZtJ3uXY2N4',
        timestamp: '2025-02-17T15:48:37.430863Z',
        author: 'p8xDvUMxC',
        mutations: [
          {
            createOrReplace: {
              _id: '_.releases.rY3Ko1I4q',
            },
          },
        ],
        documentIDs: ['_.releases.rY3Ko1I4q'],
        effects: {
          '_.releases.rY3Ko1I4q': {
            apply: [19, 8, 17, 'active', 'state'],
            revert: [
              17,
              'unarchiving',
              'state',
              17,
              'release-rY3Ko1I4q-HjgIO3PPq5URB0RPr1aAHB',
              'workflowId',
            ],
          },
        },
      },
      {
        id: 'HjgIO3PPq5URB0RPr1aADh',
        timestamp: '2025-02-17T15:48:37.238598Z',
        author: 'p8xDvUMxC',
        mutations: [
          {
            createOrReplace: {
              _id: '_.releases.rY3Ko1I4q',
            },
          },
        ],
        documentIDs: ['_.releases.rY3Ko1I4q'],
        effects: {
          '_.releases.rY3Ko1I4q': {
            apply: [
              11,
              3,
              23,
              0,
              14,
              22,
              '48:37',
              23,
              19,
              20,
              15,
              17,
              'unarchiving',
              'state',
              17,
              'release-rY3Ko1I4q-HjgIO3PPq5URB0RPr1aAHB',
              'workflowId',
            ],
            revert: [19, 8, 11, 3, 23, 0, 14, 22, '37:41', 23, 19, 20, 15, 17, 'archived', 'state'],
          },
        },
      },
      {
        id: 'ad56vrBQ94RnZtJ3uXY2K4',
        timestamp: '2025-02-17T15:37:41.591300Z',
        author: 'p8xDvUMxC',
        mutations: [
          {
            createOrReplace: {
              _id: '_.releases.rY3Ko1I4q',
            },
          },
        ],
        documentIDs: ['_.releases.rY3Ko1I4q'],
        effects: {
          '_.releases.rY3Ko1I4q': {
            apply: [19, 8, 11, 6, 23, 0, 6, 22, 'ed', 15],
            revert: [
              11,
              6,
              23,
              0,
              6,
              22,
              'ing',
              15,
              17,
              'release-rY3Ko1I4q-HjgIO3PPq5URB0RPr1RwqP',
              'workflowId',
            ],
          },
        },
      },
      {
        id: 'HjgIO3PPq5URB0RPr1Rwmv',
        timestamp: '2025-02-17T15:37:41.186908Z',
        author: 'p8xDvUMxC',
        mutations: [
          {
            createOrReplace: {
              _id: '_.releases.rY3Ko1I4q',
            },
          },
        ],
        documentIDs: ['_.releases.rY3Ko1I4q'],
        effects: {
          '_.releases.rY3Ko1I4q': {
            apply: [
              11,
              3,
              23,
              0,
              17,
              22,
              '41',
              23,
              19,
              20,
              15,
              17,
              'archiving',
              'state',
              17,
              'p8xDvUMxC',
              'userId',
              17,
              'release-rY3Ko1I4q-HjgIO3PPq5URB0RPr1RwqP',
              'workflowId',
            ],
            revert: [19, 7, 19, 8, 10, 0, 14, '_updatedAt', 17, 'active', 'state'],
          },
        },
      },
      {
        id: 'g9WA6RAm4T2Bl8zZYz08dP',
        timestamp: '2025-02-17T15:37:30.977183Z',
        author: 'p8xDvUMxC',
        mutations: [
          {
            createOrReplace: {
              _id: '_.releases.rY3Ko1I4q',
            },
          },
        ],
        documentIDs: ['_.releases.rY3Ko1I4q'],
        effects: {
          '_.releases.rY3Ko1I4q': {
            apply: [
              0,
              {
                _createdAt: '2025-02-17T15:37:30Z',
                _id: '_.releases.rY3Ko1I4q',
                _type: 'system.release',
                _updatedAt: '2025-02-17T15:37:30Z',
                metadata: {
                  description: '',
                  releaseType: 'asap',
                  title: 'To be archived',
                },
                name: 'rY3Ko1I4q',
                state: 'active',
              },
            ],
            revert: [0, null],
          },
        },
      },
    ]
    const release: ReleaseDocument = {
      _type: 'system.release',
      _id: '_.releases.rY3Ko1I4q',
      state: 'published',
      metadata: {
        releaseType: 'asap',
        description: '',
        title: 'To be published',
      },
      _createdAt: '2025-02-17T15:37:30Z',
      name: 'rY3Ko1I4q',
      _updatedAt: '2025-02-17T15:50:22Z',
      userId: 'p8xDvUMxC',
      publishAt: '2025-02-17T15:50:19.692089333Z',
      finalDocumentStates: [
        {
          id: 'versions.rY3Ko1I4q.f8dece19-c458-4cff-bf76-732b00617183',
        },
      ],
      publishedAt: '2025-02-17T15:50:22.318027688Z',
      _rev: 'ad56vrBQ94RnZtJ3uXY2W4',
    }
    const changes = buildReleaseEditEvents(transactions, release)

    expect(changes).toEqual([
      {
        type: 'publishRelease',
        timestamp: '2025-02-17T15:50:22.301295Z',
        author: 'p8xDvUMxC',
        releaseName: 'rY3Ko1I4q',
        id: 'ad56vrBQ94RnZtJ3uXY2W4',
        origin: 'translog',
      },
      {
        type: 'unarchiveRelease',
        timestamp: '2025-02-17T15:48:37.430863Z',
        author: 'p8xDvUMxC',
        releaseName: 'rY3Ko1I4q',
        id: 'ad56vrBQ94RnZtJ3uXY2N4',
        origin: 'translog',
      },
      {
        type: 'archiveRelease',
        timestamp: '2025-02-17T15:37:41.591300Z',
        author: 'p8xDvUMxC',
        releaseName: 'rY3Ko1I4q',
        id: 'ad56vrBQ94RnZtJ3uXY2K4',
        origin: 'translog',
      },
      {
        type: 'createRelease',
        origin: 'translog',
        author: 'p8xDvUMxC',
        change: {releaseType: 'asap'},
        id: 'g9WA6RAm4T2Bl8zZYz08dP',
        timestamp: '2025-02-17T15:37:30.977183Z',
        releaseName: 'rY3Ko1I4q',
      },
    ])
  })
})
