/**
 * Curated taxonomy for the `@sanity/icons` gallery (Foundations/Design System Tooling →
 * Icon pipeline). The package ships no official grouping, so this map is editorial —
 * buckets chosen for scanability, every symbol assigned exactly once. Symbols missing
 * from every bucket (e.g. icons added upstream after this curation) fall into the
 * runtime `uncategorized` catch-all, so new icons never vanish from the gallery.
 */

export interface IconCategory {
  id: string
  title: string
  symbols: string[]
}

export const ICON_CATEGORIES: IconCategory[] = [
  {
    id: 'arrows',
    title: 'Arrows & Navigation',
    symbols: [
      'arrow-down',
      'arrow-left',
      'arrow-right',
      'arrow-top-right',
      'arrow-up',
      'chevron-down',
      'chevron-left',
      'chevron-right',
      'chevron-up',
      'double-chevron-down',
      'double-chevron-left',
      'double-chevron-right',
      'double-chevron-up',
      'toggle-arrow-right',
      'enter',
      'enter-right',
      'leave',
      'launch',
      'expand',
      'collapse',
      'home',
      'menu',
      'master-detail',
      'panel-left',
      'panel-right',
    ],
  },
  {
    id: 'documents',
    title: 'Documents & Content',
    symbols: [
      'document',
      'documents',
      'add-document',
      'binary-document',
      'document-pdf',
      'document-remove',
      'document-sheet',
      'document-text',
      'document-video',
      'document-word',
      'document-zip',
      'folder',
      'archive',
      'unarchive',
      'inbox',
      'book',
      'bookmark',
      'bookmark-filled',
      'clipboard',
      'clipboard-image',
      'stack',
      'stack-compact',
      'versions',
      'timeline',
      'package',
      'projects',
      'dashboard',
    ],
  },
  {
    id: 'editor',
    title: 'Text & Editor',
    symbols: [
      'bold',
      'italic',
      'underline',
      'strikethrough',
      'highlight',
      'text',
      'blockquote',
      'double-quote',
      'block-content',
      'block-element',
      'inline',
      'inline-element',
      'code-block',
      'list',
      'olist',
      'ulist',
      'th-large',
      'th-list',
      'insert-above',
      'insert-below',
      'drag-handle',
      'split-horizontal',
      'split-vertical',
      'translate',
      'truncate',
      'compose',
      'compose-sparkles',
    ],
  },
  {
    id: 'people',
    title: 'Users & Collaboration',
    symbols: [
      'user',
      'users',
      'add-user',
      'face-happy',
      'face-indifferent',
      'face-sad',
      'comment',
      'add-comment',
      'feedback',
      'thumbs-up',
      'thumbs-down',
      'ok-hand',
      'share',
      'envelope',
      'task',
    ],
  },
  {
    id: 'actions',
    title: 'Actions',
    symbols: [
      'add',
      'add-circle',
      'remove',
      'remove-circle',
      'close',
      'close-circle',
      'edit',
      'trash',
      'copy',
      'publish',
      'unpublish',
      'undo',
      'redo',
      'refresh',
      'sync',
      'reset',
      'restore',
      'retry',
      'revert',
      'download',
      'upload',
      'search',
      'filter',
      'sort',
      'select',
      'link',
      'unlink',
      'link-removed',
      'pin',
      'pin-filled',
      'pin-removed',
      'generate',
      'transfer',
      'retrieve',
      'cog',
      'controls',
      'wrench',
    ],
  },
  {
    id: 'media',
    title: 'Media & Assets',
    symbols: [
      'image',
      'images',
      'image-remove',
      'video',
      'play',
      'pause',
      'stop',
      'microphone',
      'microphone-slash',
      'crop',
      'color-wheel',
      'drop',
      'presentation',
    ],
  },
  {
    id: 'status',
    title: 'Status & Feedback',
    symbols: [
      'checkmark',
      'checkmark-circle',
      'error-filled',
      'error-outline',
      'error-screen',
      'warning-filled',
      'warning-outline',
      'info-filled',
      'info-outline',
      'help-circle',
      'spinner',
      'progress-50',
      'progress-75',
      'bell',
      'activity',
      'access-denied',
      'read-only',
      'lock',
      'unlock',
      'eye-open',
      'eye-closed',
      'empty',
      'unknown',
      'dot',
      'asterisk',
      'overage',
    ],
  },
  {
    id: 'commerce',
    title: 'Commerce',
    symbols: ['basket', 'bill', 'credit-card', 'trolley', 'tag', 'tags', 'case', 'tiers'],
  },
  {
    id: 'dev',
    title: 'Developer & Data',
    symbols: [
      'api',
      'code',
      'terminal',
      'json',
      'groq',
      'schema',
      'database',
      'string',
      'number',
      'hash',
      'token',
      'cube',
      'component',
      'plug',
      'bug',
      'logo-js',
      'logo-ts',
      'github',
      'twitter',
      'linkedin',
      'robot',
    ],
  },
  {
    id: 'objects',
    title: 'Objects & Misc',
    symbols: [
      'calendar',
      'clock',
      'sun',
      'moon',
      'star',
      'star-filled',
      'heart',
      'heart-filled',
      'bulb-outline',
      'bulb-filled',
      'bolt',
      'sparkle',
      'sparkles',
      'confetti',
      'rocket',
      'target',
      'marker',
      'marker-removed',
      'earth-globe',
      'earth-americas',
      'desktop',
      'mobile-device',
      'tablet-device',
      'joystick',
      'ice-cream',
      'lemon',
      'bottle',
      'circle',
      'square',
      'diamond',
      'triangle-outline',
      'equal',
      'ellipsis-horizontal',
      'ellipsis-vertical',
      'bar-chart',
      'chart-upward',
      'trend-upward',
    ],
  },
]

/** Title for symbols in no bucket — the safety net for icons added upstream later. */
export const UNCATEGORIZED_TITLE = 'Uncategorized'

/**
 * Split the live icon map against the curated buckets: ordered categories that
 * actually have members, plus the catch-all for anything the curation predates.
 */
export function categorizeIcons(allSymbols: string[]): Array<{
  id: string
  title: string
  symbols: string[]
}> {
  const known = new Set(ICON_CATEGORIES.flatMap((category) => category.symbols))
  const present = new Set(allSymbols)
  const result = ICON_CATEGORIES.map((category) => ({
    ...category,
    symbols: category.symbols.filter((symbol) => present.has(symbol)),
  })).filter((category) => category.symbols.length > 0)
  const uncategorized = allSymbols.filter((symbol) => !known.has(symbol)).sort()
  if (uncategorized.length > 0) {
    result.push({id: 'uncategorized', title: UNCATEGORIZED_TITLE, symbols: uncategorized})
  }
  return result
}
