export {deskTool} from '../desk'

export type {
  DefaultDocumentNodeResolver,
  DeskToolOptions,
  StructureBuilder,
  StructureResolver,
} from '../desk'

export type {
  ActionComponent,
  DocumentActionComponent,
  DocumentActionConfirmModalProps,
  DocumentActionDescription,
  DocumentActionModalProps,
  DocumentActionDialogModalProps,
  DocumentActionPopoverModalProps,
  DocumentActionProps,
  DocumentActionResolver,
} from '../desk/actions'

export type {
  DocumentBadgeComponent,
  DocumentBadgeProps,
  DocumentBadgeDescription,
} from '../desk/badges'

export {
  DeleteAction,
  PublishAction,
  DuplicateAction,
  UnpublishAction,
  DiscardChangesAction,
  HistoryRestoreAction,
} from '../desk/actions'

export {
  ComponentBuilder,
  ComponentViewBuilder,
  DocumentBuilder,
  DocumentListBuilder,
  DocumentListItemBuilder,
  DocumentTypeListBuilder,
  FormViewBuilder,
  GenericListBuilder,
  GenericViewBuilder,
  InitialValueTemplateItemBuilder,
  ListBuilder,
  ListItemBuilder,
  MenuItemBuilder,
  MenuItemGroupBuilder,
} from '../desk/structureBuilder'

export type {
  BaseGenericList,
  BaseIntentParams,
  BuildableComponent,
  BuildableGenericList,
  BuildableList,
  Child,
  ChildObservable,
  ChildResolver,
  ChildResolverOptions,
  Collection,
  CollectionBuilder,
  Component,
  ComponentInput,
  ComponentView,
  Divider,
  DocumentList,
  DocumentListInput,
  DocumentListItem,
  DocumentListItemInput,
  DocumentListOptions,
  DocumentNode,
  DocumentOptions,
  DocumentTypeListInput,
  EditorNode,
  FormView,
  GenericList,
  GenericListInput,
  Intent,
  IntentChecker,
  IntentJsonParams,
  IntentParams,
  ItemChild,
  List,
  ListDisplayOptions,
  ListInput,
  ListItem,
  ListItemChild,
  ListItemDisplayOptions,
  ListItemInput,
  ListItemSerializeOptions,
  MenuItem,
  MenuItemActionType,
  MenuItemGroup,
  MenuItemParamsType,
  PartialDocumentList,
  PartialDocumentListItem,
  PartialDocumentNode,
  PartialListItem,
  PartialMenuItem,
  Serializable,
  SerializeOptions,
  SerializePath,
  StructureContext,
  StructureNode,
  UnserializedListItem,
  UnserializedListItemChild,
  UserComponent,
  View,
  ViewBuilder,
} from '../desk/structureBuilder'
