#!/usr/bin/env node

const path = require('path')

require('esbuild-register/dist/node').register({
  target: `node${process.version.slice(1)}`,
})

// Define the global `__DEV__` flag which is used to
// - determine when to use `esbuild-register` in the Sanity development server
// - determine when to use `esbuild-register` in the Sanity CLI
// - exclude development-only code from the production build
global.__DEV__ = true

require('../../packages/@sanity/cli/src/run')
