// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import {describe, expectTypeOf, test} from 'vitest'
import type {
  DEFAULT_DATE_FORMAT,
  DEFAULT_TIME_FORMAT,
  format,
  isValidTimeZoneString,
  parse,
  ParseResult,
  sanitizeLocale,
} from '@sanity/util/legacyDateFormat'

describe('@sanity/util/legacyDateFormat', () => {
  test('DEFAULT_DATE_FORMAT', () => {
    expectTypeOf<typeof DEFAULT_DATE_FORMAT>().not.toBeNever()
  })
  test('DEFAULT_TIME_FORMAT', () => {
    expectTypeOf<typeof DEFAULT_TIME_FORMAT>().not.toBeNever()
  })
  test('format', () => {
    expectTypeOf<typeof format>().toBeFunction()
  })
  test('isValidTimeZoneString', () => {
    expectTypeOf<typeof isValidTimeZoneString>().toBeFunction()
  })
  test('parse', () => {
    expectTypeOf<typeof parse>().toBeFunction()
  })
  test('ParseResult', () => {
    expectTypeOf<ParseResult>().not.toBeNever()
  })
  test('sanitizeLocale', () => {
    expectTypeOf<typeof sanitizeLocale>().not.toBeNever()
  })
})
