// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import {describe, expectTypeOf, test} from 'vitest'
import type {createClientConcurrencyLimiter} from '@sanity/util/client'

describe('@sanity/util/client', () => {
  test('createClientConcurrencyLimiter', () => {
    expectTypeOf<typeof createClientConcurrencyLimiter>().toBeFunction()
  })
})
