// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
import {describe, expectTypeOf, test} from 'vitest'
import type {VisionLocaleResourceKeys, visionTool, VisionToolConfig} from '@sanity/vision'

describe('@sanity/vision', () => {
  test('VisionLocaleResourceKeys', () => {
    expectTypeOf<VisionLocaleResourceKeys>().not.toBeNever()
  })
  test('visionTool', () => {
    expectTypeOf<typeof visionTool>().not.toBeNever()
  })
  test('VisionToolConfig', () => {
    expectTypeOf<VisionToolConfig>().toBeObject()
  })
})
