// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
import {describe, expectTypeOf, test} from 'vitest'
import type {default as _default, Schema, SchemaValidationResult} from '@sanity/schema'

describe('@sanity/schema', () => {
  test('default', () => {
    expectTypeOf<_default>().not.toBeNever()
  })
  test('Schema', () => {
    expectTypeOf<typeof Schema>().not.toBeNever()
  })
  test('SchemaValidationResult', () => {
    expectTypeOf<SchemaValidationResult>().toBeObject()
  })
})
