// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import type {
  experimental_vistaTool,
  VisionLocaleResourceKeys,
  visionTool,
  VisionToolConfig,
  VistaToolConfig,
} from '@sanity/vision'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/vision', () => {
  test('experimental_vistaTool', () => {
    expectTypeOf<typeof experimental_vistaTool>().not.toBeNever()
  })
  test('VisionLocaleResourceKeys', () => {
    expectTypeOf<VisionLocaleResourceKeys>().not.toBeNever()
  })
  test('visionTool', () => {
    expectTypeOf<typeof visionTool>().not.toBeNever()
  })
  test('VisionToolConfig', () => {
    expectTypeOf<VisionToolConfig>().toBeObject()
  })
  test('VistaToolConfig', () => {
    expectTypeOf<VistaToolConfig>().not.toBeNever()
  })
})
