// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import {describe, expectTypeOf, test} from 'vitest'
import type {
  ALL_FIELDS_GROUP_NAME,
  builtinTypes,
  createSchemaFromManifestTypes,
  DEFAULT_MAX_FIELD_DEPTH,
  DescriptorConverter,
  extractSchema,
  FIXME,
  groupProblems,
  isActionEnabled,
  Problem,
  ProblemPath,
  ProblemPathPropertySegment,
  ProblemPathSegment,
  ProblemPathTypeSegment,
  processSchemaSynchronization,
  resolveSearchConfig,
  resolveSearchConfigForBaseFieldPaths,
  SchemaSynchronizationRequest,
  SchemaSynchronizationResult,
  TypeWithProblems,
  validateMediaLibraryAssetAspect,
  validateSchema,
  ValidationError,
  ValidationResult,
} from '@sanity/schema/_internal'

describe('@sanity/schema/_internal', () => {
  test('ALL_FIELDS_GROUP_NAME', () => {
    expectTypeOf<typeof ALL_FIELDS_GROUP_NAME>().not.toBeNever()
  })
  test('builtinTypes', () => {
    expectTypeOf<typeof builtinTypes>().not.toBeNever()
  })
  test('createSchemaFromManifestTypes', () => {
    expectTypeOf<typeof createSchemaFromManifestTypes>().toBeFunction()
  })
  test('DEFAULT_MAX_FIELD_DEPTH', () => {
    expectTypeOf<typeof DEFAULT_MAX_FIELD_DEPTH>().not.toBeNever()
  })
  test('DescriptorConverter', () => {
    expectTypeOf<DescriptorConverter>().not.toBeNever()
  })
  test('extractSchema', () => {
    expectTypeOf<typeof extractSchema>().toBeFunction()
  })
  test('FIXME', () => {
    expectTypeOf<FIXME>().not.toBeNever()
  })
  test('groupProblems', () => {
    expectTypeOf<typeof groupProblems>().toBeFunction()
  })
  test('isActionEnabled', () => {
    expectTypeOf<typeof isActionEnabled>().not.toBeNever()
  })
  test('Problem', () => {
    expectTypeOf<Problem>().toBeObject()
  })
  test('ProblemPath', () => {
    expectTypeOf<ProblemPath>().not.toBeNever()
  })
  test('ProblemPathPropertySegment', () => {
    expectTypeOf<ProblemPathPropertySegment>().toBeObject()
  })
  test('ProblemPathSegment', () => {
    expectTypeOf<ProblemPathSegment>().not.toBeNever()
  })
  test('ProblemPathTypeSegment', () => {
    expectTypeOf<ProblemPathTypeSegment>().toBeObject()
  })
  test('processSchemaSynchronization', () => {
    expectTypeOf<typeof processSchemaSynchronization>().toBeFunction()
  })
  test('resolveSearchConfig', () => {
    expectTypeOf<typeof resolveSearchConfig>().toBeFunction()
  })
  test('resolveSearchConfigForBaseFieldPaths', () => {
    expectTypeOf<typeof resolveSearchConfigForBaseFieldPaths>().toBeFunction()
  })
  test('SchemaSynchronizationRequest', () => {
    expectTypeOf<SchemaSynchronizationRequest>().not.toBeNever()
  })
  test('SchemaSynchronizationResult', () => {
    expectTypeOf<SchemaSynchronizationResult>().not.toBeNever()
  })
  test('TypeWithProblems', () => {
    expectTypeOf<TypeWithProblems>().toBeObject()
  })
  test('validateMediaLibraryAssetAspect', () => {
    expectTypeOf<typeof validateMediaLibraryAssetAspect>().toBeFunction()
  })
  test('validateSchema', () => {
    expectTypeOf<typeof validateSchema>().toBeFunction()
  })
  test('ValidationError', () => {
    expectTypeOf<ValidationError>().not.toBeNever()
  })
  test('ValidationResult', () => {
    expectTypeOf<ValidationResult>().toBeObject()
  })
})
