// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import type {
  ALL_FIELDS_GROUP_NAME,
  builtinTypes,
  CreateManifest,
  createSchemaFromManifestTypes,
  createStoredWorkspaceSchemaPayload,
  CreateWorkspaceManifest,
  DEFAULT_MAX_FIELD_DEPTH,
  DefaultWorkspaceSchemaId,
  DescriptorConverter,
  extractCreateWorkspaceManifest,
  extractManifestSchemaTypes,
  extractSchema,
  FIXME,
  getWorkspaceSchemaId,
  groupProblems,
  IconResolver,
  isActionEnabled,
  ManifestSchemaType,
  ManifestWorkspaceFile,
  ParsedWorkspaceSchemaId,
  parseWorkspaceSchemaId,
  Problem,
  ProblemPath,
  ProblemPathPropertySegment,
  ProblemPathSegment,
  ProblemPathTypeSegment,
  processSchemaSynchronization,
  resolveSearchConfig,
  resolveSearchConfigForBaseFieldPaths,
  SchemaSynchronizationRequest,
  SchemaSynchronizationResult,
  StoredWorkspaceSchema,
  TypeWithProblems,
  validateMediaLibraryAssetAspect,
  validateSchema,
  ValidationError,
  ValidationResult,
  validForNamesChars,
  validForNamesPattern,
  WorkspaceSchemaId,
} from '@sanity/schema/_internal'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/schema/_internal', () => {
  test('ALL_FIELDS_GROUP_NAME', () => {
    expectTypeOf<typeof ALL_FIELDS_GROUP_NAME>().not.toBeNever()
  })
  test('builtinTypes', () => {
    expectTypeOf<typeof builtinTypes>().not.toBeNever()
  })
  test('CreateManifest', () => {
    expectTypeOf<CreateManifest>().toBeObject()
  })
  test('createSchemaFromManifestTypes', () => {
    expectTypeOf<typeof createSchemaFromManifestTypes>().toBeFunction()
  })
  test('createStoredWorkspaceSchemaPayload', () => {
    expectTypeOf<typeof createStoredWorkspaceSchemaPayload>().toBeFunction()
  })
  test('CreateWorkspaceManifest', () => {
    expectTypeOf<CreateWorkspaceManifest>().toBeObject()
  })
  test('DEFAULT_MAX_FIELD_DEPTH', () => {
    expectTypeOf<typeof DEFAULT_MAX_FIELD_DEPTH>().not.toBeNever()
  })
  test('DefaultWorkspaceSchemaId', () => {
    expectTypeOf<DefaultWorkspaceSchemaId>().not.toBeNever()
  })
  test('DescriptorConverter', () => {
    expectTypeOf<DescriptorConverter>().not.toBeNever()
  })
  test('extractCreateWorkspaceManifest', () => {
    expectTypeOf<typeof extractCreateWorkspaceManifest>().toBeFunction()
  })
  test('extractManifestSchemaTypes', () => {
    expectTypeOf<typeof extractManifestSchemaTypes>().toBeFunction()
  })
  test('extractSchema', () => {
    expectTypeOf<typeof extractSchema>().toBeFunction()
  })
  test('FIXME', () => {
    expectTypeOf<FIXME>().not.toBeNever()
  })
  test('getWorkspaceSchemaId', () => {
    expectTypeOf<typeof getWorkspaceSchemaId>().toBeFunction()
  })
  test('groupProblems', () => {
    expectTypeOf<typeof groupProblems>().toBeFunction()
  })
  test('IconResolver', () => {
    expectTypeOf<IconResolver>().not.toBeNever()
  })
  test('isActionEnabled', () => {
    expectTypeOf<typeof isActionEnabled>().not.toBeNever()
  })
  test('ManifestSchemaType', () => {
    expectTypeOf<ManifestSchemaType>().toBeObject()
  })
  test('ManifestWorkspaceFile', () => {
    expectTypeOf<ManifestWorkspaceFile>().toBeObject()
  })
  test('ParsedWorkspaceSchemaId', () => {
    expectTypeOf<ParsedWorkspaceSchemaId>().toBeObject()
  })
  test('parseWorkspaceSchemaId', () => {
    expectTypeOf<typeof parseWorkspaceSchemaId>().toBeFunction()
  })
  test('Problem', () => {
    expectTypeOf<Problem>().toBeObject()
  })
  test('ProblemPath', () => {
    expectTypeOf<ProblemPath>().not.toBeNever()
  })
  test('ProblemPathPropertySegment', () => {
    expectTypeOf<ProblemPathPropertySegment>().toBeObject()
  })
  test('ProblemPathSegment', () => {
    expectTypeOf<ProblemPathSegment>().not.toBeNever()
  })
  test('ProblemPathTypeSegment', () => {
    expectTypeOf<ProblemPathTypeSegment>().toBeObject()
  })
  test('processSchemaSynchronization', () => {
    expectTypeOf<typeof processSchemaSynchronization>().toBeFunction()
  })
  test('resolveSearchConfig', () => {
    expectTypeOf<typeof resolveSearchConfig>().toBeFunction()
  })
  test('resolveSearchConfigForBaseFieldPaths', () => {
    expectTypeOf<typeof resolveSearchConfigForBaseFieldPaths>().toBeFunction()
  })
  test('SchemaSynchronizationRequest', () => {
    expectTypeOf<SchemaSynchronizationRequest>().not.toBeNever()
  })
  test('SchemaSynchronizationResult', () => {
    expectTypeOf<SchemaSynchronizationResult>().not.toBeNever()
  })
  test('StoredWorkspaceSchema', () => {
    expectTypeOf<StoredWorkspaceSchema>().toBeObject()
  })
  test('TypeWithProblems', () => {
    expectTypeOf<TypeWithProblems>().toBeObject()
  })
  test('validateMediaLibraryAssetAspect', () => {
    expectTypeOf<typeof validateMediaLibraryAssetAspect>().toBeFunction()
  })
  test('validateSchema', () => {
    expectTypeOf<typeof validateSchema>().toBeFunction()
  })
  test('ValidationError', () => {
    expectTypeOf<ValidationError>().not.toBeNever()
  })
  test('ValidationResult', () => {
    expectTypeOf<ValidationResult>().toBeObject()
  })
  test('validForNamesChars', () => {
    expectTypeOf<typeof validForNamesChars>().not.toBeNever()
  })
  test('validForNamesPattern', () => {
    expectTypeOf<typeof validForNamesPattern>().not.toBeNever()
  })
  test('WorkspaceSchemaId', () => {
    expectTypeOf<WorkspaceSchemaId>().not.toBeNever()
  })
})
