// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import type {
  convertToValidationMarker,
  evaluateDocumentInternal,
  evaluateDocumentObservable,
  getFallbackLocaleSource,
  getTypeChain,
  hasValidationContext,
  inferFromSchema,
  inferFromSchemaType,
  LocaleSource,
  normalizeValidationRules,
  pathToString,
  resolveTypeForArrayItem,
  Rule,
  typeString,
  validateDocumentInternal,
  ValidateDocumentInternalOptions,
  validateDocumentObservable,
  ValidateDocumentObservableOptions,
  validateItem,
  ValidateItemOptions,
  ValidationContext,
  validationLocaleStrings,
} from '@sanity/validation/_internal'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/validation/_internal', () => {
  test('convertToValidationMarker', () => {
    expectTypeOf<typeof convertToValidationMarker>().toBeFunction()
  })
  test('evaluateDocumentInternal', () => {
    expectTypeOf<typeof evaluateDocumentInternal>().toBeFunction()
  })
  test('evaluateDocumentObservable', () => {
    expectTypeOf<typeof evaluateDocumentObservable>().toBeFunction()
  })
  test('getFallbackLocaleSource', () => {
    expectTypeOf<typeof getFallbackLocaleSource>().toBeFunction()
  })
  test('getTypeChain', () => {
    expectTypeOf<typeof getTypeChain>().toBeFunction()
  })
  test('hasValidationContext', () => {
    expectTypeOf<typeof hasValidationContext>().toBeFunction()
  })
  test('inferFromSchema', () => {
    expectTypeOf<typeof inferFromSchema>().toBeFunction()
  })
  test('inferFromSchemaType', () => {
    // This export has 2 declarations, run `TEST_DTS_EXPORTS_DIAGNOSTICS=duplicates pnpm generate:dts-exports` to see where each declaration is coming from
    expectTypeOf<typeof inferFromSchemaType>().toBeFunction()
  })
  test('LocaleSource', () => {
    expectTypeOf<LocaleSource>().toBeObject()
  })
  test('normalizeValidationRules', () => {
    expectTypeOf<typeof normalizeValidationRules>().toBeFunction()
  })
  test('pathToString', () => {
    expectTypeOf<typeof pathToString>().toBeFunction()
  })
  test('resolveTypeForArrayItem', () => {
    expectTypeOf<typeof resolveTypeForArrayItem>().toBeFunction()
  })
  test('Rule', () => {
    expectTypeOf<typeof Rule>().not.toBeNever()
  })
  test('typeString', () => {
    expectTypeOf<typeof typeString>().toBeFunction()
  })
  test('validateDocumentInternal', () => {
    expectTypeOf<typeof validateDocumentInternal>().toBeFunction()
  })
  test('ValidateDocumentInternalOptions', () => {
    expectTypeOf<ValidateDocumentInternalOptions>().toBeObject()
    expectTypeOf<ValidateDocumentInternalOptions['signal']>().toEqualTypeOf<
      AbortSignal | undefined
    >()
  })
  test('validateDocumentObservable', () => {
    expectTypeOf<typeof validateDocumentObservable>().toBeFunction()
  })
  test('ValidateDocumentObservableOptions', () => {
    expectTypeOf<ValidateDocumentObservableOptions>().toBeObject()
    expectTypeOf<ValidateDocumentObservableOptions['signal']>().toEqualTypeOf<
      AbortSignal | undefined
    >()
  })
  test('validateItem', () => {
    expectTypeOf<typeof validateItem>().toBeFunction()
  })
  test('ValidateItemOptions', () => {
    expectTypeOf<ValidateItemOptions['signal']>().toEqualTypeOf<AbortSignal | undefined>()
  })
  test('ValidationContext', () => {
    // This export has 2 declarations, run `TEST_DTS_EXPORTS_DIAGNOSTICS=duplicates pnpm generate:dts-exports` to see where each declaration is coming from
    expectTypeOf<ValidationContext>().toBeObject()
  })
  test('validationLocaleStrings', () => {
    expectTypeOf<typeof validationLocaleStrings>().not.toBeNever()
  })
})
