// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
import {describe, expectTypeOf, test} from 'vitest'
import type {
  arrayToJSONMatchPath,
  BufferedDocument,
  CommitHandlerMessage,
  Doc,
  Document,
  extract,
  extractWithPath,
  Mut,
  Mutation,
  MutationParams,
  SquashingBuffer,
  SubmissionResponder,
} from '@sanity/mutator'

describe('@sanity/mutator', () => {
  test('arrayToJSONMatchPath', () => {
    expectTypeOf<typeof arrayToJSONMatchPath>().toBeFunction()
  })
  test('BufferedDocument', () => {
    expectTypeOf<BufferedDocument>().not.toBeNever()
  })
  test('CommitHandlerMessage', () => {
    expectTypeOf<CommitHandlerMessage>().toBeObject()
  })
  test('Doc', () => {
    expectTypeOf<Doc>().toBeObject()
  })
  test('Document', () => {
    expectTypeOf<Document>().not.toBeNever()
  })
  test('extract', () => {
    expectTypeOf<typeof extract>().toBeFunction()
  })
  test('extractWithPath', () => {
    expectTypeOf<typeof extractWithPath>().toBeFunction()
  })
  test('Mut', () => {
    expectTypeOf<Mut>().toBeObject()
  })
  test('Mutation', () => {
    expectTypeOf<Mutation>().not.toBeNever()
  })
  test('MutationParams', () => {
    expectTypeOf<MutationParams>().toBeObject()
  })
  test('SquashingBuffer', () => {
    expectTypeOf<SquashingBuffer>().not.toBeNever()
  })
  test('SubmissionResponder', () => {
    expectTypeOf<SubmissionResponder>().toBeObject()
  })
})
