// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
import {describe, expectTypeOf, test} from 'vitest'
import type {absolutify, expandHome, pathIsEmpty} from '@sanity/util/fs'

describe('@sanity/util/fs', () => {
  test('absolutify', () => {
    expectTypeOf<typeof absolutify>().toBeFunction()
  })
  test('expandHome', () => {
    expectTypeOf<typeof expandHome>().toBeFunction()
  })
  test('pathIsEmpty', () => {
    expectTypeOf<typeof pathIsEmpty>().toBeFunction()
  })
})
