// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import {describe, expectTypeOf, test} from 'vitest'
import type {
  ArrayActionName,
  ArrayDefinition,
  ArrayOfEntry,
  ArrayOfType,
  ArrayOptions,
  ArrayRule,
  ArraySchemaType,
  ArraySchemaTypeOf,
  Asset,
  AssetFromSource,
  AssetMetadataType,
  AssetSchemaTypeOptions,
  AssetSource,
  AssetSourceComponentProps,
  AssetSourceSpec,
  AssetSourceUploader,
  AssetSourceUploaderClass,
  AssetSourceUploadEvent,
  AssetSourceUploadEventAbort,
  AssetSourceUploadEventAllComplete,
  AssetSourceUploadEventError,
  AssetSourceUploadEventProgress,
  AssetSourceUploadEventStatus,
  AssetSourceUploadFile,
  AssetSourceUploadSubscriber,
  AutocompleteString,
  BaseSchemaDefinition,
  BaseSchemaType,
  BaseSchemaTypeOptions,
  BlockAnnotationDefinition,
  BlockChildrenObjectField,
  BlockDecoratorDefinition,
  BlockDefinition,
  BlockListDefinition,
  BlockListObjectField,
  BlockMarksDefinition,
  BlockOptions,
  BlockRule,
  BlockSchemaType,
  BlockStyleDefinition,
  BlockStyleObjectField,
  BooleanDefinition,
  BooleanOptions,
  BooleanRule,
  BooleanSchemaType,
  CanvasAppOptions,
  CanvasNotificationPayload,
  CollapseOptions,
  ConditionalIndexAccess,
  ConditionalProperty,
  ConditionalPropertyCallback,
  ConditionalPropertyCallbackContext,
  CreateIfNotExistsMutation,
  CreateMutation,
  CreateOrReplaceMutation,
  CreateSquashedMutation,
  CrossDatasetReferenceDefinition,
  CrossDatasetReferenceFilterResolver,
  CrossDatasetReferenceFilterSearchOptions,
  CrossDatasetReferenceSchemaType,
  CrossDatasetReferenceValue,
  CrossDatasetType,
  CurrentUser,
  CustomValidator,
  CustomValidatorResult,
  DashboardNotificationPayload,
  DateDefinition,
  DateOptions,
  DateRule,
  DatetimeDefinition,
  DatetimeOptions,
  DatetimeRule,
  defineArrayMember,
  DefineArrayMemberBase,
  defineAssetAspect,
  defineField,
  DefineSchemaBase,
  DefineSchemaOptions,
  DefineSchemaType,
  defineType,
  DeleteMutation,
  DeprecatedProperty,
  DeprecatedSchemaType,
  DeprecationConfiguration,
  DocumentDefinition,
  DocumentOptions,
  DocumentRule,
  EmailDefinition,
  EmailOptions,
  EmailRule,
  EmptyProps,
  EnumListProps,
  FieldDefinition,
  FieldDefinitionBase,
  FieldGroup,
  FieldGroupDefinition,
  FieldReference,
  FieldRules,
  Fieldset,
  FieldsetDefinition,
  File,
  FileAsset,
  FileDefinition,
  FileOptions,
  FileRule,
  FileSchemaType,
  FileValue,
  FormNodeValidation,
  GeopointDefinition,
  GeopointOptions,
  GeopointRule,
  GeopointValue,
  GlobalDocumentReferenceDefinition,
  GlobalDocumentReferenceFilterResolver,
  GlobalDocumentReferenceFilterSearchOptions,
  GlobalDocumentReferenceSchemaType,
  GlobalDocumentReferenceType,
  GlobalDocumentReferenceValue,
  HotspotOptions,
  HotspotPreview,
  I18nTextRecord,
  I18nTitledListValue,
  Image,
  ImageAsset,
  ImageCrop,
  ImageDefinition,
  ImageDimensions,
  ImageHotspot,
  ImageMetadata,
  ImageMetadataType,
  ImageOptions,
  ImagePalette,
  ImageRule,
  ImageSchemaType,
  ImageSwatch,
  ImageUrlAutoMode,
  ImageUrlCropMode,
  ImageUrlFitMode,
  ImageUrlFormat,
  ImageUrlOrientation,
  ImageUrlParams,
  ImageValue,
  IndexTuple,
  InitialValueProperty,
  InitialValueResolver,
  InitialValueResolverContext,
  InlineFieldDefinition,
  InsertMenuOptions,
  InsertPatch,
  IntrinsicArrayOfBase,
  IntrinsicArrayOfDefinition,
  IntrinsicBase,
  IntrinsicDefinitions,
  IntrinsicTypeName,
  isArrayOfBlocksSchemaType,
  isArrayOfObjectsSchemaType,
  isArrayOfPrimitivesSchemaType,
  isArraySchemaType,
  isAssetAspect,
  isBlockChildrenObjectField,
  isBlockListObjectField,
  isBlockSchemaType,
  isBlockStyleObjectField,
  isBooleanSchemaType,
  isCreateIfNotExistsMutation,
  isCreateMutation,
  isCreateOrReplaceMutation,
  isCreateSquashedMutation,
  isCrossDatasetReference,
  isCrossDatasetReferenceSchemaType,
  isDateTimeSchemaType,
  isDeleteMutation,
  isDeprecatedSchemaType,
  isDeprecationConfiguration,
  isDocumentSchemaType,
  isFileSchemaType,
  isGlobalDocumentReference,
  isImage,
  isImageSchemaType,
  isIndexSegment,
  isIndexTuple,
  isKeyedObject,
  isKeySegment,
  isNumberSchemaType,
  isObjectSchemaType,
  isPatchMutation,
  isPortableTextListBlock,
  isPortableTextSpan,
  isPortableTextTextBlock,
  isPrimitiveSchemaType,
  isReference,
  isReferenceSchemaType,
  isSanityDocument,
  isSearchStrategy,
  isSlug,
  isSpanSchemaType,
  isStringSchemaType,
  isTitledListValue,
  isTypedObject,
  isValidationError,
  isValidationErrorMarker,
  isValidationInfo,
  isValidationInfoMarker,
  isValidationWarning,
  isValidationWarningMarker,
  KeyedObject,
  KeyedSegment,
  LocalizedValidationMessages,
  MaybeAllowUnknownProps,
  MaybePreview,
  MEDIA_LIBRARY_ASSET_ASPECT_TYPE_NAME,
  MediaAssetTypes,
  MediaLibraryAssetAspectDefinition,
  MediaLibraryAssetAspectDocument,
  MediaLibraryAssetAspectSupportedFieldDefinitions,
  MediaLibraryAssetAspectTypeName,
  MediaLibraryAssetType,
  MediaLibraryFilter,
  MediaLibraryOptions,
  MediaValidationValue,
  MediaValidator,
  MendozaEffectPair,
  MendozaPatch,
  MultiFieldSet,
  MultipleMutationResult,
  Mutation,
  MutationOperationName,
  MutationSelection,
  NarrowPreview,
  NumberDefinition,
  NumberOptions,
  NumberRule,
  NumberSchemaType,
  ObjectDefinition,
  ObjectField,
  ObjectFieldType,
  ObjectOptions,
  ObjectRule,
  ObjectSchemaType,
  ObjectSchemaTypeWithOptions,
  PatchMutation,
  PatchMutationOperation,
  PatchOperations,
  Path,
  PathSegment,
  PortableTextBlock,
  PortableTextChild,
  PortableTextListBlock,
  PortableTextObject,
  PortableTextSpan,
  PortableTextTextBlock,
  PrepareViewOptions,
  PreviewConfig,
  PreviewValue,
  Reference,
  ReferenceBaseOptions,
  ReferenceDefinition,
  ReferenceFilterOptions,
  ReferenceFilterQueryOptions,
  ReferenceFilterResolver,
  ReferenceFilterResolverContext,
  ReferenceFilterResolverOptions,
  ReferenceFilterSearchOptions,
  ReferenceOptions,
  ReferenceRule,
  ReferenceSchemaType,
  ReferenceTo,
  ReferenceValue,
  Role,
  Rule,
  RuleBuilder,
  RuleClass,
  RuleDef,
  RuleSpec,
  RuleSpecConstraint,
  RuleTypeConstraint,
  SanityCreateOptions,
  SanityDocument,
  SanityDocumentLike,
  Schema,
  SchemaType,
  SchemaTypeDefinition,
  SchemaValidationError,
  SchemaValidationProblem,
  SchemaValidationProblemGroup,
  SchemaValidationProblemPath,
  SchemaValidationValue,
  SchemaValidationWarning,
  SearchConfiguration,
  searchStrategies,
  SearchStrategy,
  SingleFieldSet,
  SingleMutationResult,
  Slug,
  SlugDefinition,
  SlugifierFn,
  SlugIsUniqueValidator,
  SlugOptions,
  SlugParent,
  SlugRule,
  SlugSchemaType,
  SlugSourceContext,
  SlugSourceFn,
  SlugValidationContext,
  SlugValue,
  SortOrdering,
  SortOrderingItem,
  SpanMarksObjectField,
  SpanSchemaType,
  SpanTextObjectField,
  StrictDefinition,
  StrictVersionLayeringOptions,
  StringDefinition,
  StringOptions,
  StringRule,
  StringSchemaType,
  StudioNotificationPayload,
  SwatchName,
  TextDefinition,
  TextOptions,
  TextRule,
  TextSchemaType,
  TitledListValue,
  TransactionLogEvent,
  TransactionLogEventWithEffects,
  TransactionLogEventWithMutations,
  TransactionLogMutation,
  TypeAliasDefinition,
  typed,
  TypedObject,
  TypeReference,
  UploadState,
  UriValidationOptions,
  UrlDefinition,
  UrlOptions,
  UrlRule,
  User,
  ValidationBuilder,
  ValidationContext,
  ValidationError,
  ValidationErrorClass,
  ValidationErrorOptions,
  ValidationMarker,
  Validator,
  Validators,
  WeakCrossDatasetReferenceValue,
  WeakGlobalDocumentReferenceValue,
  WeakReference,
  WidenInitialValue,
  WidenValidation,
} from '@sanity/types'

describe('@sanity/types', () => {
  test('ArrayActionName', () => {
    expectTypeOf<ArrayActionName>().not.toBeNever()
  })
  test('ArrayDefinition', () => {
    expectTypeOf<ArrayDefinition>().toBeObject()
  })
  test('ArrayOfEntry', () => {
    expectTypeOf<ArrayOfEntry<any>>().not.toBeNever()
  })
  test('ArrayOfType', () => {
    expectTypeOf<ArrayOfType<any, any>>().not.toBeNever()
  })
  test('ArrayOptions', () => {
    expectTypeOf<ArrayOptions<any>>().toBeObject()
  })
  test('ArrayRule', () => {
    expectTypeOf<ArrayRule<any>>().toBeObject()
  })
  test('ArraySchemaType', () => {
    expectTypeOf<ArraySchemaType<any>>().toBeObject()
  })
  test('ArraySchemaTypeOf', () => {
    expectTypeOf<ArraySchemaTypeOf<any>>().not.toBeNever()
  })
  test('Asset', () => {
    expectTypeOf<Asset>().toBeObject()
  })
  test('AssetFromSource', () => {
    expectTypeOf<AssetFromSource>().not.toBeNever()
  })
  test('AssetMetadataType', () => {
    expectTypeOf<AssetMetadataType>().not.toBeNever()
  })
  test('AssetSchemaTypeOptions', () => {
    expectTypeOf<AssetSchemaTypeOptions>().toBeObject()
  })
  test('AssetSource', () => {
    expectTypeOf<AssetSource>().toBeObject()
  })
  test('AssetSourceComponentProps', () => {
    expectTypeOf<AssetSourceComponentProps>().toBeObject()
  })
  test('AssetSourceSpec', () => {
    expectTypeOf<AssetSourceSpec>().toBeObject()
  })
  test('AssetSourceUploader', () => {
    expectTypeOf<AssetSourceUploader>().toBeObject()
  })
  test('AssetSourceUploaderClass', () => {
    expectTypeOf<AssetSourceUploaderClass>().not.toBeNever()
  })
  test('AssetSourceUploadEvent', () => {
    expectTypeOf<AssetSourceUploadEvent>().not.toBeNever()
  })
  test('AssetSourceUploadEventAbort', () => {
    expectTypeOf<AssetSourceUploadEventAbort>().not.toBeNever()
  })
  test('AssetSourceUploadEventAllComplete', () => {
    expectTypeOf<AssetSourceUploadEventAllComplete>().not.toBeNever()
  })
  test('AssetSourceUploadEventError', () => {
    expectTypeOf<AssetSourceUploadEventError>().not.toBeNever()
  })
  test('AssetSourceUploadEventProgress', () => {
    expectTypeOf<AssetSourceUploadEventProgress>().not.toBeNever()
  })
  test('AssetSourceUploadEventStatus', () => {
    expectTypeOf<AssetSourceUploadEventStatus>().not.toBeNever()
  })
  test('AssetSourceUploadFile', () => {
    expectTypeOf<AssetSourceUploadFile>().toBeObject()
  })
  test('AssetSourceUploadSubscriber', () => {
    expectTypeOf<AssetSourceUploadSubscriber>().not.toBeNever()
  })
  test('AutocompleteString', () => {
    expectTypeOf<AutocompleteString>().not.toBeNever()
  })
  test('BaseSchemaDefinition', () => {
    expectTypeOf<BaseSchemaDefinition>().toBeObject()
  })
  test('BaseSchemaType', () => {
    expectTypeOf<BaseSchemaType>().toBeObject()
  })
  test('BaseSchemaTypeOptions', () => {
    expectTypeOf<BaseSchemaTypeOptions>().toBeObject()
  })
  test('BlockAnnotationDefinition', () => {
    expectTypeOf<BlockAnnotationDefinition>().toBeObject()
  })
  test('BlockChildrenObjectField', () => {
    expectTypeOf<BlockChildrenObjectField>().not.toBeNever()
  })
  test('BlockDecoratorDefinition', () => {
    expectTypeOf<BlockDecoratorDefinition>().toBeObject()
  })
  test('BlockDefinition', () => {
    expectTypeOf<BlockDefinition>().toBeObject()
  })
  test('BlockListDefinition', () => {
    expectTypeOf<BlockListDefinition>().toBeObject()
  })
  test('BlockListObjectField', () => {
    expectTypeOf<BlockListObjectField>().not.toBeNever()
  })
  test('BlockMarksDefinition', () => {
    expectTypeOf<BlockMarksDefinition>().toBeObject()
  })
  test('BlockOptions', () => {
    expectTypeOf<BlockOptions>().toBeObject()
  })
  test('BlockRule', () => {
    expectTypeOf<BlockRule>().toBeObject()
  })
  test('BlockSchemaType', () => {
    expectTypeOf<BlockSchemaType>().toBeObject()
  })
  test('BlockStyleDefinition', () => {
    expectTypeOf<BlockStyleDefinition>().toBeObject()
  })
  test('BlockStyleObjectField', () => {
    expectTypeOf<BlockStyleObjectField>().not.toBeNever()
  })
  test('BooleanDefinition', () => {
    expectTypeOf<BooleanDefinition>().toBeObject()
  })
  test('BooleanOptions', () => {
    expectTypeOf<BooleanOptions>().toBeObject()
  })
  test('BooleanRule', () => {
    expectTypeOf<BooleanRule>().toBeObject()
  })
  test('BooleanSchemaType', () => {
    expectTypeOf<BooleanSchemaType>().toBeObject()
  })
  test('CanvasAppOptions', () => {
    expectTypeOf<CanvasAppOptions>().toBeObject()
  })
  test('CanvasNotificationPayload', () => {
    expectTypeOf<CanvasNotificationPayload>().toBeObject()
  })
  test('CollapseOptions', () => {
    expectTypeOf<CollapseOptions>().toBeObject()
  })
  test('ConditionalIndexAccess', () => {
    expectTypeOf<ConditionalIndexAccess<any, any>>().not.toBeNever()
  })
  test('ConditionalProperty', () => {
    expectTypeOf<ConditionalProperty>().not.toBeNever()
  })
  test('ConditionalPropertyCallback', () => {
    expectTypeOf<ConditionalPropertyCallback>().not.toBeNever()
  })
  test('ConditionalPropertyCallbackContext', () => {
    expectTypeOf<ConditionalPropertyCallbackContext>().toBeObject()
  })
  test('CreateIfNotExistsMutation', () => {
    expectTypeOf<CreateIfNotExistsMutation>().toBeObject()
  })
  test('CreateMutation', () => {
    expectTypeOf<CreateMutation>().toBeObject()
  })
  test('CreateOrReplaceMutation', () => {
    expectTypeOf<CreateOrReplaceMutation>().toBeObject()
  })
  test('CreateSquashedMutation', () => {
    expectTypeOf<CreateSquashedMutation>().toBeObject()
  })
  test('CrossDatasetReferenceDefinition', () => {
    expectTypeOf<CrossDatasetReferenceDefinition>().toBeObject()
  })
  test('CrossDatasetReferenceFilterResolver', () => {
    expectTypeOf<CrossDatasetReferenceFilterResolver>().not.toBeNever()
  })
  test('CrossDatasetReferenceFilterSearchOptions', () => {
    expectTypeOf<CrossDatasetReferenceFilterSearchOptions>().not.toBeNever()
  })
  test('CrossDatasetReferenceSchemaType', () => {
    expectTypeOf<CrossDatasetReferenceSchemaType>().toBeObject()
  })
  test('CrossDatasetReferenceValue', () => {
    expectTypeOf<CrossDatasetReferenceValue>().toBeObject()
  })
  test('CrossDatasetType', () => {
    expectTypeOf<CrossDatasetType>().toBeObject()
  })
  test('CurrentUser', () => {
    expectTypeOf<CurrentUser>().toBeObject()
  })
  test('CustomValidator', () => {
    expectTypeOf<CustomValidator<any>>().toBeObject()
  })
  test('CustomValidatorResult', () => {
    expectTypeOf<CustomValidatorResult>().not.toBeNever()
  })
  test('DashboardNotificationPayload', () => {
    expectTypeOf<DashboardNotificationPayload>().toBeObject()
  })
  test('DateDefinition', () => {
    expectTypeOf<DateDefinition>().toBeObject()
  })
  test('DateOptions', () => {
    expectTypeOf<DateOptions>().toBeObject()
  })
  test('DateRule', () => {
    expectTypeOf<DateRule>().toBeObject()
  })
  test('DatetimeDefinition', () => {
    expectTypeOf<DatetimeDefinition>().toBeObject()
  })
  test('DatetimeOptions', () => {
    expectTypeOf<DatetimeOptions>().toBeObject()
  })
  test('DatetimeRule', () => {
    expectTypeOf<DatetimeRule>().toBeObject()
  })
  test('defineArrayMember', () => {
    expectTypeOf<typeof defineArrayMember>().toBeFunction()
  })
  test('DefineArrayMemberBase', () => {
    expectTypeOf<DefineArrayMemberBase<any, any>>().not.toBeNever()
  })
  test('defineAssetAspect', () => {
    expectTypeOf<typeof defineAssetAspect>().toBeFunction()
  })
  test('defineField', () => {
    expectTypeOf<typeof defineField>().toBeFunction()
  })
  test('DefineSchemaBase', () => {
    expectTypeOf<DefineSchemaBase<any, any>>().not.toBeNever()
  })
  test('DefineSchemaOptions', () => {
    expectTypeOf<DefineSchemaOptions<any, any>>().toBeObject()
  })
  test('DefineSchemaType', () => {
    expectTypeOf<DefineSchemaType<any, any>>().not.toBeNever()
  })
  test('defineType', () => {
    expectTypeOf<typeof defineType>().toBeFunction()
  })
  test('DeleteMutation', () => {
    expectTypeOf<DeleteMutation>().toBeObject()
  })
  test('DeprecatedProperty', () => {
    expectTypeOf<DeprecatedProperty>().toBeObject()
  })
  test('DeprecatedSchemaType', () => {
    expectTypeOf<DeprecatedSchemaType<any>>().not.toBeNever()
  })
  test('DeprecationConfiguration', () => {
    expectTypeOf<DeprecationConfiguration>().toBeObject()
  })
  test('DocumentDefinition', () => {
    expectTypeOf<DocumentDefinition>().toBeObject()
  })
  test('DocumentOptions', () => {
    expectTypeOf<DocumentOptions>().toBeObject()
  })
  test('DocumentRule', () => {
    expectTypeOf<DocumentRule>().toBeObject()
  })
  test('EmailDefinition', () => {
    expectTypeOf<EmailDefinition>().toBeObject()
  })
  test('EmailOptions', () => {
    expectTypeOf<EmailOptions>().toBeObject()
  })
  test('EmailRule', () => {
    expectTypeOf<EmailRule>().toBeObject()
  })
  test('EmptyProps', () => {
    expectTypeOf<EmptyProps>().toBeObject()
  })
  test('EnumListProps', () => {
    expectTypeOf<EnumListProps<any>>().toBeObject()
  })
  test('FieldDefinition', () => {
    expectTypeOf<FieldDefinition<any, any>>().not.toBeNever()
  })
  test('FieldDefinitionBase', () => {
    expectTypeOf<FieldDefinitionBase>().toBeObject()
  })
  test('FieldGroup', () => {
    expectTypeOf<FieldGroup>().toBeObject()
  })
  test('FieldGroupDefinition', () => {
    expectTypeOf<FieldGroupDefinition>().not.toBeNever()
  })
  test('FieldReference', () => {
    expectTypeOf<FieldReference>().toBeObject()
  })
  test('FieldRules', () => {
    expectTypeOf<FieldRules>().not.toBeNever()
  })
  test('Fieldset', () => {
    expectTypeOf<Fieldset>().not.toBeNever()
  })
  test('FieldsetDefinition', () => {
    expectTypeOf<FieldsetDefinition>().not.toBeNever()
  })
  test('File', () => {
    expectTypeOf<File>().toBeObject()
  })
  test('FileAsset', () => {
    expectTypeOf<FileAsset>().toBeObject()
  })
  test('FileDefinition', () => {
    expectTypeOf<FileDefinition>().toBeObject()
  })
  test('FileOptions', () => {
    expectTypeOf<FileOptions>().toBeObject()
  })
  test('FileRule', () => {
    expectTypeOf<FileRule>().toBeObject()
  })
  test('FileSchemaType', () => {
    expectTypeOf<FileSchemaType>().toBeObject()
  })
  test('FileValue', () => {
    expectTypeOf<FileValue>().toBeObject()
  })
  test('FormNodeValidation', () => {
    expectTypeOf<FormNodeValidation>().toBeObject()
  })
  test('GeopointDefinition', () => {
    expectTypeOf<GeopointDefinition>().toBeObject()
  })
  test('GeopointOptions', () => {
    expectTypeOf<GeopointOptions>().toBeObject()
  })
  test('GeopointRule', () => {
    expectTypeOf<GeopointRule>().toBeObject()
  })
  test('GeopointValue', () => {
    expectTypeOf<GeopointValue>().toBeObject()
  })
  test('GlobalDocumentReferenceDefinition', () => {
    expectTypeOf<GlobalDocumentReferenceDefinition>().toBeObject()
  })
  test('GlobalDocumentReferenceFilterResolver', () => {
    expectTypeOf<GlobalDocumentReferenceFilterResolver>().not.toBeNever()
  })
  test('GlobalDocumentReferenceFilterSearchOptions', () => {
    expectTypeOf<GlobalDocumentReferenceFilterSearchOptions>().not.toBeNever()
  })
  test('GlobalDocumentReferenceSchemaType', () => {
    expectTypeOf<GlobalDocumentReferenceSchemaType>().toBeObject()
  })
  test('GlobalDocumentReferenceType', () => {
    expectTypeOf<GlobalDocumentReferenceType>().toBeObject()
  })
  test('GlobalDocumentReferenceValue', () => {
    expectTypeOf<GlobalDocumentReferenceValue>().toBeObject()
  })
  test('HotspotOptions', () => {
    expectTypeOf<HotspotOptions>().toBeObject()
  })
  test('HotspotPreview', () => {
    expectTypeOf<HotspotPreview>().toBeObject()
  })
  test('I18nTextRecord', () => {
    expectTypeOf<I18nTextRecord<any>>().not.toBeNever()
  })
  test('I18nTitledListValue', () => {
    expectTypeOf<I18nTitledListValue<any>>().toBeObject()
  })
  test('Image', () => {
    expectTypeOf<Image>().toBeObject()
  })
  test('ImageAsset', () => {
    expectTypeOf<ImageAsset>().toBeObject()
  })
  test('ImageCrop', () => {
    expectTypeOf<ImageCrop>().toBeObject()
  })
  test('ImageDefinition', () => {
    expectTypeOf<ImageDefinition>().toBeObject()
  })
  test('ImageDimensions', () => {
    expectTypeOf<ImageDimensions>().toBeObject()
  })
  test('ImageHotspot', () => {
    expectTypeOf<ImageHotspot>().toBeObject()
  })
  test('ImageMetadata', () => {
    expectTypeOf<ImageMetadata>().toBeObject()
  })
  test('ImageMetadataType', () => {
    expectTypeOf<ImageMetadataType>().not.toBeNever()
  })
  test('ImageOptions', () => {
    expectTypeOf<ImageOptions>().toBeObject()
  })
  test('ImagePalette', () => {
    expectTypeOf<ImagePalette>().toBeObject()
  })
  test('ImageRule', () => {
    expectTypeOf<ImageRule>().toBeObject()
  })
  test('ImageSchemaType', () => {
    expectTypeOf<ImageSchemaType>().toBeObject()
  })
  test('ImageSwatch', () => {
    expectTypeOf<ImageSwatch>().toBeObject()
  })
  test('ImageUrlAutoMode', () => {
    expectTypeOf<ImageUrlAutoMode>().not.toBeNever()
  })
  test('ImageUrlCropMode', () => {
    expectTypeOf<ImageUrlCropMode>().not.toBeNever()
  })
  test('ImageUrlFitMode', () => {
    expectTypeOf<ImageUrlFitMode>().not.toBeNever()
  })
  test('ImageUrlFormat', () => {
    expectTypeOf<ImageUrlFormat>().not.toBeNever()
  })
  test('ImageUrlOrientation', () => {
    expectTypeOf<ImageUrlOrientation>().not.toBeNever()
  })
  test('ImageUrlParams', () => {
    expectTypeOf<ImageUrlParams>().toBeObject()
  })
  test('ImageValue', () => {
    expectTypeOf<ImageValue>().toBeObject()
  })
  test('IndexTuple', () => {
    expectTypeOf<IndexTuple>().not.toBeNever()
  })
  test('InitialValueProperty', () => {
    expectTypeOf<InitialValueProperty<any, any>>().not.toBeNever()
  })
  test('InitialValueResolver', () => {
    expectTypeOf<InitialValueResolver<any, any>>().not.toBeNever()
  })
  test('InitialValueResolverContext', () => {
    expectTypeOf<InitialValueResolverContext>().toBeObject()
  })
  test('InlineFieldDefinition', () => {
    expectTypeOf<InlineFieldDefinition>().not.toBeNever()
  })
  test('InsertMenuOptions', () => {
    expectTypeOf<InsertMenuOptions>().toBeObject()
  })
  test('InsertPatch', () => {
    expectTypeOf<InsertPatch>().not.toBeNever()
  })
  test('IntrinsicArrayOfBase', () => {
    expectTypeOf<IntrinsicArrayOfBase>().not.toBeNever()
  })
  test('IntrinsicArrayOfDefinition', () => {
    expectTypeOf<IntrinsicArrayOfDefinition>().not.toBeNever()
  })
  test('IntrinsicBase', () => {
    expectTypeOf<IntrinsicBase>().not.toBeNever()
  })
  test('IntrinsicDefinitions', () => {
    expectTypeOf<IntrinsicDefinitions>().toBeObject()
  })
  test('IntrinsicTypeName', () => {
    expectTypeOf<IntrinsicTypeName>().not.toBeNever()
  })
  test('isArrayOfBlocksSchemaType', () => {
    expectTypeOf<typeof isArrayOfBlocksSchemaType>().toBeFunction()
  })
  test('isArrayOfObjectsSchemaType', () => {
    expectTypeOf<typeof isArrayOfObjectsSchemaType>().toBeFunction()
  })
  test('isArrayOfPrimitivesSchemaType', () => {
    expectTypeOf<typeof isArrayOfPrimitivesSchemaType>().toBeFunction()
  })
  test('isArraySchemaType', () => {
    expectTypeOf<typeof isArraySchemaType>().toBeFunction()
  })
  test('isAssetAspect', () => {
    expectTypeOf<typeof isAssetAspect>().toBeFunction()
  })
  test('isBlockChildrenObjectField', () => {
    expectTypeOf<typeof isBlockChildrenObjectField>().toBeFunction()
  })
  test('isBlockListObjectField', () => {
    expectTypeOf<typeof isBlockListObjectField>().toBeFunction()
  })
  test('isBlockSchemaType', () => {
    expectTypeOf<typeof isBlockSchemaType>().toBeFunction()
  })
  test('isBlockStyleObjectField', () => {
    expectTypeOf<typeof isBlockStyleObjectField>().toBeFunction()
  })
  test('isBooleanSchemaType', () => {
    expectTypeOf<typeof isBooleanSchemaType>().toBeFunction()
  })
  test('isCreateIfNotExistsMutation', () => {
    expectTypeOf<typeof isCreateIfNotExistsMutation>().toBeFunction()
  })
  test('isCreateMutation', () => {
    expectTypeOf<typeof isCreateMutation>().toBeFunction()
  })
  test('isCreateOrReplaceMutation', () => {
    expectTypeOf<typeof isCreateOrReplaceMutation>().toBeFunction()
  })
  test('isCreateSquashedMutation', () => {
    expectTypeOf<typeof isCreateSquashedMutation>().toBeFunction()
  })
  test('isCrossDatasetReference', () => {
    expectTypeOf<typeof isCrossDatasetReference>().toBeFunction()
  })
  test('isCrossDatasetReferenceSchemaType', () => {
    expectTypeOf<typeof isCrossDatasetReferenceSchemaType>().toBeFunction()
  })
  test('isDateTimeSchemaType', () => {
    expectTypeOf<typeof isDateTimeSchemaType>().toBeFunction()
  })
  test('isDeleteMutation', () => {
    expectTypeOf<typeof isDeleteMutation>().toBeFunction()
  })
  test('isDeprecatedSchemaType', () => {
    expectTypeOf<typeof isDeprecatedSchemaType>().toBeFunction()
  })
  test('isDeprecationConfiguration', () => {
    expectTypeOf<typeof isDeprecationConfiguration>().toBeFunction()
  })
  test('isDocumentSchemaType', () => {
    expectTypeOf<typeof isDocumentSchemaType>().toBeFunction()
  })
  test('isFileSchemaType', () => {
    expectTypeOf<typeof isFileSchemaType>().toBeFunction()
  })
  test('isGlobalDocumentReference', () => {
    expectTypeOf<typeof isGlobalDocumentReference>().toBeFunction()
  })
  test('isImage', () => {
    expectTypeOf<typeof isImage>().toBeFunction()
  })
  test('isImageSchemaType', () => {
    expectTypeOf<typeof isImageSchemaType>().toBeFunction()
  })
  test('isIndexSegment', () => {
    expectTypeOf<typeof isIndexSegment>().toBeFunction()
  })
  test('isIndexTuple', () => {
    expectTypeOf<typeof isIndexTuple>().toBeFunction()
  })
  test('isKeyedObject', () => {
    expectTypeOf<typeof isKeyedObject>().toBeFunction()
  })
  test('isKeySegment', () => {
    expectTypeOf<typeof isKeySegment>().toBeFunction()
  })
  test('isNumberSchemaType', () => {
    expectTypeOf<typeof isNumberSchemaType>().toBeFunction()
  })
  test('isObjectSchemaType', () => {
    expectTypeOf<typeof isObjectSchemaType>().toBeFunction()
  })
  test('isPatchMutation', () => {
    expectTypeOf<typeof isPatchMutation>().toBeFunction()
  })
  test('isPortableTextListBlock', () => {
    expectTypeOf<typeof isPortableTextListBlock>().toBeFunction()
  })
  test('isPortableTextSpan', () => {
    expectTypeOf<typeof isPortableTextSpan>().toBeFunction()
  })
  test('isPortableTextTextBlock', () => {
    expectTypeOf<typeof isPortableTextTextBlock>().toBeFunction()
  })
  test('isPrimitiveSchemaType', () => {
    expectTypeOf<typeof isPrimitiveSchemaType>().toBeFunction()
  })
  test('isReference', () => {
    expectTypeOf<typeof isReference>().toBeFunction()
  })
  test('isReferenceSchemaType', () => {
    expectTypeOf<typeof isReferenceSchemaType>().toBeFunction()
  })
  test('isSanityDocument', () => {
    expectTypeOf<typeof isSanityDocument>().toBeFunction()
  })
  test('isSearchStrategy', () => {
    expectTypeOf<typeof isSearchStrategy>().toBeFunction()
  })
  test('isSlug', () => {
    expectTypeOf<typeof isSlug>().toBeFunction()
  })
  test('isSpanSchemaType', () => {
    expectTypeOf<typeof isSpanSchemaType>().toBeFunction()
  })
  test('isStringSchemaType', () => {
    expectTypeOf<typeof isStringSchemaType>().toBeFunction()
  })
  test('isTitledListValue', () => {
    expectTypeOf<typeof isTitledListValue>().toBeFunction()
  })
  test('isTypedObject', () => {
    expectTypeOf<typeof isTypedObject>().toBeFunction()
  })
  test('isValidationError', () => {
    expectTypeOf<typeof isValidationError>().toBeFunction()
  })
  test('isValidationErrorMarker', () => {
    expectTypeOf<typeof isValidationErrorMarker>().toBeFunction()
  })
  test('isValidationInfo', () => {
    expectTypeOf<typeof isValidationInfo>().toBeFunction()
  })
  test('isValidationInfoMarker', () => {
    expectTypeOf<typeof isValidationInfoMarker>().toBeFunction()
  })
  test('isValidationWarning', () => {
    expectTypeOf<typeof isValidationWarning>().toBeFunction()
  })
  test('isValidationWarningMarker', () => {
    expectTypeOf<typeof isValidationWarningMarker>().toBeFunction()
  })
  test('KeyedObject', () => {
    expectTypeOf<KeyedObject>().toBeObject()
  })
  test('KeyedSegment', () => {
    expectTypeOf<KeyedSegment>().not.toBeNever()
  })
  test('LocalizedValidationMessages', () => {
    expectTypeOf<LocalizedValidationMessages>().toBeObject()
  })
  test('MaybeAllowUnknownProps', () => {
    expectTypeOf<MaybeAllowUnknownProps<any>>().not.toBeNever()
  })
  test('MaybePreview', () => {
    expectTypeOf<MaybePreview<any, any>>().not.toBeNever()
  })
  test('MEDIA_LIBRARY_ASSET_ASPECT_TYPE_NAME', () => {
    expectTypeOf<typeof MEDIA_LIBRARY_ASSET_ASPECT_TYPE_NAME>().not.toBeNever()
  })
  test('MediaAssetTypes', () => {
    expectTypeOf<MediaAssetTypes>().not.toBeNever()
  })
  test('MediaLibraryAssetAspectDefinition', () => {
    expectTypeOf<MediaLibraryAssetAspectDefinition>().not.toBeNever()
  })
  test('MediaLibraryAssetAspectDocument', () => {
    expectTypeOf<MediaLibraryAssetAspectDocument>().toBeObject()
  })
  test('MediaLibraryAssetAspectSupportedFieldDefinitions', () => {
    expectTypeOf<MediaLibraryAssetAspectSupportedFieldDefinitions>().not.toBeNever()
  })
  test('MediaLibraryAssetAspectTypeName', () => {
    expectTypeOf<MediaLibraryAssetAspectTypeName>().not.toBeNever()
  })
  test('MediaLibraryAssetType', () => {
    expectTypeOf<MediaLibraryAssetType>().not.toBeNever()
  })
  test('MediaLibraryFilter', () => {
    expectTypeOf<MediaLibraryFilter>().toBeObject()
  })
  test('MediaLibraryOptions', () => {
    expectTypeOf<MediaLibraryOptions>().toBeObject()
  })
  test('MediaValidationValue', () => {
    expectTypeOf<MediaValidationValue<any>>().toBeObject()
  })
  test('MediaValidator', () => {
    expectTypeOf<MediaValidator<any>>().toBeObject()
  })
  test('MendozaEffectPair', () => {
    expectTypeOf<MendozaEffectPair>().toBeObject()
  })
  test('MendozaPatch', () => {
    expectTypeOf<MendozaPatch>().not.toBeNever()
  })
  test('MultiFieldSet', () => {
    expectTypeOf<MultiFieldSet>().toBeObject()
  })
  test('MultipleMutationResult', () => {
    expectTypeOf<MultipleMutationResult>().toBeObject()
  })
  test('Mutation', () => {
    expectTypeOf<Mutation>().not.toBeNever()
  })
  test('MutationOperationName', () => {
    expectTypeOf<MutationOperationName>().not.toBeNever()
  })
  test('MutationSelection', () => {
    expectTypeOf<MutationSelection>().not.toBeNever()
  })
  test('NarrowPreview', () => {
    expectTypeOf<NarrowPreview<any, any, any, any>>().not.toBeNever()
  })
  test('NumberDefinition', () => {
    expectTypeOf<NumberDefinition>().toBeObject()
  })
  test('NumberOptions', () => {
    expectTypeOf<NumberOptions>().toBeObject()
  })
  test('NumberRule', () => {
    expectTypeOf<NumberRule>().toBeObject()
  })
  test('NumberSchemaType', () => {
    expectTypeOf<NumberSchemaType>().toBeObject()
  })
  test('ObjectDefinition', () => {
    expectTypeOf<ObjectDefinition>().toBeObject()
  })
  test('ObjectField', () => {
    expectTypeOf<ObjectField<any>>().toBeObject()
  })
  test('ObjectFieldType', () => {
    expectTypeOf<ObjectFieldType<any>>().not.toBeNever()
  })
  test('ObjectOptions', () => {
    expectTypeOf<ObjectOptions>().toBeObject()
  })
  test('ObjectRule', () => {
    expectTypeOf<ObjectRule>().toBeObject()
  })
  test('ObjectSchemaType', () => {
    expectTypeOf<ObjectSchemaType>().toBeObject()
  })
  test('ObjectSchemaTypeWithOptions', () => {
    expectTypeOf<ObjectSchemaTypeWithOptions>().toBeObject()
  })
  test('PatchMutation', () => {
    expectTypeOf<PatchMutation>().toBeObject()
  })
  test('PatchMutationOperation', () => {
    expectTypeOf<PatchMutationOperation>().not.toBeNever()
  })
  test('PatchOperations', () => {
    expectTypeOf<PatchOperations>().toBeObject()
  })
  test('Path', () => {
    expectTypeOf<Path>().not.toBeNever()
  })
  test('PathSegment', () => {
    expectTypeOf<PathSegment>().not.toBeNever()
  })
  test('PortableTextBlock', () => {
    expectTypeOf<PortableTextBlock>().not.toBeNever()
  })
  test('PortableTextChild', () => {
    expectTypeOf<PortableTextChild>().not.toBeNever()
  })
  test('PortableTextListBlock', () => {
    expectTypeOf<PortableTextListBlock>().toBeObject()
  })
  test('PortableTextObject', () => {
    expectTypeOf<PortableTextObject>().toBeObject()
  })
  test('PortableTextSpan', () => {
    expectTypeOf<PortableTextSpan>().toBeObject()
  })
  test('PortableTextTextBlock', () => {
    expectTypeOf<PortableTextTextBlock<any>>().toBeObject()
  })
  test('PrepareViewOptions', () => {
    expectTypeOf<PrepareViewOptions>().toBeObject()
  })
  test('PreviewConfig', () => {
    expectTypeOf<PreviewConfig<any, any>>().toBeObject()
  })
  test('PreviewValue', () => {
    expectTypeOf<PreviewValue>().toBeObject()
  })
  test('Reference', () => {
    expectTypeOf<Reference>().toBeObject()
  })
  test('ReferenceBaseOptions', () => {
    expectTypeOf<ReferenceBaseOptions>().toBeObject()
  })
  test('ReferenceDefinition', () => {
    expectTypeOf<ReferenceDefinition>().toBeObject()
  })
  test('ReferenceFilterOptions', () => {
    expectTypeOf<ReferenceFilterOptions>().not.toBeNever()
  })
  test('ReferenceFilterQueryOptions', () => {
    expectTypeOf<ReferenceFilterQueryOptions>().toBeObject()
  })
  test('ReferenceFilterResolver', () => {
    expectTypeOf<ReferenceFilterResolver>().not.toBeNever()
  })
  test('ReferenceFilterResolverContext', () => {
    expectTypeOf<ReferenceFilterResolverContext>().toBeObject()
  })
  test('ReferenceFilterResolverOptions', () => {
    expectTypeOf<ReferenceFilterResolverOptions>().toBeObject()
  })
  test('ReferenceFilterSearchOptions', () => {
    expectTypeOf<ReferenceFilterSearchOptions>().not.toBeNever()
  })
  test('ReferenceOptions', () => {
    expectTypeOf<ReferenceOptions>().not.toBeNever()
  })
  test('ReferenceRule', () => {
    expectTypeOf<ReferenceRule>().toBeObject()
  })
  test('ReferenceSchemaType', () => {
    expectTypeOf<ReferenceSchemaType>().toBeObject()
  })
  test('ReferenceTo', () => {
    expectTypeOf<ReferenceTo>().not.toBeNever()
  })
  test('ReferenceValue', () => {
    expectTypeOf<ReferenceValue>().not.toBeNever()
  })
  test('Role', () => {
    expectTypeOf<Role>().toBeObject()
  })
  test('Rule', () => {
    expectTypeOf<Rule>().toBeObject()
  })
  test('RuleBuilder', () => {
    expectTypeOf<RuleBuilder<any, any>>().not.toBeNever()
  })
  test('RuleClass', () => {
    expectTypeOf<RuleClass>().toBeObject()
  })
  test('RuleDef', () => {
    expectTypeOf<RuleDef<any, any>>().toBeObject()
  })
  test('RuleSpec', () => {
    expectTypeOf<RuleSpec>().not.toBeNever()
  })
  test('RuleSpecConstraint', () => {
    expectTypeOf<RuleSpecConstraint<any>>().not.toBeNever()
  })
  test('RuleTypeConstraint', () => {
    expectTypeOf<RuleTypeConstraint>().not.toBeNever()
  })
  test('SanityCreateOptions', () => {
    expectTypeOf<SanityCreateOptions>().toBeObject()
  })
  test('SanityDocument', () => {
    expectTypeOf<SanityDocument>().toBeObject()
  })
  test('SanityDocumentLike', () => {
    expectTypeOf<SanityDocumentLike>().toBeObject()
  })
  test('Schema', () => {
    expectTypeOf<Schema>().toBeObject()
  })
  test('SchemaType', () => {
    expectTypeOf<SchemaType>().not.toBeNever()
  })
  test('SchemaTypeDefinition', () => {
    expectTypeOf<SchemaTypeDefinition<any>>().not.toBeNever()
  })
  test('SchemaValidationError', () => {
    expectTypeOf<SchemaValidationError>().toBeObject()
  })
  test('SchemaValidationProblem', () => {
    expectTypeOf<SchemaValidationProblem>().not.toBeNever()
  })
  test('SchemaValidationProblemGroup', () => {
    expectTypeOf<SchemaValidationProblemGroup>().toBeObject()
  })
  test('SchemaValidationProblemPath', () => {
    expectTypeOf<SchemaValidationProblemPath>().not.toBeNever()
  })
  test('SchemaValidationValue', () => {
    expectTypeOf<SchemaValidationValue>().not.toBeNever()
  })
  test('SchemaValidationWarning', () => {
    expectTypeOf<SchemaValidationWarning>().toBeObject()
  })
  test('SearchConfiguration', () => {
    expectTypeOf<SearchConfiguration>().toBeObject()
  })
  test('searchStrategies', () => {
    expectTypeOf<typeof searchStrategies>().not.toBeNever()
  })
  test('SearchStrategy', () => {
    expectTypeOf<SearchStrategy>().not.toBeNever()
  })
  test('SingleFieldSet', () => {
    expectTypeOf<SingleFieldSet>().toBeObject()
  })
  test('SingleMutationResult', () => {
    expectTypeOf<SingleMutationResult>().toBeObject()
  })
  test('Slug', () => {
    expectTypeOf<Slug>().toBeObject()
  })
  test('SlugDefinition', () => {
    expectTypeOf<SlugDefinition>().toBeObject()
  })
  test('SlugifierFn', () => {
    expectTypeOf<SlugifierFn>().not.toBeNever()
  })
  test('SlugIsUniqueValidator', () => {
    expectTypeOf<SlugIsUniqueValidator>().not.toBeNever()
  })
  test('SlugOptions', () => {
    expectTypeOf<SlugOptions>().toBeObject()
  })
  test('SlugParent', () => {
    expectTypeOf<SlugParent>().not.toBeNever()
  })
  test('SlugRule', () => {
    expectTypeOf<SlugRule>().toBeObject()
  })
  test('SlugSchemaType', () => {
    expectTypeOf<SlugSchemaType>().toBeObject()
  })
  test('SlugSourceContext', () => {
    expectTypeOf<SlugSourceContext>().toBeObject()
  })
  test('SlugSourceFn', () => {
    expectTypeOf<SlugSourceFn>().not.toBeNever()
  })
  test('SlugValidationContext', () => {
    expectTypeOf<SlugValidationContext>().toBeObject()
  })
  test('SlugValue', () => {
    expectTypeOf<SlugValue>().toBeObject()
  })
  test('SortOrdering', () => {
    expectTypeOf<SortOrdering>().not.toBeNever()
  })
  test('SortOrderingItem', () => {
    expectTypeOf<SortOrderingItem>().toBeObject()
  })
  test('SpanMarksObjectField', () => {
    expectTypeOf<SpanMarksObjectField>().not.toBeNever()
  })
  test('SpanSchemaType', () => {
    expectTypeOf<SpanSchemaType>().toBeObject()
  })
  test('SpanTextObjectField', () => {
    expectTypeOf<SpanTextObjectField>().not.toBeNever()
  })
  test('StrictDefinition', () => {
    expectTypeOf<StrictDefinition>().not.toBeNever()
  })
  test('StrictVersionLayeringOptions', () => {
    expectTypeOf<StrictVersionLayeringOptions>().toBeObject()
  })
  test('StringDefinition', () => {
    expectTypeOf<StringDefinition>().toBeObject()
  })
  test('StringOptions', () => {
    expectTypeOf<StringOptions>().toBeObject()
  })
  test('StringRule', () => {
    expectTypeOf<StringRule>().toBeObject()
  })
  test('StringSchemaType', () => {
    expectTypeOf<StringSchemaType>().toBeObject()
  })
  test('StudioNotificationPayload', () => {
    expectTypeOf<StudioNotificationPayload>().toBeObject()
  })
  test('SwatchName', () => {
    expectTypeOf<SwatchName>().not.toBeNever()
  })
  test('TextDefinition', () => {
    expectTypeOf<TextDefinition>().toBeObject()
  })
  test('TextOptions', () => {
    expectTypeOf<TextOptions>().toBeObject()
  })
  test('TextRule', () => {
    expectTypeOf<TextRule>().toBeObject()
  })
  test('TextSchemaType', () => {
    expectTypeOf<TextSchemaType>().toBeObject()
  })
  test('TitledListValue', () => {
    expectTypeOf<TitledListValue<any>>().toBeObject()
  })
  test('TransactionLogEvent', () => {
    expectTypeOf<TransactionLogEvent>().toBeObject()
  })
  test('TransactionLogEventWithEffects', () => {
    expectTypeOf<TransactionLogEventWithEffects>().toBeObject()
  })
  test('TransactionLogEventWithMutations', () => {
    expectTypeOf<TransactionLogEventWithMutations>().toBeObject()
  })
  test('TransactionLogMutation', () => {
    expectTypeOf<TransactionLogMutation>().not.toBeNever()
  })
  test('TypeAliasDefinition', () => {
    expectTypeOf<TypeAliasDefinition<any, any>>().toBeObject()
  })
  test('typed', () => {
    expectTypeOf<typeof typed>().toBeFunction()
  })
  test('TypedObject', () => {
    expectTypeOf<TypedObject>().toBeObject()
  })
  test('TypeReference', () => {
    expectTypeOf<TypeReference>().toBeObject()
  })
  test('UploadState', () => {
    expectTypeOf<UploadState>().toBeObject()
  })
  test('UriValidationOptions', () => {
    expectTypeOf<UriValidationOptions>().toBeObject()
  })
  test('UrlDefinition', () => {
    expectTypeOf<UrlDefinition>().toBeObject()
  })
  test('UrlOptions', () => {
    expectTypeOf<UrlOptions>().toBeObject()
  })
  test('UrlRule', () => {
    expectTypeOf<UrlRule>().toBeObject()
  })
  test('User', () => {
    expectTypeOf<User>().toBeObject()
  })
  test('ValidationBuilder', () => {
    expectTypeOf<ValidationBuilder<any, any>>().not.toBeNever()
  })
  test('ValidationContext', () => {
    expectTypeOf<ValidationContext>().toBeObject()
  })
  test('ValidationError', () => {
    expectTypeOf<ValidationError>().toBeObject()
  })
  test('ValidationErrorClass', () => {
    expectTypeOf<ValidationErrorClass>().toBeObject()
  })
  test('ValidationErrorOptions', () => {
    expectTypeOf<ValidationErrorOptions>().toBeObject()
  })
  test('ValidationMarker', () => {
    expectTypeOf<ValidationMarker>().toBeObject()
  })
  test('Validator', () => {
    expectTypeOf<Validator<any, any>>().not.toBeNever()
  })
  test('Validators', () => {
    expectTypeOf<Validators>().not.toBeNever()
  })
  test('WeakCrossDatasetReferenceValue', () => {
    expectTypeOf<WeakCrossDatasetReferenceValue>().toBeObject()
  })
  test('WeakGlobalDocumentReferenceValue', () => {
    expectTypeOf<WeakGlobalDocumentReferenceValue>().toBeObject()
  })
  test('WeakReference', () => {
    expectTypeOf<WeakReference>().toBeObject()
  })
  test('WidenInitialValue', () => {
    expectTypeOf<WidenInitialValue>().toBeObject()
  })
  test('WidenValidation', () => {
    expectTypeOf<WidenValidation>().toBeObject()
  })
})
