// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
import {describe, expectTypeOf, test} from 'vitest'
import type {ConcurrencyLimiter} from '@sanity/util/concurrency-limiter'

describe('@sanity/util/concurrency-limiter', () => {
  test('ConcurrencyLimiter', () => {
    expectTypeOf<ConcurrencyLimiter>().not.toBeNever()
  })
})
