// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
import {describe, expectTypeOf, test} from 'vitest'
import type {createSafeJsonParser} from '@sanity/util/createSafeJsonParser'

describe('@sanity/util/createSafeJsonParser', () => {
  test('createSafeJsonParser', () => {
    expectTypeOf<typeof createSafeJsonParser>().toBeFunction()
  })
})
