// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import {describe, expectTypeOf, test} from 'vitest'
import type {
  default as _default,
  defineQuery,
  PickSchema,
  SanityDocument,
  SanityQueries,
  SanityQueryResult,
  SanitySchema,
  SanitySchemas,
  SanitySchemaType,
  SchemaOrigin,
} from 'groq'

describe('groq', () => {
  test('default', () => {
    expectTypeOf<typeof _default>().toBeFunction()
  })
  test('defineQuery', () => {
    expectTypeOf<typeof defineQuery>().toBeFunction()
  })
  test('PickSchema', () => {
    expectTypeOf<PickSchema<any, any>>().not.toBeNever()
  })
  test('SanityDocument', () => {
    expectTypeOf<SanityDocument<any, any>>().not.toBeNever()
  })
  test('SanityQueries', () => {
    expectTypeOf<SanityQueries>().toBeObject()
  })
  test('SanityQueryResult', () => {
    expectTypeOf<SanityQueryResult<any, any>>().toBeNever()
  })
  test('SanitySchema', () => {
    expectTypeOf<SanitySchema<any>>().toBeNever()
  })
  test('SanitySchemas', () => {
    expectTypeOf<SanitySchemas>().toBeObject()
  })
  test('SanitySchemaType', () => {
    expectTypeOf<SanitySchemaType<any, any>>().toBeNever()
  })
  test('SchemaOrigin', () => {
    expectTypeOf<SchemaOrigin<any, any>>().not.toBeNever()
  })
})
