// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import type {default as _default, defineQuery, 'module.exports' as _module_exports} from 'groq'
import {describe, expectTypeOf, test} from 'vitest'

describe('groq', () => {
  test('default', () => {
    expectTypeOf<typeof _default>().not.toBeNever()
  })
  test('defineQuery', () => {
    expectTypeOf<typeof defineQuery>().toBeFunction()
  })
  test('module.exports', () => {
    expectTypeOf<typeof _module_exports>().not.toBeNever()
  })
})
