// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import {describe, expectTypeOf, test} from 'vitest'
import type {
  AnyOp,
  APIConfig,
  append,
  ArrayOp,
  AsyncIterableMigration,
  at,
  collectMigrationMutations,
  create,
  createIfNotExists,
  CreateIfNotExistsMutation,
  CreateMutation,
  createOrReplace,
  CreateOrReplaceMutation,
  dec,
  decodeText,
  DecOp,
  DEFAULT_MUTATION_CONCURRENCY,
  defineMigration,
  del,
  delay,
  delete_,
  DeleteMutation,
  diffMatchPatch,
  DiffMatchPatchOp,
  DocumentMigrationReturnValue,
  dryRun,
  ExportAPIConfig,
  filter,
  fromDocuments,
  fromExportArchive,
  fromExportEndpoint,
  inc,
  IncOp,
  IndexedSegment,
  insert,
  insertAfter,
  insertBefore,
  InsertOp,
  JsonArray,
  JsonObject,
  JSONOptions,
  JSONParser,
  JsonPrimitive,
  JsonValue,
  KeyedSegment,
  map,
  MAX_MUTATION_CONCURRENCY,
  MigrateDefinition,
  Migration,
  MigrationContext,
  MigrationProgress,
  MigrationRunnerConfig,
  Mutation,
  NodeMigration,
  NodeMigrationReturnValue,
  NodePatch,
  NodePatchList,
  NumberOp,
  Operation,
  parse,
  parseJSON,
  patch,
  PatchMutation,
  PatchOptions,
  Path,
  prepend,
  PrimitiveOp,
  RelativePosition,
  replace,
  ReplaceOp,
  run,
  safeJsonParser,
  SanityDocument,
  set,
  setIfMissing,
  SetIfMissingOp,
  SetOp,
  split,
  stringify,
  stringifyJSON,
  StringOp,
  take,
  toArray,
  toFetchOptionsIterable,
  transaction,
  Transaction,
  truncate,
  TruncateOp,
  unset,
  UnsetOp,
} from 'sanity/migrate'

describe('sanity/migrate', () => {
  test('AnyOp', () => {
    expectTypeOf<AnyOp>().not.toBeNever()
  })
  test('APIConfig', () => {
    expectTypeOf<APIConfig>().toBeObject()
  })
  test('append', () => {
    expectTypeOf<typeof append>().toBeFunction()
  })
  test('ArrayOp', () => {
    expectTypeOf<ArrayOp>().not.toBeNever()
  })
  test('AsyncIterableMigration', () => {
    expectTypeOf<AsyncIterableMigration>().not.toBeNever()
  })
  test('at', () => {
    expectTypeOf<typeof at>().toBeFunction()
  })
  test('collectMigrationMutations', () => {
    expectTypeOf<typeof collectMigrationMutations>().toBeFunction()
  })
  test('create', () => {
    expectTypeOf<typeof create>().toBeFunction()
  })
  test('createIfNotExists', () => {
    expectTypeOf<typeof createIfNotExists>().toBeFunction()
  })
  test('CreateIfNotExistsMutation', () => {
    expectTypeOf<CreateIfNotExistsMutation<any>>().not.toBeNever()
  })
  test('CreateMutation', () => {
    expectTypeOf<CreateMutation<any>>().not.toBeNever()
  })
  test('createOrReplace', () => {
    expectTypeOf<typeof createOrReplace>().toBeFunction()
  })
  test('CreateOrReplaceMutation', () => {
    expectTypeOf<CreateOrReplaceMutation<any>>().not.toBeNever()
  })
  test('dec', () => {
    expectTypeOf<typeof dec>().not.toBeNever()
  })
  test('decodeText', () => {
    expectTypeOf<typeof decodeText>().toBeFunction()
  })
  test('DecOp', () => {
    expectTypeOf<DecOp<any>>().not.toBeNever()
  })
  test('DEFAULT_MUTATION_CONCURRENCY', () => {
    expectTypeOf<typeof DEFAULT_MUTATION_CONCURRENCY>().not.toBeNever()
  })
  test('defineMigration', () => {
    expectTypeOf<typeof defineMigration>().toBeFunction()
  })
  test('del', () => {
    expectTypeOf<typeof del>().not.toBeNever()
  })
  test('delay', () => {
    expectTypeOf<typeof delay>().toBeFunction()
  })
  test('delete_', () => {
    expectTypeOf<typeof delete_>().toBeFunction()
  })
  test('DeleteMutation', () => {
    expectTypeOf<DeleteMutation>().not.toBeNever()
  })
  test('diffMatchPatch', () => {
    expectTypeOf<typeof diffMatchPatch>().not.toBeNever()
  })
  test('DiffMatchPatchOp', () => {
    expectTypeOf<DiffMatchPatchOp>().not.toBeNever()
  })
  test('DocumentMigrationReturnValue', () => {
    expectTypeOf<DocumentMigrationReturnValue>().not.toBeNever()
  })
  test('dryRun', () => {
    expectTypeOf<typeof dryRun>().toBeFunction()
  })
  test('ExportAPIConfig', () => {
    expectTypeOf<ExportAPIConfig>().toBeObject()
  })
  test('filter', () => {
    expectTypeOf<typeof filter>().toBeFunction()
  })
  test('fromDocuments', () => {
    expectTypeOf<typeof fromDocuments>().toBeFunction()
  })
  test('fromExportArchive', () => {
    expectTypeOf<typeof fromExportArchive>().toBeFunction()
  })
  test('fromExportEndpoint', () => {
    expectTypeOf<typeof fromExportEndpoint>().toBeFunction()
  })
  test('inc', () => {
    expectTypeOf<typeof inc>().not.toBeNever()
  })
  test('IncOp', () => {
    expectTypeOf<IncOp<any>>().not.toBeNever()
  })
  test('IndexedSegment', () => {
    expectTypeOf<IndexedSegment>().not.toBeNever()
  })
  test('insert', () => {
    expectTypeOf<typeof insert>().toBeFunction()
  })
  test('insertAfter', () => {
    expectTypeOf<typeof insertAfter>().not.toBeNever()
  })
  test('insertBefore', () => {
    expectTypeOf<typeof insertBefore>().toBeFunction()
  })
  test('InsertOp', () => {
    expectTypeOf<InsertOp<any, any, any>>().not.toBeNever()
  })
  test('JsonArray', () => {
    expectTypeOf<JsonArray>().not.toBeNever()
  })
  test('JsonObject', () => {
    expectTypeOf<JsonObject>().not.toBeNever()
  })
  test('JSONOptions', () => {
    expectTypeOf<JSONOptions<any>>().toBeObject()
  })
  test('JSONParser', () => {
    expectTypeOf<JSONParser<any>>().not.toBeNever()
  })
  test('JsonPrimitive', () => {
    expectTypeOf<JsonPrimitive>().not.toBeNever()
  })
  test('JsonValue', () => {
    expectTypeOf<JsonValue>().not.toBeNever()
  })
  test('KeyedSegment', () => {
    expectTypeOf<KeyedSegment>().not.toBeNever()
  })
  test('map', () => {
    expectTypeOf<typeof map>().toBeFunction()
  })
  test('MAX_MUTATION_CONCURRENCY', () => {
    expectTypeOf<typeof MAX_MUTATION_CONCURRENCY>().not.toBeNever()
  })
  test('MigrateDefinition', () => {
    expectTypeOf<MigrateDefinition>().not.toBeNever()
  })
  test('Migration', () => {
    expectTypeOf<Migration<any>>().toBeObject()
  })
  test('MigrationContext', () => {
    expectTypeOf<MigrationContext>().toBeObject()
  })
  test('MigrationProgress', () => {
    expectTypeOf<MigrationProgress>().not.toBeNever()
  })
  test('MigrationRunnerConfig', () => {
    expectTypeOf<MigrationRunnerConfig>().toBeObject()
  })
  test('Mutation', () => {
    expectTypeOf<Mutation<any>>().not.toBeNever()
  })
  test('NodeMigration', () => {
    expectTypeOf<NodeMigration>().toBeObject()
  })
  test('NodeMigrationReturnValue', () => {
    expectTypeOf<NodeMigrationReturnValue>().not.toBeNever()
  })
  test('NodePatch', () => {
    expectTypeOf<NodePatch<any, any>>().not.toBeNever()
  })
  test('NodePatchList', () => {
    expectTypeOf<NodePatchList>().not.toBeNever()
  })
  test('NumberOp', () => {
    expectTypeOf<NumberOp>().not.toBeNever()
  })
  test('Operation', () => {
    expectTypeOf<Operation>().not.toBeNever()
  })
  test('parse', () => {
    expectTypeOf<typeof parse>().toBeFunction()
  })
  test('parseJSON', () => {
    expectTypeOf<typeof parseJSON>().toBeFunction()
  })
  test('patch', () => {
    expectTypeOf<typeof patch>().toBeFunction()
  })
  test('PatchMutation', () => {
    expectTypeOf<PatchMutation<any>>().not.toBeNever()
  })
  test('PatchOptions', () => {
    expectTypeOf<PatchOptions>().not.toBeNever()
  })
  test('Path', () => {
    expectTypeOf<Path>().not.toBeNever()
  })
  test('prepend', () => {
    expectTypeOf<typeof prepend>().toBeFunction()
  })
  test('PrimitiveOp', () => {
    expectTypeOf<PrimitiveOp>().not.toBeNever()
  })
  test('RelativePosition', () => {
    expectTypeOf<RelativePosition>().not.toBeNever()
  })
  test('replace', () => {
    expectTypeOf<typeof replace>().toBeFunction()
  })
  test('ReplaceOp', () => {
    expectTypeOf<ReplaceOp<any, any>>().not.toBeNever()
  })
  test('run', () => {
    expectTypeOf<typeof run>().toBeFunction()
  })
  test('safeJsonParser', () => {
    expectTypeOf<typeof safeJsonParser>().not.toBeNever()
  })
  test('SanityDocument', () => {
    expectTypeOf<SanityDocument>().not.toBeNever()
  })
  test('set', () => {
    expectTypeOf<typeof set>().not.toBeNever()
  })
  test('setIfMissing', () => {
    expectTypeOf<typeof setIfMissing>().not.toBeNever()
  })
  test('SetIfMissingOp', () => {
    expectTypeOf<SetIfMissingOp<any>>().not.toBeNever()
  })
  test('SetOp', () => {
    expectTypeOf<SetOp<any>>().not.toBeNever()
  })
  test('split', () => {
    expectTypeOf<typeof split>().toBeFunction()
  })
  test('stringify', () => {
    expectTypeOf<typeof stringify>().toBeFunction()
  })
  test('stringifyJSON', () => {
    expectTypeOf<typeof stringifyJSON>().toBeFunction()
  })
  test('StringOp', () => {
    expectTypeOf<StringOp>().not.toBeNever()
  })
  test('take', () => {
    expectTypeOf<typeof take>().toBeFunction()
  })
  test('toArray', () => {
    expectTypeOf<typeof toArray>().toBeFunction()
  })
  test('toFetchOptionsIterable', () => {
    expectTypeOf<typeof toFetchOptionsIterable>().toBeFunction()
  })
  test('transaction', () => {
    // This export has 2 declarations, run `TEST_DTS_EXPORTS_DIAGNOSTICS=duplicates pnpm generate:dts-exports` to see where each declaration is coming from
    expectTypeOf<typeof transaction>().toBeFunction()
  })
  test('Transaction', () => {
    expectTypeOf<Transaction>().toBeObject()
  })
  test('truncate', () => {
    expectTypeOf<typeof truncate>().toBeFunction()
  })
  test('TruncateOp', () => {
    expectTypeOf<TruncateOp>().not.toBeNever()
  })
  test('unset', () => {
    expectTypeOf<typeof unset>().not.toBeNever()
  })
  test('UnsetOp', () => {
    expectTypeOf<UnsetOp>().not.toBeNever()
  })
})
