// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import type {
  RelativeTimeOptions,
  StudioLocaleResourceKeys,
  Translate,
  TranslateComponentMap,
  TranslationProps,
  useCurrentLocale,
  useDateTimeFormat,
  UseDateTimeFormatOptions,
  useRelativeTime,
  useTranslation,
  UseTranslationOptions,
  UseTranslationResponse,
} from 'sanity/_unstable-i18n'
import {describe, expectTypeOf, test} from 'vitest'

describe('sanity/_unstable-i18n', () => {
  test('RelativeTimeOptions', () => {
    expectTypeOf<RelativeTimeOptions>().toBeObject()
  })
  test('StudioLocaleResourceKeys', () => {
    expectTypeOf<StudioLocaleResourceKeys>().not.toBeNever()
  })
  test('Translate', () => {
    expectTypeOf<typeof Translate>().toBeFunction()
  })
  test('TranslateComponentMap', () => {
    expectTypeOf<TranslateComponentMap<any>>().not.toBeNever()
  })
  test('TranslationProps', () => {
    expectTypeOf<TranslationProps<any>>().toBeObject()
  })
  test('useCurrentLocale', () => {
    expectTypeOf<typeof useCurrentLocale>().toBeFunction()
  })
  test('useDateTimeFormat', () => {
    expectTypeOf<typeof useDateTimeFormat>().toBeFunction()
  })
  test('UseDateTimeFormatOptions', () => {
    expectTypeOf<UseDateTimeFormatOptions>().not.toBeNever()
  })
  test('useRelativeTime', () => {
    expectTypeOf<typeof useRelativeTime>().toBeFunction()
  })
  test('useTranslation', () => {
    expectTypeOf<typeof useTranslation>().toBeFunction()
  })
  test('UseTranslationOptions', () => {
    expectTypeOf<UseTranslationOptions<any>>().toBeObject()
  })
  test('UseTranslationResponse', () => {
    expectTypeOf<UseTranslationResponse<any, any>>().not.toBeNever()
  })
})
