// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import {describe, expectTypeOf, test} from 'vitest'
import type {cliProjectCommands} from 'sanity/_internal'

describe('sanity/_internal', () => {
  test('cliProjectCommands', () => {
    expectTypeOf<typeof cliProjectCommands>().not.toBeNever()
  })
})
