// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import {describe, expectTypeOf, test} from 'vitest'
import type {
  BackLinkProps,
  BaseGenericList,
  BaseIntentParams,
  BaseResolvedPaneNode,
  BaseView,
  BuildableComponent,
  BuildableGenericList,
  BuildableList,
  Builder,
  Child,
  ChildLinkProps,
  ChildObservable,
  ChildResolver,
  ChildResolverOptions,
  Collection,
  CollectionBuilder,
  component,
  Component,
  ComponentBuilder,
  ComponentInput,
  ComponentView,
  ComponentViewBuilder,
  ConfirmDeleteDialog,
  ConfirmDeleteDialogProps,
  createStructureBuilder,
  CustomComponentPaneNode,
  DEFAULT_INTENT_HANDLER,
  DefaultDocumentNodeContext,
  DefaultDocumentNodeResolver,
  defaultInitialValueTemplateItems,
  defaultIntentChecker,
  Divider,
  DocumentBuilder,
  DocumentFieldMenuActionNode,
  documentFromEditor,
  documentFromEditorWithInitialValue,
  DocumentInspectorHeader,
  DocumentList,
  DocumentListBuilder,
  DocumentListInput,
  DocumentListItem,
  DocumentListItemBuilder,
  DocumentListItemInput,
  DocumentListOptions,
  DocumentListPane,
  DocumentListPaneNode,
  DocumentListPaneProps,
  DocumentNode,
  DocumentOptions,
  DocumentPane,
  DocumentPaneNode,
  DocumentPaneProvider,
  DocumentPaneProviderProps,
  DocumentTypeListBuilder,
  DocumentTypeListInput,
  EditorNode,
  EditReferenceOptions,
  form,
  FormView,
  FormViewBuilder,
  GenericList,
  GenericListBuilder,
  GenericListInput,
  GenericViewBuilder,
  getOrderingMenuItem,
  getOrderingMenuItemsForSchemaType,
  getTypeNamesFromFilter,
  HELP_URL,
  InitialValueTemplateItemBuilder,
  Intent,
  IntentChecker,
  IntentJsonParams,
  IntentParams,
  isDocumentListItem,
  ItemChild,
  List,
  ListBuilder,
  ListDisplayOptions,
  ListInput,
  ListItem,
  ListItemBuilder,
  ListItemChild,
  ListItemDisplayOptions,
  ListItemInput,
  ListItemSerializeOptions,
  ListPaneNode,
  maybeSerializeInitialValueTemplateItem,
  maybeSerializeMenuItem,
  maybeSerializeMenuItemGroup,
  maybeSerializeView,
  MenuItem,
  MenuItemActionType,
  MenuItemBuilder,
  MenuItemGroup,
  MenuItemGroupBuilder,
  MenuItemParamsType,
  menuItemsFromInitialValueTemplateItems,
  Pane,
  PaneContent,
  PaneLayout,
  PaneListItem,
  PaneListItemDivider,
  PaneMenuItem,
  PaneMenuItemGroup,
  PaneNode,
  PaneNodeResolver,
  PaneRouterContext,
  PaneRouterContextValue,
  ParameterizedLinkProps,
  PartialDocumentList,
  PartialDocumentListItem,
  PartialDocumentNode,
  PartialListItem,
  PartialMenuItem,
  ReferenceChildLinkProps,
  RouterPaneGroup,
  RouterPanes,
  RouterPaneSibling,
  RouterPaneSiblingContext,
  Serializable,
  SerializablePaneNode,
  SerializeError,
  SerializeOptions,
  SerializePath,
  shallowIntentChecker,
  SortMenuItem,
  StrictVersionLayeringOptions,
  StructureBuilder,
  StructureBuilderOptions,
  StructureContext,
  structureLocaleNamespace,
  StructureLocaleResourceKeys,
  StructureNode,
  StructureResolver,
  StructureResolverContext,
  structureTool,
  StructureToolContextValue,
  StructureToolFeatures,
  StructureToolMenuItem,
  StructureToolOptions,
  StructureToolPaneActionHandler,
  StructureToolProvider,
  StructureToolProviderProps,
  UnresolvedPaneNode,
  UnserializedListItem,
  UnserializedListItemChild,
  useDocumentPane,
  useDocumentTitle,
  UseDocumentTitle,
  usePaneOptions,
  usePaneRouter,
  UserComponent,
  UserViewComponent,
  useStructureTool,
  View,
  ViewBuilder,
} from 'sanity/structure'

describe('sanity/structure', () => {
  test('BackLinkProps', () => {
    expectTypeOf<BackLinkProps>().toBeObject()
  })
  test('BaseGenericList', () => {
    expectTypeOf<BaseGenericList>().toBeObject()
  })
  test('BaseIntentParams', () => {
    expectTypeOf<BaseIntentParams>().toBeObject()
  })
  test('BaseResolvedPaneNode', () => {
    expectTypeOf<BaseResolvedPaneNode<any>>().toBeObject()
  })
  test('BaseView', () => {
    expectTypeOf<BaseView>().toBeObject()
  })
  test('BuildableComponent', () => {
    expectTypeOf<BuildableComponent>().toBeObject()
  })
  test('BuildableGenericList', () => {
    expectTypeOf<BuildableGenericList>().toBeObject()
  })
  test('BuildableList', () => {
    expectTypeOf<BuildableList>().toBeObject()
  })
  test('Builder', () => {
    expectTypeOf<Builder>().not.toBeNever()
  })
  test('Child', () => {
    expectTypeOf<Child>().not.toBeNever()
  })
  test('ChildLinkProps', () => {
    expectTypeOf<ChildLinkProps>().toBeObject()
  })
  test('ChildObservable', () => {
    expectTypeOf<ChildObservable>().toBeObject()
  })
  test('ChildResolver', () => {
    expectTypeOf<ChildResolver>().toBeObject()
  })
  test('ChildResolverOptions', () => {
    expectTypeOf<ChildResolverOptions>().toBeObject()
  })
  test('Collection', () => {
    expectTypeOf<Collection>().not.toBeNever()
  })
  test('CollectionBuilder', () => {
    expectTypeOf<CollectionBuilder>().not.toBeNever()
  })
  test('component', () => {
    expectTypeOf<typeof component>().not.toBeNever()
  })
  test('Component', () => {
    expectTypeOf<Component>().toBeObject()
  })
  test('ComponentBuilder', () => {
    expectTypeOf<ComponentBuilder>().not.toBeNever()
  })
  test('ComponentInput', () => {
    expectTypeOf<ComponentInput>().toBeObject()
  })
  test('ComponentView', () => {
    expectTypeOf<ComponentView<any>>().toBeObject()
  })
  test('ComponentViewBuilder', () => {
    expectTypeOf<ComponentViewBuilder>().not.toBeNever()
  })
  test('ConfirmDeleteDialog', () => {
    expectTypeOf<typeof ConfirmDeleteDialog>().toBeFunction()
  })
  test('ConfirmDeleteDialogProps', () => {
    expectTypeOf<ConfirmDeleteDialogProps>().toBeObject()
  })
  test('createStructureBuilder', () => {
    expectTypeOf<typeof createStructureBuilder>().toBeFunction()
  })
  test('CustomComponentPaneNode', () => {
    expectTypeOf<CustomComponentPaneNode>().toBeObject()
  })
  test('DEFAULT_INTENT_HANDLER', () => {
    expectTypeOf<typeof DEFAULT_INTENT_HANDLER>().not.toBeNever()
  })
  test('DefaultDocumentNodeContext', () => {
    expectTypeOf<DefaultDocumentNodeContext>().toBeObject()
  })
  test('DefaultDocumentNodeResolver', () => {
    expectTypeOf<DefaultDocumentNodeResolver>().not.toBeNever()
  })
  test('defaultInitialValueTemplateItems', () => {
    expectTypeOf<typeof defaultInitialValueTemplateItems>().toBeFunction()
  })
  test('defaultIntentChecker', () => {
    expectTypeOf<typeof defaultIntentChecker>().not.toBeNever()
  })
  test('Divider', () => {
    expectTypeOf<Divider>().toBeObject()
  })
  test('DocumentBuilder', () => {
    expectTypeOf<DocumentBuilder>().not.toBeNever()
  })
  test('DocumentFieldMenuActionNode', () => {
    expectTypeOf<DocumentFieldMenuActionNode>().not.toBeNever()
  })
  test('documentFromEditor', () => {
    expectTypeOf<typeof documentFromEditor>().toBeFunction()
  })
  test('documentFromEditorWithInitialValue', () => {
    expectTypeOf<typeof documentFromEditorWithInitialValue>().toBeFunction()
  })
  test('DocumentInspectorHeader', () => {
    expectTypeOf<typeof DocumentInspectorHeader>().toBeFunction()
  })
  test('DocumentList', () => {
    expectTypeOf<DocumentList>().toBeObject()
  })
  test('DocumentListBuilder', () => {
    expectTypeOf<DocumentListBuilder>().not.toBeNever()
  })
  test('DocumentListInput', () => {
    expectTypeOf<DocumentListInput>().toBeObject()
  })
  test('DocumentListItem', () => {
    expectTypeOf<DocumentListItem>().toBeObject()
  })
  test('DocumentListItemBuilder', () => {
    expectTypeOf<DocumentListItemBuilder>().not.toBeNever()
  })
  test('DocumentListItemInput', () => {
    expectTypeOf<DocumentListItemInput>().toBeObject()
  })
  test('DocumentListOptions', () => {
    expectTypeOf<DocumentListOptions>().toBeObject()
  })
  test('DocumentListPane', () => {
    expectTypeOf<typeof DocumentListPane>().not.toBeNever()
  })
  test('DocumentListPaneNode', () => {
    expectTypeOf<DocumentListPaneNode>().toBeObject()
  })
  test('DocumentListPaneProps', () => {
    expectTypeOf<DocumentListPaneProps>().not.toBeNever()
  })
  test('DocumentNode', () => {
    expectTypeOf<DocumentNode>().toBeObject()
  })
  test('DocumentOptions', () => {
    expectTypeOf<DocumentOptions>().toBeObject()
  })
  test('DocumentPane', () => {
    expectTypeOf<typeof DocumentPane>().not.toBeNever()
  })
  test('DocumentPaneNode', () => {
    expectTypeOf<DocumentPaneNode>().toBeObject()
  })
  test('DocumentPaneProvider', () => {
    expectTypeOf<typeof DocumentPaneProvider>().not.toBeNever()
  })
  test('DocumentPaneProviderProps', () => {
    expectTypeOf<DocumentPaneProviderProps>().not.toBeNever()
  })
  test('DocumentTypeListBuilder', () => {
    expectTypeOf<DocumentTypeListBuilder>().not.toBeNever()
  })
  test('DocumentTypeListInput', () => {
    expectTypeOf<DocumentTypeListInput>().toBeObject()
  })
  test('EditorNode', () => {
    expectTypeOf<EditorNode>().toBeObject()
  })
  test('EditReferenceOptions', () => {
    expectTypeOf<EditReferenceOptions>().toBeObject()
  })
  test('form', () => {
    expectTypeOf<typeof form>().not.toBeNever()
  })
  test('FormView', () => {
    expectTypeOf<FormView>().toBeObject()
  })
  test('FormViewBuilder', () => {
    expectTypeOf<FormViewBuilder>().not.toBeNever()
  })
  test('GenericList', () => {
    expectTypeOf<GenericList>().toBeObject()
  })
  test('GenericListBuilder', () => {
    expectTypeOf<GenericListBuilder<any, any>>().not.toBeNever()
  })
  test('GenericListInput', () => {
    expectTypeOf<GenericListInput>().toBeObject()
  })
  test('GenericViewBuilder', () => {
    expectTypeOf<GenericViewBuilder<any, any>>().not.toBeNever()
  })
  test('getOrderingMenuItem', () => {
    expectTypeOf<typeof getOrderingMenuItem>().toBeFunction()
  })
  test('getOrderingMenuItemsForSchemaType', () => {
    expectTypeOf<typeof getOrderingMenuItemsForSchemaType>().toBeFunction()
  })
  test('getTypeNamesFromFilter', () => {
    expectTypeOf<typeof getTypeNamesFromFilter>().toBeFunction()
  })
  test('HELP_URL', () => {
    expectTypeOf<typeof HELP_URL>().not.toBeNever()
  })
  test('InitialValueTemplateItemBuilder', () => {
    expectTypeOf<InitialValueTemplateItemBuilder>().not.toBeNever()
  })
  test('Intent', () => {
    expectTypeOf<Intent>().toBeObject()
  })
  test('IntentChecker', () => {
    expectTypeOf<IntentChecker>().toBeObject()
  })
  test('IntentJsonParams', () => {
    expectTypeOf<IntentJsonParams>().not.toBeNever()
  })
  test('IntentParams', () => {
    expectTypeOf<IntentParams>().not.toBeNever()
  })
  test('isDocumentListItem', () => {
    expectTypeOf<typeof isDocumentListItem>().toBeFunction()
  })
  test('ItemChild', () => {
    expectTypeOf<ItemChild>().not.toBeNever()
  })
  test('List', () => {
    expectTypeOf<List>().toBeObject()
  })
  test('ListBuilder', () => {
    expectTypeOf<ListBuilder>().not.toBeNever()
  })
  test('ListDisplayOptions', () => {
    expectTypeOf<ListDisplayOptions>().toBeObject()
  })
  test('ListInput', () => {
    expectTypeOf<ListInput>().toBeObject()
  })
  test('ListItem', () => {
    expectTypeOf<ListItem>().toBeObject()
  })
  test('ListItemBuilder', () => {
    expectTypeOf<ListItemBuilder>().not.toBeNever()
  })
  test('ListItemChild', () => {
    expectTypeOf<ListItemChild>().not.toBeNever()
  })
  test('ListItemDisplayOptions', () => {
    expectTypeOf<ListItemDisplayOptions>().toBeObject()
  })
  test('ListItemInput', () => {
    expectTypeOf<ListItemInput>().toBeObject()
  })
  test('ListItemSerializeOptions', () => {
    expectTypeOf<ListItemSerializeOptions>().toBeObject()
  })
  test('ListPaneNode', () => {
    expectTypeOf<ListPaneNode>().toBeObject()
  })
  test('maybeSerializeInitialValueTemplateItem', () => {
    expectTypeOf<typeof maybeSerializeInitialValueTemplateItem>().toBeFunction()
  })
  test('maybeSerializeMenuItem', () => {
    expectTypeOf<typeof maybeSerializeMenuItem>().toBeFunction()
  })
  test('maybeSerializeMenuItemGroup', () => {
    expectTypeOf<typeof maybeSerializeMenuItemGroup>().toBeFunction()
  })
  test('maybeSerializeView', () => {
    expectTypeOf<typeof maybeSerializeView>().toBeFunction()
  })
  test('MenuItem', () => {
    expectTypeOf<MenuItem>().toBeObject()
  })
  test('MenuItemActionType', () => {
    expectTypeOf<MenuItemActionType>().not.toBeNever()
  })
  test('MenuItemBuilder', () => {
    expectTypeOf<MenuItemBuilder>().not.toBeNever()
  })
  test('MenuItemGroup', () => {
    expectTypeOf<MenuItemGroup>().toBeObject()
  })
  test('MenuItemGroupBuilder', () => {
    expectTypeOf<MenuItemGroupBuilder>().not.toBeNever()
  })
  test('MenuItemParamsType', () => {
    expectTypeOf<MenuItemParamsType>().not.toBeNever()
  })
  test('menuItemsFromInitialValueTemplateItems', () => {
    expectTypeOf<typeof menuItemsFromInitialValueTemplateItems>().toBeFunction()
  })
  test('Pane', () => {
    expectTypeOf<typeof Pane>().not.toBeNever()
  })
  test('PaneContent', () => {
    expectTypeOf<typeof PaneContent>().not.toBeNever()
  })
  test('PaneLayout', () => {
    expectTypeOf<typeof PaneLayout>().toBeFunction()
  })
  test('PaneListItem', () => {
    expectTypeOf<PaneListItem<any>>().toBeObject()
  })
  test('PaneListItemDivider', () => {
    expectTypeOf<PaneListItemDivider>().toBeObject()
  })
  test('PaneMenuItem', () => {
    expectTypeOf<PaneMenuItem>().toBeObject()
  })
  test('PaneMenuItemGroup', () => {
    expectTypeOf<PaneMenuItemGroup>().toBeObject()
  })
  test('PaneNode', () => {
    expectTypeOf<PaneNode>().not.toBeNever()
  })
  test('PaneNodeResolver', () => {
    expectTypeOf<PaneNodeResolver>().not.toBeNever()
  })
  test('PaneRouterContext', () => {
    expectTypeOf<typeof PaneRouterContext>().not.toBeNever()
  })
  test('PaneRouterContextValue', () => {
    expectTypeOf<PaneRouterContextValue>().toBeObject()
  })
  test('ParameterizedLinkProps', () => {
    expectTypeOf<ParameterizedLinkProps>().toBeObject()
  })
  test('PartialDocumentList', () => {
    expectTypeOf<PartialDocumentList>().toBeObject()
  })
  test('PartialDocumentListItem', () => {
    expectTypeOf<PartialDocumentListItem>().not.toBeNever()
  })
  test('PartialDocumentNode', () => {
    expectTypeOf<PartialDocumentNode>().toBeObject()
  })
  test('PartialListItem', () => {
    expectTypeOf<PartialListItem>().not.toBeNever()
  })
  test('PartialMenuItem', () => {
    expectTypeOf<PartialMenuItem>().not.toBeNever()
  })
  test('ReferenceChildLinkProps', () => {
    expectTypeOf<ReferenceChildLinkProps>().toBeObject()
  })
  test('RouterPaneGroup', () => {
    expectTypeOf<RouterPaneGroup>().not.toBeNever()
  })
  test('RouterPanes', () => {
    expectTypeOf<RouterPanes>().not.toBeNever()
  })
  test('RouterPaneSibling', () => {
    expectTypeOf<RouterPaneSibling>().toBeObject()
  })
  test('RouterPaneSiblingContext', () => {
    expectTypeOf<RouterPaneSiblingContext>().toBeObject()
  })
  test('Serializable', () => {
    expectTypeOf<Serializable<any>>().toBeObject()
  })
  test('SerializablePaneNode', () => {
    expectTypeOf<SerializablePaneNode>().not.toBeNever()
  })
  test('SerializeError', () => {
    expectTypeOf<SerializeError>().not.toBeNever()
  })
  test('SerializeOptions', () => {
    expectTypeOf<SerializeOptions>().toBeObject()
  })
  test('SerializePath', () => {
    expectTypeOf<SerializePath>().not.toBeNever()
  })
  test('shallowIntentChecker', () => {
    expectTypeOf<typeof shallowIntentChecker>().not.toBeNever()
  })
  test('SortMenuItem', () => {
    expectTypeOf<SortMenuItem>().toBeObject()
  })
  test('StrictVersionLayeringOptions', () => {
    expectTypeOf<StrictVersionLayeringOptions>().toBeObject()
  })
  test('StructureBuilder', () => {
    expectTypeOf<StructureBuilder>().toBeObject()
  })
  test('StructureBuilderOptions', () => {
    expectTypeOf<StructureBuilderOptions>().toBeObject()
  })
  test('StructureContext', () => {
    expectTypeOf<StructureContext>().toBeObject()
  })
  test('structureLocaleNamespace', () => {
    expectTypeOf<typeof structureLocaleNamespace>().not.toBeNever()
  })
  test('StructureLocaleResourceKeys', () => {
    expectTypeOf<StructureLocaleResourceKeys>().not.toBeNever()
  })
  test('StructureNode', () => {
    expectTypeOf<StructureNode>().toBeObject()
  })
  test('StructureResolver', () => {
    expectTypeOf<StructureResolver>().not.toBeNever()
  })
  test('StructureResolverContext', () => {
    expectTypeOf<StructureResolverContext>().toBeObject()
  })
  test('structureTool', () => {
    expectTypeOf<typeof structureTool>().not.toBeNever()
  })
  test('StructureToolContextValue', () => {
    expectTypeOf<StructureToolContextValue>().toBeObject()
  })
  test('StructureToolFeatures', () => {
    expectTypeOf<StructureToolFeatures>().toBeObject()
  })
  test('StructureToolMenuItem', () => {
    expectTypeOf<StructureToolMenuItem>().toBeObject()
  })
  test('StructureToolOptions', () => {
    expectTypeOf<StructureToolOptions>().toBeObject()
  })
  test('StructureToolPaneActionHandler', () => {
    expectTypeOf<StructureToolPaneActionHandler>().not.toBeNever()
  })
  test('StructureToolProvider', () => {
    expectTypeOf<typeof StructureToolProvider>().toBeFunction()
  })
  test('StructureToolProviderProps', () => {
    expectTypeOf<StructureToolProviderProps>().toBeObject()
  })
  test('UnresolvedPaneNode', () => {
    expectTypeOf<UnresolvedPaneNode>().not.toBeNever()
  })
  test('UnserializedListItem', () => {
    expectTypeOf<UnserializedListItem>().toBeObject()
  })
  test('UnserializedListItemChild', () => {
    expectTypeOf<UnserializedListItemChild>().not.toBeNever()
  })
  test('useDocumentPane', () => {
    expectTypeOf<typeof useDocumentPane>().toBeFunction()
  })
  test('useDocumentTitle', () => {
    expectTypeOf<typeof useDocumentTitle>().toBeFunction()
  })
  test('UseDocumentTitle', () => {
    expectTypeOf<UseDocumentTitle>().toBeObject()
  })
  test('usePaneOptions', () => {
    expectTypeOf<typeof usePaneOptions>().toBeFunction()
  })
  test('usePaneRouter', () => {
    expectTypeOf<typeof usePaneRouter>().toBeFunction()
  })
  test('UserComponent', () => {
    expectTypeOf<UserComponent>().not.toBeNever()
  })
  test('UserViewComponent', () => {
    expectTypeOf<UserViewComponent<any>>().not.toBeNever()
  })
  test('useStructureTool', () => {
    expectTypeOf<typeof useStructureTool>().toBeFunction()
  })
  test('View', () => {
    expectTypeOf<View>().not.toBeNever()
  })
  test('ViewBuilder', () => {
    expectTypeOf<ViewBuilder>().not.toBeNever()
  })
})
