// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import type {
  BackLinkProps,
  BaseGenericList,
  BaseIntentParams,
  BaseView,
  BuildableComponent,
  BuildableGenericList,
  BuildableList,
  Child,
  ChildLinkProps,
  ChildObservable,
  ChildResolver,
  ChildResolverOptions,
  Collection,
  CollectionBuilder,
  Component,
  ComponentBuilder,
  ComponentInput,
  ComponentView,
  ComponentViewBuilder,
  DefaultDocumentNodeContext,
  DefaultDocumentNodeResolver,
  defineIncomingReferenceDecoration,
  Divider,
  DocumentBuilder,
  DocumentFieldMenuActionNode,
  DocumentInspectorHeader,
  DocumentList,
  DocumentListBuilder,
  DocumentListInput,
  DocumentListItem,
  DocumentListItemBuilder,
  DocumentListItemInput,
  DocumentListOptions,
  DocumentNode,
  DocumentOptions,
  DocumentPaneProvider,
  DocumentTypeListBuilder,
  DocumentTypeListInput,
  EditorNode,
  EditReferenceOptions,
  FormView,
  FormViewBuilder,
  GenericList,
  GenericListBuilder,
  GenericListInput,
  GenericViewBuilder,
  IncomingReferenceAction,
  IncomingReferencesOptions,
  InitialValueTemplateItemBuilder,
  Intent,
  IntentChecker,
  IntentJsonParams,
  IntentParams,
  isIncomingReferenceCreation,
  ItemChild,
  KnownMenuItemParams,
  List,
  ListBuilder,
  ListDisplayOptions,
  ListInput,
  ListItem,
  ListItemBuilder,
  ListItemChild,
  ListItemDisplayOptions,
  ListItemInput,
  ListItemSerializeOptions,
  MenuItem,
  MenuItemActionType,
  MenuItemBuilder,
  MenuItemGroup,
  MenuItemGroupBuilder,
  MenuItemParamsType,
  PaneLayout,
  PaneRouterContext,
  PaneRouterContextValue,
  ParameterizedLinkProps,
  PartialDocumentList,
  PartialDocumentListItem,
  PartialDocumentNode,
  PartialListItem,
  PartialMenuItem,
  ReferenceChildLinkProps,
  RouterPaneGroup,
  RouterPanes,
  RouterPaneSibling,
  Serializable,
  SerializeOptions,
  SerializePath,
  StructureBuilder,
  StructureContext,
  structureLocaleNamespace,
  StructureLocaleResourceKeys,
  StructureNode,
  StructureResolver,
  StructureResolverContext,
  structureTool,
  StructureToolMenuItem,
  StructureToolOptions,
  UnserializedListItem,
  UnserializedListItemChild,
  useDocumentPane,
  useDocumentTitle,
  UseDocumentTitle,
  usePaneRouter,
  UserComponent,
  UserViewComponent,
  View,
  ViewBuilder,
} from 'sanity/structure'
import {describe, expectTypeOf, test} from 'vitest'

describe('sanity/structure', () => {
  test('BackLinkProps', () => {
    expectTypeOf<BackLinkProps>().toBeObject()
  })
  test('BaseGenericList', () => {
    expectTypeOf<BaseGenericList>().toBeObject()
  })
  test('BaseIntentParams', () => {
    expectTypeOf<BaseIntentParams>().toBeObject()
  })
  test('BaseView', () => {
    expectTypeOf<BaseView>().toBeObject()
  })
  test('BuildableComponent', () => {
    expectTypeOf<BuildableComponent>().toBeObject()
  })
  test('BuildableGenericList', () => {
    expectTypeOf<BuildableGenericList>().toBeObject()
  })
  test('BuildableList', () => {
    expectTypeOf<BuildableList>().toBeObject()
  })
  test('Child', () => {
    expectTypeOf<Child>().not.toBeNever()
  })
  test('ChildLinkProps', () => {
    expectTypeOf<ChildLinkProps>().toBeObject()
  })
  test('ChildObservable', () => {
    expectTypeOf<ChildObservable>().toBeObject()
  })
  test('ChildResolver', () => {
    expectTypeOf<ChildResolver>().toBeObject()
  })
  test('ChildResolverOptions', () => {
    expectTypeOf<ChildResolverOptions>().toBeObject()
  })
  test('Collection', () => {
    expectTypeOf<Collection>().not.toBeNever()
  })
  test('CollectionBuilder', () => {
    expectTypeOf<CollectionBuilder>().not.toBeNever()
  })
  test('Component', () => {
    expectTypeOf<Component>().toBeObject()
  })
  test('ComponentBuilder', () => {
    expectTypeOf<ComponentBuilder>().not.toBeNever()
  })
  test('ComponentInput', () => {
    expectTypeOf<ComponentInput>().toBeObject()
  })
  test('ComponentView', () => {
    expectTypeOf<ComponentView<any>>().toBeObject()
  })
  test('ComponentViewBuilder', () => {
    expectTypeOf<ComponentViewBuilder>().not.toBeNever()
  })
  test('DefaultDocumentNodeContext', () => {
    expectTypeOf<DefaultDocumentNodeContext>().toBeObject()
  })
  test('DefaultDocumentNodeResolver', () => {
    expectTypeOf<DefaultDocumentNodeResolver>().not.toBeNever()
  })
  test('defineIncomingReferenceDecoration', () => {
    expectTypeOf<typeof defineIncomingReferenceDecoration>().toBeFunction()
  })
  test('Divider', () => {
    expectTypeOf<Divider>().toBeObject()
  })
  test('DocumentBuilder', () => {
    expectTypeOf<DocumentBuilder>().not.toBeNever()
  })
  test('DocumentFieldMenuActionNode', () => {
    expectTypeOf<DocumentFieldMenuActionNode>().not.toBeNever()
  })
  test('DocumentInspectorHeader', () => {
    expectTypeOf<typeof DocumentInspectorHeader>().toBeFunction()
  })
  test('DocumentList', () => {
    expectTypeOf<DocumentList>().toBeObject()
  })
  test('DocumentListBuilder', () => {
    expectTypeOf<DocumentListBuilder>().not.toBeNever()
  })
  test('DocumentListInput', () => {
    expectTypeOf<DocumentListInput>().toBeObject()
  })
  test('DocumentListItem', () => {
    expectTypeOf<DocumentListItem>().toBeObject()
  })
  test('DocumentListItemBuilder', () => {
    expectTypeOf<DocumentListItemBuilder>().not.toBeNever()
  })
  test('DocumentListItemInput', () => {
    expectTypeOf<DocumentListItemInput>().toBeObject()
  })
  test('DocumentListOptions', () => {
    expectTypeOf<DocumentListOptions>().toBeObject()
  })
  test('DocumentNode', () => {
    expectTypeOf<DocumentNode>().toBeObject()
  })
  test('DocumentOptions', () => {
    expectTypeOf<DocumentOptions>().toBeObject()
  })
  test('DocumentPaneProvider', () => {
    expectTypeOf<typeof DocumentPaneProvider>().not.toBeNever()
  })
  test('DocumentTypeListBuilder', () => {
    expectTypeOf<DocumentTypeListBuilder>().not.toBeNever()
  })
  test('DocumentTypeListInput', () => {
    expectTypeOf<DocumentTypeListInput>().toBeObject()
  })
  test('EditorNode', () => {
    expectTypeOf<EditorNode>().toBeObject()
  })
  test('EditReferenceOptions', () => {
    expectTypeOf<EditReferenceOptions>().toBeObject()
  })
  test('FormView', () => {
    expectTypeOf<FormView>().toBeObject()
  })
  test('FormViewBuilder', () => {
    expectTypeOf<FormViewBuilder>().not.toBeNever()
  })
  test('GenericList', () => {
    expectTypeOf<GenericList>().toBeObject()
  })
  test('GenericListBuilder', () => {
    expectTypeOf<GenericListBuilder<any, any>>().not.toBeNever()
  })
  test('GenericListInput', () => {
    expectTypeOf<GenericListInput>().toBeObject()
  })
  test('GenericViewBuilder', () => {
    expectTypeOf<GenericViewBuilder<any, any>>().not.toBeNever()
  })
  test('IncomingReferenceAction', () => {
    expectTypeOf<IncomingReferenceAction>().not.toBeNever()
  })
  test('IncomingReferencesOptions', () => {
    expectTypeOf<IncomingReferencesOptions>().not.toBeNever()
  })
  test('InitialValueTemplateItemBuilder', () => {
    expectTypeOf<InitialValueTemplateItemBuilder>().not.toBeNever()
  })
  test('Intent', () => {
    expectTypeOf<Intent>().toBeObject()
  })
  test('IntentChecker', () => {
    expectTypeOf<IntentChecker>().toBeObject()
  })
  test('IntentJsonParams', () => {
    expectTypeOf<IntentJsonParams>().not.toBeNever()
  })
  test('IntentParams', () => {
    expectTypeOf<IntentParams>().not.toBeNever()
  })
  test('isIncomingReferenceCreation', () => {
    expectTypeOf<typeof isIncomingReferenceCreation>().toBeFunction()
  })
  test('ItemChild', () => {
    expectTypeOf<ItemChild>().not.toBeNever()
  })
  test('KnownMenuItemParams', () => {
    expectTypeOf<KnownMenuItemParams>().toBeObject()
  })
  test('List', () => {
    expectTypeOf<List>().toBeObject()
  })
  test('ListBuilder', () => {
    expectTypeOf<ListBuilder>().not.toBeNever()
  })
  test('ListDisplayOptions', () => {
    expectTypeOf<ListDisplayOptions>().toBeObject()
  })
  test('ListInput', () => {
    expectTypeOf<ListInput>().toBeObject()
  })
  test('ListItem', () => {
    expectTypeOf<ListItem>().toBeObject()
  })
  test('ListItemBuilder', () => {
    expectTypeOf<ListItemBuilder>().not.toBeNever()
  })
  test('ListItemChild', () => {
    expectTypeOf<ListItemChild>().not.toBeNever()
  })
  test('ListItemDisplayOptions', () => {
    expectTypeOf<ListItemDisplayOptions>().toBeObject()
  })
  test('ListItemInput', () => {
    expectTypeOf<ListItemInput>().toBeObject()
  })
  test('ListItemSerializeOptions', () => {
    expectTypeOf<ListItemSerializeOptions>().toBeObject()
  })
  test('MenuItem', () => {
    expectTypeOf<MenuItem>().toBeObject()
  })
  test('MenuItemActionType', () => {
    expectTypeOf<MenuItemActionType>().not.toBeNever()
  })
  test('MenuItemBuilder', () => {
    expectTypeOf<MenuItemBuilder>().not.toBeNever()
  })
  test('MenuItemGroup', () => {
    expectTypeOf<MenuItemGroup>().toBeObject()
  })
  test('MenuItemGroupBuilder', () => {
    expectTypeOf<MenuItemGroupBuilder>().not.toBeNever()
  })
  test('MenuItemParamsType', () => {
    expectTypeOf<MenuItemParamsType>().not.toBeNever()
  })
  test('PaneLayout', () => {
    expectTypeOf<typeof PaneLayout>().toBeFunction()
  })
  test('PaneRouterContext', () => {
    expectTypeOf<typeof PaneRouterContext>().not.toBeNever()
  })
  test('PaneRouterContextValue', () => {
    expectTypeOf<PaneRouterContextValue>().toBeObject()
  })
  test('ParameterizedLinkProps', () => {
    expectTypeOf<ParameterizedLinkProps>().toBeObject()
  })
  test('PartialDocumentList', () => {
    expectTypeOf<PartialDocumentList>().toBeObject()
  })
  test('PartialDocumentListItem', () => {
    expectTypeOf<PartialDocumentListItem>().not.toBeNever()
  })
  test('PartialDocumentNode', () => {
    expectTypeOf<PartialDocumentNode>().toBeObject()
  })
  test('PartialListItem', () => {
    expectTypeOf<PartialListItem>().not.toBeNever()
  })
  test('PartialMenuItem', () => {
    expectTypeOf<PartialMenuItem>().not.toBeNever()
  })
  test('ReferenceChildLinkProps', () => {
    expectTypeOf<ReferenceChildLinkProps>().toBeObject()
  })
  test('RouterPaneGroup', () => {
    expectTypeOf<RouterPaneGroup>().not.toBeNever()
  })
  test('RouterPanes', () => {
    expectTypeOf<RouterPanes>().not.toBeNever()
  })
  test('RouterPaneSibling', () => {
    expectTypeOf<RouterPaneSibling>().toBeObject()
  })
  test('Serializable', () => {
    expectTypeOf<Serializable<any>>().toBeObject()
  })
  test('SerializeOptions', () => {
    expectTypeOf<SerializeOptions>().toBeObject()
  })
  test('SerializePath', () => {
    expectTypeOf<SerializePath>().not.toBeNever()
  })
  test('StructureBuilder', () => {
    expectTypeOf<StructureBuilder>().toBeObject()
  })
  test('StructureContext', () => {
    expectTypeOf<StructureContext>().toBeObject()
  })
  test('structureLocaleNamespace', () => {
    expectTypeOf<typeof structureLocaleNamespace>().not.toBeNever()
  })
  test('StructureLocaleResourceKeys', () => {
    expectTypeOf<StructureLocaleResourceKeys>().not.toBeNever()
  })
  test('StructureNode', () => {
    expectTypeOf<StructureNode>().toBeObject()
  })
  test('StructureResolver', () => {
    expectTypeOf<StructureResolver>().not.toBeNever()
  })
  test('StructureResolverContext', () => {
    expectTypeOf<StructureResolverContext>().toBeObject()
  })
  test('structureTool', () => {
    expectTypeOf<typeof structureTool>().not.toBeNever()
  })
  test('StructureToolMenuItem', () => {
    expectTypeOf<StructureToolMenuItem>().toBeObject()
  })
  test('StructureToolOptions', () => {
    expectTypeOf<StructureToolOptions>().toBeObject()
  })
  test('UnserializedListItem', () => {
    expectTypeOf<UnserializedListItem>().toBeObject()
  })
  test('UnserializedListItemChild', () => {
    expectTypeOf<UnserializedListItemChild>().not.toBeNever()
  })
  test('useDocumentPane', () => {
    expectTypeOf<typeof useDocumentPane>().toBeFunction()
  })
  test('useDocumentTitle', () => {
    expectTypeOf<typeof useDocumentTitle>().toBeFunction()
  })
  test('UseDocumentTitle', () => {
    expectTypeOf<UseDocumentTitle>().toBeObject()
  })
  test('usePaneRouter', () => {
    expectTypeOf<typeof usePaneRouter>().toBeFunction()
  })
  test('UserComponent', () => {
    expectTypeOf<UserComponent>().not.toBeNever()
  })
  test('UserViewComponent', () => {
    expectTypeOf<UserViewComponent<any>>().not.toBeNever()
  })
  test('View', () => {
    expectTypeOf<View>().not.toBeNever()
  })
  test('ViewBuilder', () => {
    expectTypeOf<ViewBuilder>().not.toBeNever()
  })
})
