// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import {describe, expectTypeOf, test} from 'vitest'
import type {
  CliClientOptions,
  CliConfig,
  createCliConfig,
  defineCliConfig,
  getCliClient,
  getStudioEnvironmentVariables,
  StudioEnvVariablesOptions,
} from 'sanity/cli'

describe('sanity/cli', () => {
  test('CliClientOptions', () => {
    expectTypeOf<CliClientOptions>().toBeObject()
  })
  test('CliConfig', () => {
    expectTypeOf<CliConfig>().toBeObject()
  })
  test('createCliConfig', () => {
    expectTypeOf<typeof createCliConfig>().toBeFunction()
  })
  test('defineCliConfig', () => {
    expectTypeOf<typeof defineCliConfig>().toBeFunction()
  })
  test('getCliClient', () => {
    expectTypeOf<typeof getCliClient>().not.toBeNever()
  })
  test('getStudioEnvironmentVariables', () => {
    expectTypeOf<typeof getStudioEnvironmentVariables>().toBeFunction()
  })
  test('StudioEnvVariablesOptions', () => {
    expectTypeOf<StudioEnvVariablesOptions>().toBeObject()
  })
})
