// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import type {createContext} from 'sanity/_createContext'
import {describe, expectTypeOf, test} from 'vitest'

describe('sanity/_createContext', () => {
  test('createContext', () => {
    expectTypeOf<typeof createContext>().toBeFunction()
  })
})
