// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import type {
  ArrayDefinition,
  BaseFormNode,
  ChangeIndicatorsTracker,
  CopyPasteProvider,
  createPatchChannel,
  defaultLocale,
  defineArrayMember,
  defineField,
  defineType,
  DivergencesProvider,
  EMPTY_ARRAY,
  FieldDefinition,
  FieldMember,
  FieldPresence,
  FieldProps,
  FIXME,
  FormBuilder,
  FormDocumentValue,
  FormFieldHeaderText,
  FormInput,
  FormNodePresence,
  FormPatch,
  FormPatchJSONValue,
  FormSetIfMissingPatch,
  FormUnsetPatch,
  getExpandOperations,
  InputProps,
  isObjectSchemaType,
  ItemProps,
  LocaleProvider,
  LocaleResourceBundle,
  LocaleSource,
  Mutation,
  ObjectArrayFormNode,
  ObjectDefinition,
  ObjectField,
  ObjectFieldProps,
  ObjectInputProps,
  ObjectMember,
  ObjectSchemaType,
  PatchArg,
  PatchEvent,
  Path,
  pathToString,
  PerspectiveProvider,
  PreparedSnapshot,
  PresenceOverlay,
  ProjectData,
  ResourceCacheProvider,
  ScrollContainer,
  set,
  setAtPath,
  setIfMissing,
  Source,
  SourceClientOptions,
  SourceProvider,
  StateTree,
  StringInputProps,
  StudioLocaleResourceKeys,
  TransformPatches,
  Translate,
  unset,
  useCurrentLocale,
  useDateTimeFormat,
  useFormState,
  useRelativeTime,
  useSchema,
  useTranslation,
  useWorkspace,
  validateDocument,
  ValidationMarker,
  VirtualizerScrollInstanceProvider,
  Workspace,
  WorkspaceProvider,
} from 'sanity/_unstable-embedded'
import {describe, expectTypeOf, test} from 'vitest'

describe('sanity/_unstable-embedded', () => {
  test('ArrayDefinition', () => {
    // This export has 2 declarations, run `TEST_DTS_EXPORTS_DIAGNOSTICS=duplicates pnpm generate:dts-exports` to see where each declaration is coming from
    expectTypeOf<ArrayDefinition>().toBeObject()
  })
  test('BaseFormNode', () => {
    expectTypeOf<BaseFormNode<any, any>>().toBeObject()
  })
  test('ChangeIndicatorsTracker', () => {
    expectTypeOf<typeof ChangeIndicatorsTracker>().not.toBeNever()
  })
  test('CopyPasteProvider', () => {
    expectTypeOf<typeof CopyPasteProvider>().not.toBeNever()
  })
  test('createPatchChannel', () => {
    expectTypeOf<typeof createPatchChannel>().toBeFunction()
  })
  test('defaultLocale', () => {
    expectTypeOf<typeof defaultLocale>().not.toBeNever()
  })
  test('defineArrayMember', () => {
    expectTypeOf<typeof defineArrayMember>().toBeFunction()
  })
  test('defineField', () => {
    expectTypeOf<typeof defineField>().toBeFunction()
  })
  test('defineType', () => {
    expectTypeOf<typeof defineType>().toBeFunction()
  })
  test('DivergencesProvider', () => {
    expectTypeOf<typeof DivergencesProvider>().not.toBeNever()
  })
  test('EMPTY_ARRAY', () => {
    expectTypeOf<typeof EMPTY_ARRAY>().not.toBeNever()
  })
  test('FieldDefinition', () => {
    expectTypeOf<FieldDefinition<any, any>>().not.toBeNever()
  })
  test('FieldMember', () => {
    expectTypeOf<FieldMember<any>>().toBeObject()
  })
  test('FieldPresence', () => {
    expectTypeOf<typeof FieldPresence>().toBeFunction()
  })
  test('FieldProps', () => {
    expectTypeOf<FieldProps>().not.toBeNever()
  })
  test('FIXME', () => {
    expectTypeOf<FIXME>().not.toBeNever()
  })
  test('FormBuilder', () => {
    expectTypeOf<typeof FormBuilder>().toBeFunction()
  })
  test('FormDocumentValue', () => {
    expectTypeOf<FormDocumentValue>().toBeObject()
  })
  test('FormFieldHeaderText', () => {
    expectTypeOf<typeof FormFieldHeaderText>().not.toBeNever()
  })
  test('FormInput', () => {
    expectTypeOf<typeof FormInput>().not.toBeNever()
  })
  test('FormNodePresence', () => {
    expectTypeOf<FormNodePresence>().toBeObject()
  })
  test('FormPatch', () => {
    expectTypeOf<FormPatch>().not.toBeNever()
  })
  test('FormPatchJSONValue', () => {
    expectTypeOf<FormPatchJSONValue>().not.toBeNever()
  })
  test('FormSetIfMissingPatch', () => {
    expectTypeOf<FormSetIfMissingPatch>().toBeObject()
  })
  test('FormUnsetPatch', () => {
    expectTypeOf<FormUnsetPatch>().toBeObject()
  })
  test('getExpandOperations', () => {
    expectTypeOf<typeof getExpandOperations>().toBeFunction()
  })
  test('InputProps', () => {
    expectTypeOf<InputProps>().not.toBeNever()
  })
  test('isObjectSchemaType', () => {
    expectTypeOf<typeof isObjectSchemaType>().toBeFunction()
  })
  test('ItemProps', () => {
    expectTypeOf<ItemProps>().not.toBeNever()
  })
  test('LocaleProvider', () => {
    expectTypeOf<typeof LocaleProvider>().toBeFunction()
  })
  test('LocaleResourceBundle', () => {
    expectTypeOf<LocaleResourceBundle>().toBeObject()
  })
  test('LocaleSource', () => {
    expectTypeOf<LocaleSource>().toBeObject()
  })
  test('Mutation', () => {
    expectTypeOf<Mutation>().not.toBeNever()
  })
  test('ObjectArrayFormNode', () => {
    expectTypeOf<ObjectArrayFormNode<any, any>>().toBeObject()
  })
  test('ObjectDefinition', () => {
    // This export has 2 declarations, run `TEST_DTS_EXPORTS_DIAGNOSTICS=duplicates pnpm generate:dts-exports` to see where each declaration is coming from
    expectTypeOf<ObjectDefinition>().toBeObject()
  })
  test('ObjectField', () => {
    expectTypeOf<ObjectField<any>>().toBeObject()
  })
  test('ObjectFieldProps', () => {
    expectTypeOf<ObjectFieldProps<any>>().toBeObject()
  })
  test('ObjectInputProps', () => {
    expectTypeOf<ObjectInputProps<any, any>>().toBeObject()
  })
  test('ObjectMember', () => {
    expectTypeOf<ObjectMember>().not.toBeNever()
  })
  test('ObjectSchemaType', () => {
    expectTypeOf<ObjectSchemaType>().toBeObject()
  })
  test('PatchArg', () => {
    expectTypeOf<PatchArg>().not.toBeNever()
  })
  test('PatchEvent', () => {
    expectTypeOf<PatchEvent>().not.toBeNever()
  })
  test('Path', () => {
    expectTypeOf<Path>().not.toBeNever()
  })
  test('pathToString', () => {
    expectTypeOf<typeof pathToString>().toBeFunction()
  })
  test('PerspectiveProvider', () => {
    expectTypeOf<typeof PerspectiveProvider>().toBeFunction()
  })
  test('PreparedSnapshot', () => {
    expectTypeOf<PreparedSnapshot>().toBeObject()
  })
  test('PresenceOverlay', () => {
    expectTypeOf<typeof PresenceOverlay>().toBeFunction()
  })
  test('ProjectData', () => {
    expectTypeOf<ProjectData>().toBeObject()
  })
  test('ResourceCacheProvider', () => {
    expectTypeOf<typeof ResourceCacheProvider>().toBeFunction()
  })
  test('ScrollContainer', () => {
    expectTypeOf<typeof ScrollContainer>().not.toBeNever()
  })
  test('set', () => {
    expectTypeOf<typeof set>().toBeFunction()
  })
  test('setAtPath', () => {
    expectTypeOf<typeof setAtPath>().toBeFunction()
  })
  test('setIfMissing', () => {
    expectTypeOf<typeof setIfMissing>().toBeFunction()
  })
  test('Source', () => {
    expectTypeOf<Source>().toBeObject()
  })
  test('SourceClientOptions', () => {
    expectTypeOf<SourceClientOptions>().toBeObject()
  })
  test('SourceProvider', () => {
    expectTypeOf<typeof SourceProvider>().toBeFunction()
  })
  test('StateTree', () => {
    expectTypeOf<StateTree<any>>().toBeObject()
  })
  test('StringInputProps', () => {
    expectTypeOf<StringInputProps<any>>().toBeObject()
  })
  test('StudioLocaleResourceKeys', () => {
    expectTypeOf<StudioLocaleResourceKeys>().not.toBeNever()
  })
  test('TransformPatches', () => {
    expectTypeOf<typeof TransformPatches>().not.toBeNever()
  })
  test('Translate', () => {
    expectTypeOf<typeof Translate>().toBeFunction()
  })
  test('unset', () => {
    expectTypeOf<typeof unset>().toBeFunction()
  })
  test('useCurrentLocale', () => {
    expectTypeOf<typeof useCurrentLocale>().toBeFunction()
  })
  test('useDateTimeFormat', () => {
    expectTypeOf<typeof useDateTimeFormat>().toBeFunction()
  })
  test('useFormState', () => {
    expectTypeOf<typeof useFormState>().toBeFunction()
  })
  test('useRelativeTime', () => {
    expectTypeOf<typeof useRelativeTime>().toBeFunction()
  })
  test('useSchema', () => {
    expectTypeOf<typeof useSchema>().toBeFunction()
  })
  test('useTranslation', () => {
    expectTypeOf<typeof useTranslation>().toBeFunction()
  })
  test('useWorkspace', () => {
    expectTypeOf<typeof useWorkspace>().toBeFunction()
  })
  test('validateDocument', () => {
    expectTypeOf<typeof validateDocument>().toBeFunction()
  })
  test('ValidationMarker', () => {
    expectTypeOf<ValidationMarker>().toBeObject()
  })
  test('VirtualizerScrollInstanceProvider', () => {
    expectTypeOf<typeof VirtualizerScrollInstanceProvider>().toBeFunction()
  })
  test('Workspace', () => {
    expectTypeOf<Workspace>().toBeObject()
  })
  test('WorkspaceProvider', () => {
    expectTypeOf<typeof WorkspaceProvider>().toBeFunction()
  })
})
