// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import type {
  CliClientOptions,
  CliConfig,
  createCliConfig,
  DefineAppInput,
  defineCliConfig,
  DefineMediaLibraryInput,
  getCliClient,
  getStudioEnvironmentVariables,
  MediaLibraryField,
  StudioEnvVariablesOptions,
  unstable_defineApp,
  unstable_defineMediaLibrary,
} from 'sanity/cli'
import {describe, expectTypeOf, test} from 'vitest'

describe('sanity/cli', () => {
  test('CliClientOptions', () => {
    expectTypeOf<CliClientOptions>().toBeObject()
  })
  test('CliConfig', () => {
    expectTypeOf<CliConfig>().toBeObject()
  })
  test('createCliConfig', () => {
    expectTypeOf<typeof createCliConfig>().toBeFunction()
  })
  test('DefineAppInput', () => {
    expectTypeOf<DefineAppInput>().not.toBeNever()
  })
  test('defineCliConfig', () => {
    expectTypeOf<typeof defineCliConfig>().toBeFunction()
  })
  test('DefineMediaLibraryInput', () => {
    expectTypeOf<DefineMediaLibraryInput>().toBeObject()
  })
  test('getCliClient', () => {
    expectTypeOf<typeof getCliClient>().not.toBeNever()
  })
  test('getStudioEnvironmentVariables', () => {
    expectTypeOf<typeof getStudioEnvironmentVariables>().toBeFunction()
  })
  test('MediaLibraryField', () => {
    expectTypeOf<MediaLibraryField>().toBeObject()
  })
  test('StudioEnvVariablesOptions', () => {
    expectTypeOf<StudioEnvVariablesOptions>().toBeObject()
  })
  test('unstable_defineApp', () => {
    expectTypeOf<typeof unstable_defineApp>().toBeFunction()
  })
  test('unstable_defineMediaLibrary', () => {
    expectTypeOf<typeof unstable_defineMediaLibrary>().toBeFunction()
  })
})
