// Auto-generated by running `pnpm generate:dts-exports`
// If deleting the exports, for example, then please use this command to regenerate the tests
// If you need to investigate where new imports are coming from run `TEST_DTS_EXPORTS_DIAGNOSTICS=full pnpm generate:dts-exports`

import type {
  defineVideoField,
  VideoDefinition,
  VideoDefinition$1,
  VideoOptions,
  VideoRule,
  videoTypeName,
  VideoValue,
} from 'sanity/media-library'
import {describe, expectTypeOf, test} from 'vitest'

describe('sanity/media-library', () => {
  test('defineVideoField', () => {
    expectTypeOf<typeof defineVideoField>().toBeFunction()
  })
  test('VideoDefinition', () => {
    expectTypeOf<VideoDefinition>().toBeObject()
  })
  test('VideoDefinition$1', () => {
    expectTypeOf<VideoDefinition$1>().toBeObject()
  })
  test('VideoOptions', () => {
    expectTypeOf<VideoOptions>().toBeObject()
  })
  test('VideoRule', () => {
    expectTypeOf<VideoRule>().toBeObject()
  })
  test('videoTypeName', () => {
    expectTypeOf<typeof videoTypeName>().not.toBeNever()
  })
  test('VideoValue', () => {
    expectTypeOf<VideoValue>().toBeObject()
  })
})
