/**
 * Route patterns a Presentation `defineDocuments` config can contain, matched against the pathnames
 * studios would throw at them. The expected results were generated by running path-to-regexp v6
 * (for the v6 corpus) and v8 (for the v8 corpus) side by side as oracles, on both native URLPattern
 * and urlpattern-polyfill — see the SAPP-4118 spike this suite is ported from
 * (https://github.com/sanity-io/plugins/pull/1908). Pinning them here keeps the matcher honest
 * about full parity with the patterns studios already have in production.
 */
import {describe, expect, test} from 'vitest'

import {createRouteMatcher} from '../matchRoute'

if (typeof URLPattern === 'undefined') {
  await import('urlpattern-polyfill')
}

type ExpectedParams = Record<string, string | string[]> | undefined

interface CorpusEntry {
  pattern: string
  description: string
  /** Pathname → expected params, or undefined when the pathname should not match. */
  expected: Record<string, ExpectedParams>
}

/** Patterns written for path-to-regexp v6, i.e. what studios configured before the v8 bump. */
const V6_CORPUS: CorpusEntry[] = [
  {
    pattern: '/',
    description: 'Root',
    expected: {'/': {}, '/about': undefined},
  },
  {
    pattern: '/about',
    description: 'Literal segment',
    expected: {'/about': {}, '/about/': {}, '/About': {}, '/about/us': undefined},
  },
  {
    pattern: '/course/:slug',
    description: 'Named param',
    expected: {
      '/course/intro': {slug: 'intro'},
      '/course/intro/': {slug: 'intro'},
      '/course': undefined,
      '/course/intro/extra': undefined,
    },
  },
  {
    pattern: '/:prefix(.*)/course/:slug',
    description: 'Custom regexp param spanning segments (reported in SAPP-4118)',
    expected: {
      '/no/course/intro': {prefix: 'no', slug: 'intro'},
      '/a/b/c/course/intro': {prefix: 'a/b/c', slug: 'intro'},
      '/course/intro': undefined,
      '/no/course/intro/': {prefix: 'no', slug: 'intro'},
    },
  },
  {
    pattern: '/:locale(en|no|se)/blog/:slug',
    description: 'Custom regexp param restricted to an enum',
    expected: {
      '/en/blog/hello': {locale: 'en', slug: 'hello'},
      '/no/blog/hello': {locale: 'no', slug: 'hello'},
      '/de/blog/hello': undefined,
    },
  },
  {
    pattern: '/:id(\\d+)',
    description: 'Custom regexp param restricted to digits',
    expected: {'/123': {id: '123'}, '/abc': undefined, '/123/': {id: '123'}},
  },
  {
    pattern: '/(\\d+)',
    description: 'Unnamed custom regexp group',
    expected: {'/123': {0: '123'}, '/abc': undefined},
  },
  {
    pattern: '/(.*)',
    description: 'Catch-all',
    expected: {
      '/': {0: ''},
      '/about': {0: 'about'},
      '/a/b/c': {0: 'a/b/c'},
      '/about/': {0: 'about/'},
    },
  },
  {
    pattern: '/(.*)/end',
    description: 'Catch-all followed by a literal',
    expected: {'/a/b/end': {0: 'a/b'}, '/end': undefined, '/a/end': {0: 'a'}},
  },
  {
    pattern: '/blog/:slug?',
    description: 'Optional param',
    expected: {'/blog': {}, '/blog/': {}, '/blog/hello': {slug: 'hello'}, '/blog/a/b': undefined},
  },
  {
    pattern: '/:locale?/product/:slug',
    description: 'Optional param before literals',
    expected: {
      '/product/x': {slug: 'x'},
      '/en/product/x': {locale: 'en', slug: 'x'},
      '/en/no/product/x': undefined,
    },
  },
  {
    pattern: '/:path*',
    description: 'Zero or more segments',
    expected: {
      '/': {},
      '/about': {path: ['about']},
      '/a/b/c': {path: ['a', 'b', 'c']},
      '/a/b/c/': {path: ['a', 'b', 'c']},
    },
  },
  {
    pattern: '/blog/:slug+',
    description: 'One or more segments',
    expected: {
      '/blog': undefined,
      '/blog/hello': {slug: ['hello']},
      '/blog/a/b': {slug: ['a', 'b']},
    },
  },
  {
    pattern: '{/:parts}*',
    description: 'Zero or more segments in a group',
    expected: {'/': {}, '/a': {parts: ['a']}, '/a/b': {parts: ['a', 'b']}},
  },
  {
    pattern: '/prefix{/:rest}*',
    description: 'Literal followed by an optional repeated group',
    expected: {'/prefix': {}, '/prefix/a/b': {rest: ['a', 'b']}},
  },
  {
    pattern: '/:attr1?{-:attr2}?',
    description: 'Optional group with a non-slash prefix',
    expected: {'/': {}, '/about': {attr1: 'about'}, '/about-us': {attr1: 'about', attr2: 'us'}},
  },
  {
    pattern: '{-:attr}+',
    description: 'Repeated group joined by a non-slash prefix',
    expected: {'-a': {attr: ['a']}, '-a-b': {attr: ['a', 'b']}},
  },
  {
    pattern: '/api/v:version(\\d+)/items',
    description: 'Param embedded mid-segment',
    expected: {'/api/v2/items': {version: '2'}, '/api/v/items': undefined},
  },
  {
    pattern: '/:slug([a-z0-9-]+)',
    description:
      'Custom regexp param with a character class (throws on native URLPattern unescaped)',
    expected: {'/about': {slug: 'about'}, '/ABOUT': {slug: 'ABOUT'}, '/a_b': undefined},
  },
  {
    pattern: '/books{/:id}',
    description: 'Group without a modifier (required in v6, optional in v8)',
    expected: {'/books': undefined, '/books/1': {id: '1'}},
  },
  {
    pattern: '/files/:name.:ext',
    description: 'Two params separated by a dot',
    expected: {'/files/report.pdf': {name: 'report', ext: 'pdf'}, '/files/report': undefined},
  },
  {
    pattern: '/search/:query',
    description: 'Param carrying percent-encoded characters',
    expected: {
      '/search/hello%20world': {query: 'hello world'},
      '/search/a%2Fb': {query: 'a/b'},
      '/search/caf%C3%A9': {query: 'café'},
    },
  },
]

/** Patterns written for path-to-regexp v8, i.e. the migration studios were told to make. */
const V8_CORPUS: CorpusEntry[] = [
  {
    pattern: '/*prefix/course/:slug',
    description: 'v8 wildcard (the SAPP-4118 workaround)',
    expected: {
      '/no/course/intro': {prefix: ['no'], slug: 'intro'},
      '/a/b/course/intro': {prefix: ['a', 'b'], slug: 'intro'},
      '/course/intro': undefined,
      '/no/course/intro/': {prefix: ['no'], slug: 'intro'},
    },
  },
  {
    pattern: '/*splat',
    description: 'v8 catch-all wildcard',
    expected: {
      '/': undefined,
      '/a': {splat: ['a']},
      '/a/b': {splat: ['a', 'b']},
      '/a/': {splat: ['a', '']},
    },
  },
  {
    pattern: '/:locale/blog/*rest',
    description: 'v8 wildcard after named params',
    expected: {'/en/blog/a/b': {locale: 'en', rest: ['a', 'b']}, '/en/blog': undefined},
  },
  {
    pattern: '/course/:slug',
    description: 'Named param (unchanged between v6 and v8)',
    expected: {'/course/intro': {slug: 'intro'}, '/course/intro/': {slug: 'intro'}},
  },
]

const CORPORA = {
  'path-to-regexp v6': V6_CORPUS,
  'path-to-regexp v8': V8_CORPUS,
}

for (const [era, corpus] of Object.entries(CORPORA)) {
  describe(`parity with ${era}`, () => {
    describe.each(corpus)('$pattern ($description)', ({pattern, expected}) => {
      const matcher = createRouteMatcher(pattern)

      test.each(Object.entries(expected))('%s', (pathname, params) => {
        if (params === undefined) {
          expect(matcher(pathname)).toBeUndefined()
        } else {
          expect(matcher(pathname)).toEqual({path: pathname, params})
        }
      })
    })
  })
}
