name: Build packages
permissions:
  contents: read # for checkout
on:
  # Can only be called remotely
  workflow_call:
    secrets:
      TURBO_TOKEN:
        required: true

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install project dependencies
        run: pnpm install

      - name: Warm up turborepo remote cache
        run: pnpm build --output-logs=full --log-order=grouped
