name: Debug Lerna Lite

on:
  push:
    branches:
      - debug-lerna-lite

permissions:
  contents: read

jobs:
  run-lerna-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: debug-lerna-lite
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.ECOSPARK_APP_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}

      - name: Install deps & build
        run: pnpm install --ignore-scripts

      - name: Build
        run: pnpm build --output-logs=full --log-order=grouped

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Run lerna version
        run: |
          npx lerna version \
          --force-publish \
          --no-push \
          --sync-workspace-lock \
          --conventional-commits \
          --yes
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
