name: Vercel E2E Studio preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_E2E_STUDIO_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_E2E_STUDIO_PROJECT_ID }}
on:
  # Build on pushes branches that have a PR (including drafts)
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-cli:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install project dependencies
        run: pnpm install

      - name: Build CLI
        # This warms up the turborepo remote cache
        run: pnpm build:cli --output-logs=full --log-order=grouped

  deploy-preview:
    runs-on: ubuntu-latest
    needs: [build-cli]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    outputs:
      preview_url: ${{ steps.deploy.outputs.DEPLOY_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install project dependencies
        run: pnpm install

      - name: Build CLI
        # This should take only a few seconds as it'll restore the remote cache that got primed in the `install` job
        run: pnpm build:cli --output-logs=full --log-order=grouped

      - name: dataset setup
        env:
          SANITY_E2E_PROJECT_ID: ${{ vars.SANITY_E2E_PROJECT_ID }}
          SANITY_E2E_SESSION_TOKEN: ${{ secrets.SANITY_E2E_SESSION_TOKEN_NEW }}
          SANITY_E2E_DATASET: pr-${{ github.event.number }}
        run: |
          echo pr-${{ github.event.number }} 
          pnpm e2e:setup

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_E2E_STUDIO_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_E2E_STUDIO_PROJECT_ID }}
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_E2E_STUDIO_TOKEN }}

      - name: Build Project Artifacts
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_E2E_STUDIO_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_E2E_STUDIO_PROJECT_ID }}
          SANITY_E2E_PROJECT_ID: ${{ vars.SANITY_E2E_PROJECT_ID }}
          SANITY_E2E_DATASET: pr-${{ github.event.number }}
        run: vercel build --token=${{ secrets.VERCEL_E2E_STUDIO_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          echo "DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_E2E_STUDIO_TOKEN }} | tail -n 1)" >> $GITHUB_OUTPUT

  E2E-Tests:
    needs: [deploy-preview]
    runs-on: ubuntu-latest
    env:
      DEPLOY_URL: ${{ needs.deploy-preview.outputs.preview_url }}
    steps:
      - name: Run E2E Tests
        run: |
          echo "Running E2E tests against $DEPLOY_URL"
