name: eFPS Test
permissions:
  pull-requests: write # for comment
  statuses: write
  contents: read

on:
  deployment_status:
  workflow_dispatch:
    inputs:
      reference_tag:
        description: "npm reference tag for comparison"
        required: true
        default: "latest"
      enable_profiler:
        description: "Enable profiler"
        required: true
        type: boolean
        default: false
      record_video:
        description: "Record video"
        required: true
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}-${{ github.event.deployment_status.environment }}
  cancel-in-progress: true

jobs:
  get-vercel-url:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview – efps'
    env:
      STATUS_CONTEXT: "eFPS Test / get-vercel-url"
      TARGET_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    outputs:
      deploy_url: ${{ github.event.deployment_status.target_url }}
    steps:
      - name: Debug deployment event
        run: |
          echo "Event: ${{ toJSON(github.event) }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Deployment status state: ${{ github.event.deployment_status.state }}"
          echo "Deployment status environment: ${{ github.event.deployment_status.environment }}"
          echo "Target URL: ${{ github.event.deployment_status.target_url }}"
