name: Exports check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install project dependencies
        env:
         PUPPETEER_SKIP_DOWNLOAD: 'true'
         CYPRESS_INSTALL_BINARY: '0'
        run: yarn install

      # Required for linked packages to work
      - name: Build modules
        id: buildResolver
        run: yarn build

      - name: Check package integrity
        id: checkPackages
        run: yarn check:packages

      # - name: Notify Slack about build failure
      #   if: failure() && github.ref == 'refs/heads/ui/main'
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.ACTIONS_SLACK_BOT_TOKEN }}
      #   uses: voxmedia/github-action-slack-notify-build@v1
      #   with:
      #     channel: studio-internal
      #     status: FAILED
      #     color: danger
