name: Renovate
on:
  schedule:
    - cron: "0 */2 * * *" # Every 2 hours
  pull_request:
    types: [closed]
    branches: [main]
  issues:
    types: [edited]
  workflow_dispatch:

jobs:
  renovate:
    uses: sanity-io/sanity-actions/.github/workflows/renovate.yml@jw/selfhosted-renovate
    with:
      log-level: debug
      autodiscover: false
    secrets: inherit
