name: Test exports works in native node ESM and CJS and TypeScript DTS
on:
  push:
    paths-ignore:
      - "examples/**"
jobs:
  testExports:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Check export conditions in native node ESM and CJS, and TypeScript DTS
        run: pnpm test:exports
